### ISSUE TITLE
EBI SRA "Send to Galaxy" assigning wrong datatype (fastqsanger.gz as fastqsanger)

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/galaxy#6472] opened 2018-07-07 06:31 UTC
Hello,

I was importing fastq.gz files from ENA using the Get Data EBI SRA tool and the "Send to
Galaxy" links and found a bug - the files are incorrectly importing with fastqsanger datatype when they should be fastqsanger.gz.

Tools like FastQC/HISAT2 then fail on the files because they have the wrong datatype. I had to manually convert the datatype of each file (12 in this case) one-by-one from fastqsanger to fastqsanger.gz to get e.g. FastQC to work.

See screenshots below.

This is the ENA study I was importing the files from: https://www.ebi.ac.uk/ena/data/view/PRJNA258286 
and an example file: ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR155/004/SRR1552444/SRR1552444.fastq.gz

ping @bgruening @blankenberg 

<img width="1138" alt="screenshot1" src="https://user-images.githubusercontent.com/5591821/42407481-aff81594-8200-11e8-9faf-4a31c7ff7b77.png">
<img width="935" alt="screenshot2" src="https://user-images.githubusercontent.com/5591821/42407482-b02e5e74-8200-11e8-8086-3a4013806b8a.png">
<img width="412" alt="screen shot 2018-07-07 at 4 16 28 pm" src="https://user-images.githubusercontent.com/5591821/42407508-2bf6ec7e-8201-11e8-96e5-34d8afb4f173.png">

**Comment by blankenberg** [comment] 2018-07-09 14:59
Can confirm this behavior. 

Of particular note, it is probably not limited to just EBI SRA, but **all** data source tools using the default `data_source.py` method with ext auto-detect.

**Comment by jennaj** [comment] 2018-07-18 15:14
Duplicated issue (found original @mblue9 !). Linking the two, should probably close one of them: https://github.com/galaxyproject/galaxy/issues/6334

**Comment by jennaj** [comment] 2018-07-18 15:21
Many bug reports about this (always from a downstream tool, and can vary). 

Example biostars post: https://biostar.usegalaxy.org/p/28726/

**Comment by nsoranzo** [comment] 2018-07-18 15:21
Duplicate of #6334.

**Closed as completed by nsoranzo** 2018-07-18 15:21 UTC
Labels: kind/bug, area/tools, area/datatypes

**Comment by jennaj** [comment] 2018-09-21 17:05
**Note to usegalaxy.* users:** This is resolved at usegalaxy.org now. It will be resolved soon at usegalaxy.eu and usegalaxy.org.au and other public Galaxy servers when those servers update to the next Galaxy release.
