### ISSUE TITLE
Libraries: checking/unchecking `include deleted` multiple times (virtually) duplicates the total number of datasets

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11995] opened 2021-05-18 18:04 UTC
![issue-libs-01](https://user-images.githubusercontent.com/46503462/118701104-a5c56a80-b813-11eb-885b-e8dc68b32d06.gif)

**Comment by OlegZharkov** [comment] 2021-05-19 12:47
how did you manage to do it? I cannot reproduce 
![delete-lib](https://user-images.githubusercontent.com/15801412/118814962-03f45b00-b8b1-11eb-8f7b-d96bfa07d179.gif)

**Comment by davelopez** [comment] 2021-05-19 13:28
> What does backend return you? (open network tab in chrome please)

It always returns the same collection of libraries so I guess is some strange edge use case.

**Comment by ksuderman** [comment] 2021-05-19 19:40
I am able to reproduce this on main, but not the other test instances.  However, I noticed something; toggling the "Include deleted" button doesn't included deleted datasets, it includes the non-deleted elements twice.  In David's screencap you can see the list since increase by 26 each time, while in my case it increases by 49.  I looked at the network traffic from the backend and it is just returning a list of 49 items with `deleted=false`.  To make this easier to see I filter the library list to include a single item.
![library](https://user-images.githubusercontent.com/4098072/118874073-7c124f00-b8b8-11eb-933e-3ce6b3c039e2.gif)

**Comment by davelopez** [comment] 2021-05-19 20:46
Thanks @ksuderman!
@OlegZharkov solved the mystery in his #12011 PR. It turns out the behavior of `Include deleted` is different when you are an Admin or a regular user. The UI was expecting only deleted items when calling the API with `deleted=true`, which is the case when you are an Admin, but, in the case of a regular user, the complete list of items is returned.
So, in the end, the `Include deleted` should be an Admin-only option. I wonder if we should always return an empty list for `deleted=true` in the case of regular users just for consistency...

**Comment by OlegZharkov** [comment] 2021-05-20 14:25
thanks @ksuderman and @davelopez , it's fixed in https://github.com/galaxyproject/galaxy/pull/12011

**Closed as completed by OlegZharkov** 2021-05-20 14:25 UTC
Labels: kind/bug, area/UI-UX, area/libraries, paper-cut
