### ISSUE TITLE
Duplicating WF step duplicates step label and annotation within the duplicated step

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11287] opened 2021-02-03 14:25 UTC
![Screenshot from 2021-02-03 15-22-56](https://user-images.githubusercontent.com/4742081/106760135-c20e1480-6633-11eb-8fc4-71bd19ba47fa.png)

With that the WF becomes unsaveable because of the duplicated step label.

This is either a very recent regression or it doesn't happen all the time cause I don't remember having seen this before last week.

**Comment by mvdbeek** [comment] 2021-02-03 14:30
I think that's a duplicate of https://github.com/galaxyproject/galaxy/issues/10979

**Closed as completed by mvdbeek** 2021-02-03 14:30 UTC
Labels: kind/bug, area/workflows
