### ISSUE TITLE
[release-testing] Applying a cutoff time on admin jobs page does not show any jobs unless the cutoff time is very large

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14094] opened 2022-06-17 15:07 UTC
Testing #13893.

If the job cutoff filter on the admin jobs page is not selected, all running jobs are listed (as expected).

If the job cutoff filter is selected, no jobs are listed for the default time of 5 minutes (even after checking the page immediately after starting a few new jobs.) Jobs are only shown If the cutoff time is set to a really high value (ca. 900 minutes or more).

**Comment by dannon** [comment] 2022-06-24 12:00
@simonbray Can you add a screenshot of what you're seeing maybe?  When I test a local job here, I see the following.

![image](https://user-images.githubusercontent.com/155398/175529769-da2d1d11-3d3a-400e-a859-69c5f529f874.png)

**Comment by dannon** [comment] 2022-07-02 23:58
I'm going to close this one out since it seems to be working well in my testing.  If we can reproduce the failure feel free to reopen!

**Comment by simonbray** [comment] 2022-07-05 10:12
Hi @dannon, I've been offline for a couple of weeks but tested again today (the same way as you described). Here are some screenshots.

Cutoff time of 100:

![image](https://user-images.githubusercontent.com/32272674/177305152-4ab7cc9a-445d-4f75-8c46-3eca3349d06c.png)

Cutoff time of 1000:

![image](https://user-images.githubusercontent.com/32272674/177305256-dc7002f3-fa56-47ad-91c6-df2555a08342.png)

**Comment by simonbray** [comment] 2022-07-05 14:54
For 100 minutes:

`http://localhost:8080/api/jobs?view=admin_job_list&date_range_min=2022-07-05T13:05:51.206Z`

For 1000 minutes:

`http://localhost:8080/api/jobs?view=admin_job_list&date_range_min=2022-07-04T22:06:23.994Z`

After a bit of tinkering I found that an API request with `2022-07-04T23:59:59` gives all the jobs I ran today whereas `2022-07-05T00:00:00` gives nothing - can it be that everything after `T` is being thrown away?

**Comment by simonbray** [comment] 2022-07-06 06:50
I tried URL-encoding the string but it doesn't make a difference.

**Comment by davelopez** [comment] 2022-07-12 08:03
Fixed in https://github.com/galaxyproject/galaxy/pull/14281

**Comment by mvdbeek** [comment] 2022-08-15 11:30
Seems to have re?-appeared now, I wonder if we *also* need to urlencode the time / use the params object in axios.
![Uploading cutoff bug.gif…]()

**Comment by mvdbeek** [comment] 2022-08-15 15:31
It's not the urlencoding, the problem is the Zulu postfix, which means we get UTC times, while all our sqlalchemy / database times do not carry the `tzinfo` ...
```ipython
In [1]: from pydantic import BaseModel

In [2]: from datetime import datetime

In [3]: class Time(BaseModel):
   ...:     time: datetime
   ...:

In [4]: Time(time="2022-08-15T13:37:32.05700Z")
Out[4]: Time(time=datetime.datetime(2022, 8, 15, 13, 37, 32, 57000, tzinfo=datetime.timezone.utc))

In [5]: Time(time="2022-08-15T13:37:32.05700")
Out[5]: Time(time=datetime.datetime(2022, 8, 15, 13, 37, 32, 57000))
```

**Closed as completed** 2022-08-17 20:37 UTC
Labels: kind/bug, area/UI-UX, area/admin
