### ISSUE TITLE
More fine grained API access 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13737] opened 2022-04-16 17:24 UTC
It would be nice if we can provide more fine-grained API access to certain features. 

Use-cases:

* a user wants to give another user read-only access to the account
* a user-support role should be able to debug user sessions, but not be able to install tools etc.
* automatic tool installation bots do not need access to data and user accounts
* if we have a notification system in place it would be nice if our support and outreach people can notify users, without having admin access

GitHub personal access token page:

![image](https://user-images.githubusercontent.com/469983/163684973-7289dfe5-7c05-4e6d-a1b6-e9f8ba44b11d.png)

GitLab UI:

![image](https://user-images.githubusercontent.com/469983/163684916-6ee2dea1-5f73-4c09-a020-ce9f935c159a.png)

**Comment by hexylena** [comment] 2022-04-19 09:56
duplicate of https://github.com/galaxyproject/galaxy/issues/1524 :( I want it too, so so badly.

**Closed as completed by hexylena** 2022-04-19 09:56 UTC

**Comment by bgruening** [comment] 2022-04-19 10:13
Upps, sorry was not able to find it. "Scoped API keys" sounds cool! Thanks.

**Comment by hexylena** [comment] 2022-04-19 10:14
no worries! thanks for the nice screenshots, hopefully it makes it clearer for some future implementer what we need!
