### ISSUE TITLE
scripts/cleanup_datasets use galaxy.ini

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#5952] opened 2018-04-23 07:43 UTC
The scripts/cleanup_datasets directory uses the galaxy.ini file instead of the new galaxy.yml file by default.

**Comment by nsoranzo** [comment] 2018-04-23 09:04
Duplicate of https://github.com/galaxyproject/galaxy/issues/5941

**Closed as completed by nsoranzo** 2018-04-23 09:04 UTC
