### ISSUE TITLE
Collection and pages

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#7912] opened 2019-05-08 10:05 UTC
Hi,

If I have a few thousand items in my history the GUI shows pages with 500 elements each. If I do the same with collections, the GUI displays a message `showing only the first 1000 elements of xxxx`. It would be an improvement for the GUI to have pages within collections too.

Tested Galaxy server: usegalaxy.eu

Best,

Joachim

**Comment by mvdbeek** [comment] 2019-05-08 10:27
duplicate of https://github.com/galaxyproject/galaxy/issues/3054

**Closed as completed by mvdbeek** 2019-05-08 10:27 UTC
