### ISSUE TITLE
API exception when querying tool that is no longer installed

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11494] opened 2021-02-26 04:29 UTC
Galaxy 21.01
GET /api/tool_shed_repositories/778b1fea2ce4b3a3 throws a nondescript exception when the tool is no longer installed.

In the logs it appears as:
```
[pid: 16|app: 0|req: 30/30] 172.19.0.1 () {40 vars in 625 bytes} [Tue Feb 23 22:45:37 2021] GET /api/tool_shed_repositories/167a8bd08c2b5445 => generated 71 bytes in 10 msecs (HTTP/1.1 500) 3 headers in 158 bytes (1 switches on core 3)
galaxy.web.framework.decorators ERROR 2021-02-23 22:45:37,630 [p:16,w:1,m:0] [uWSGIWorker1Core2] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/srv/galaxy/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py", line 452, in show
    tool_shed_repository = get_tool_shed_repository_by_id(self.app, id)
  File "/srv/galaxy/lib/galaxy/tool_shed/util/repository_util.py", line 511, in get_tool_shed_repository_by_id
    .filter(app.install_model.ToolShedRepository.table.c.id == app.security.decode_id(repository_id)) \
  File "/srv/galaxy/lib/galaxy/security/idencoding.py", line 84, in decode_id
    return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
ValueError: invalid literal for int() with base 10: "\x15';!kV"
172.19.0.1 - - [23/Feb/2021:22:45:37 +0000] "GET /api/tool_shed_repositories/778b1fea2ce4b3a3 HTTP/1.1" 500 - "-" "terraform-provider-galaxy/galaxy - blend4go (devel)"
```

I expect that GET /api/tool_shed_repositories/778b1fea2ce4b3a3 should return an error saying that the tool is invalid

**Comment by innovate-invent** [comment] 2021-03-31 17:19
To clarify: the ID was valid, the tool is uninstalled, and then querying the endpoint resulted in this error.

**Comment by mvdbeek** [comment] 2021-04-01 17:20
Are you maybe mixing the changeset_revision or installed_changeset_revision (corresponding to a mercurial commit) or a repository id from the toolshed with the repository id (an integer primary key for that repository hashed using your instances secret key  ) ?

**Comment by innovate-invent** [comment] 2021-04-01 17:58
`POST /api/tool_shed_repositories/new/install_repository_revision` returns a structure with an `id` field. That is retained and appended to `GET /api/tool_shed_repositories/`. If the tool is uninstalled and `GET /api/tool_shed_repositories/778b1fea2ce4b3a3` is requested after, it throws that exception.

**Comment by davelopez** [comment] 2021-04-15 13:55
Hi @innovate-invent,
I wanted to fix this as part of the [paper-cuts event](https://galaxyproject.org/events/2021-04-papercuts/) but I couldn't reproduce it. Can you please help me reproducing it?
This is what I tried:
- `POST /api/tool_shed_repositories/new/install_repository_revision` with payload:
  ````json
  {
      "tool_shed_url":"https://toolshed.g2.bx.psu.edu/",
      "name":"text_processing",
      "owner":"bgruening",
      "changeset_revision":"ddf54b12c295"
  }
  ````
- The previous API call returns something like this:
  ````json
  [
    {
      "id": "f597429621d6eb2b",
      "tool_shed": "toolshed.g2.bx.psu.edu",
      "name": "text_processing",
      "owner": "bgruening",
      "installed_changeset_revision": "ddf54b12c295",
      "changeset_revision": "ddf54b12c295",
      "ctx_rev": "16",
      "includes_datatypes": false,
      "tool_shed_status": {
        "latest_installable_revision": "True",
        "repository_deprecated": "False",
        "revision_update": "False",
        "revision_upgrade": "False"
      },
      "deleted": false,
      "uninstalled": false,
      "dist_to_shed": false,
      "status": "Installed",
      "error_message": "",
      "description": "High performance text processing tools using the GNU coreutils, sed, awk and friends.",
      "url": "/api/tool_shed_repositories/f597429621d6eb2b"
    }
  ]
  ```` 
- Then I uninstall using `DELETE /api/tool_shed_repositories?tool_shed_url=https://toolshed.g2.bx.psu.edu/&name=text_processing&owner=bgruening&changeset_revision=ddf54b12c295`
- Finally, I call `GET /api/tool_shed_repositories/f597429621d6eb2b` and get the result:
  ````json
  {
    "id": "f597429621d6eb2b",
    "tool_shed": "toolshed.g2.bx.psu.edu",
    "name": "text_processing",
    "owner": "bgruening",
    "installed_changeset_revision": "ddf54b12c295",
    "changeset_revision": "ddf54b12c295",
    "ctx_rev": "16",
    "includes_datatypes": false,
    "tool_shed_status": {
      "latest_installable_revision": "True",
      "repository_deprecated": "False",
      "revision_update": "False",
      "revision_upgrade": "False"
    },
    "deleted": true,
    "uninstalled": true,
    "dist_to_shed": false,
    "status": "Uninstalled",
    "error_message": "",
    "description": "High performance text processing tools using the GNU coreutils, sed, awk and friends.",
    "url": "/api/tool_shed_repositories/f597429621d6eb2b"
  }
  ````
Notice the `"uninstalled": true` and `"status": "Uninstalled"`. So I didn't get any errors.
I tested this in the latest `dev` branch so maybe it is something that is already fixed?
Anyway, can you double-check the issue is not due to a bad `id` as Marius suggested? which, from the traceback, is most likely.

**Comment by innovate-invent** [comment] 2021-04-15 18:29
I think the most notable difference is that I delete by id (`DELETE /api/tool_shed_repositories/f597429621d6eb2b`) and might have remove_from_disk=1 set.

If you would like to have a peek at my code, the relevant links are:
https://github.com/brinkmanlab/terraform-provider-galaxy/blob/157d2acf1d5c9d85a74136a3cc8d59cd0f702ec9/galaxy/resource_repository.go#L371
https://github.com/brinkmanlab/terraform-provider-galaxy/blob/157d2acf1d5c9d85a74136a3cc8d59cd0f702ec9/galaxy/resource_repository.go#L333
https://github.com/brinkmanlab/blend4go/blob/90e48c00fefc0577bc356a60126b8d34ded0d442/repositories/repositories.go#L146-L160

**Comment by davelopez** [comment] 2021-04-16 09:34
I just tried the same process but using `DELETE /api/tool_shed_repositories/f597429621d6eb2b?remove_from_disk=true` and the result is the same, no error.
In any case, if I slightly alter the id to make it invalid, obviously the error is raised and it is a `500 Internal Server Error` which is not helpful. I will change it to raise a 404 instead and hopefully, we can better track what is causing the invalid `id` in your case.

**Comment by davelopez** [comment] 2021-04-16 13:54
The misleading `500 Internal Server Error` should be fixed in https://github.com/galaxyproject/galaxy/pull/11856

**Comment by mvdbeek** [comment] 2021-06-15 10:29
I think we can call this fixed with https://github.com/galaxyproject/galaxy/pull/11856

**Closed as completed by mvdbeek** 2021-06-15 10:29 UTC
Labels: kind/bug, area/API, paper-cut
