### ISSUE TITLE
Feature request - Filenames based on dataset collection identifier

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2140] opened 2016-04-12 18:25 UTC
I'm trying to incorporate the use of dataset collections to simplify workflows, esp. ones with many samples (e.g. RNA-Seq). One issue I'm running into is when I need to get the data outside of galaxy, either for external analysis (e.g. in R) or visualization on UCSC. In both cases, the data is referenced as the "name" of the file (e.g. "Tophat on dataset 1 and 2: accepted hits") instead of the collection id (e.g. sample A). It would be nice if there was a way to expose this "collection id" when exporting data.

**Comment by jmchilton** [comment] 2016-09-30 15:01
So when downloading a collection item from the history panel - you want the name of the downloaded file to be `<GalaxyCollectionHID>-[<element_identifier>].<extension>` instead of `<GalaxyDatasetHID>-[<name>.<extension>]`? Is that enough?

Update: I think you comments on this https://github.com/galaxyproject/galaxy/issues/2023 are a little more concrete in terms of how implement this. Can we close this as a duplicate of that?

**Comment by lparsons** [comment] 2016-09-30 15:12
That seems about right, except I'm not clear on what `<GalaxyCollectionHID>` actually is. Perhaps an example would help:

#### History
- Tophat accepted hits
  - sample A
  - sample B
- featureCounts (gene counts)
  - sample A
  - sample B

#### Exported filenames

```
Tophat accepted hits: sample A.bam
Tophat accepted hits: sample B.bam
featureCounts (gene counts): sample A.tabular
featureCounts (gene counts): sample B.tabular
```

**Comment by jmchilton** [comment] 2016-09-30 15:13
So is this for history export and not file download?

**Comment by lparsons** [comment] 2016-09-30 15:15
I was thinking file download (though downloading a collection would be VERY nice). Hadn't really thought about history export, it's so slow it isn't used much, but it would be great there too. Also, exposed when sent to external viewers such as UCSC.

**Comment by mvdbeek** [comment] 2017-01-26 09:35
> Also, exposed when sent to external viewers such as UCSC.

That last one would be a huge win ... if load up a bunch of files in IGV this would be super-helpful.

**Closed as completed** 2017-05-02 13:27 UTC
Labels: kind/enhancement, area/UI-UX, kind/feature, area/dataset-collections
