### ISSUE TITLE
api/workflows/<id>/download requires the workflow to be published instead of importable

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14348] opened 2022-07-19 15:05 UTC
Could we check that it's not public first, and then require authentication?

**Comment by davelopez** [comment] 2022-07-20 12:04
Hi @hexylena! can you help me reproduce this? Is this happening in a particular galaxy instance or version?

I've tried downloading a random workflow from the published pages in `org` (22.05), `eu` (22.01), and local (dev branch) without logging in and it seems to work:

```
curl -X 'GET' \
  'https://usegalaxy.eu/api/workflows/79eb28066236e836/download' \
  -H 'accept: application/json'
```

```
curl -X 'GET' \
  'https://usegalaxy.org/api/workflows/ef2c1fb7d6a51b3a/download' \
  -H 'accept: application/json'
```

**Comment by hexylena** [comment] 2022-07-20 12:33
Sure thing! `6ae84da19987dc85` was a workflow ID provided by Nate on .org for use in ptdk. ptdk requires that workflows are made public first so it can download them. However I could not construct a valid URL for this workflow to view it myself (logged in), nor download it (until I started supplying an API key) despite that it's public (but maybe not publicly listed?)

**Comment by davelopez** [comment] 2022-07-20 12:56
> despite that it's public (but maybe not publicly listed?)

As far as I know, making it public will make it appear in the published workflows list :thinking:

> https://usegalaxy.eu/api/workflows/6ae84da19987dc85/download (only works if api key supplied.)

I don't think the same workflow ID will work both in org and eu, so I guess you meant https://usegalaxy.org/api/workflows/6ae84da19987dc85/download 

Can you confirm that `6ae84da19987dc85` workflow is really published in org? If I try to download it (even when I'm logged in) using https://usegalaxy.org/api/workflows/6ae84da19987dc85/download I get:
```json
{
"err_msg": "Workflow is not owned by or shared with current user",
"err_code": 403002
}
```
My suspicion is that this workflow is not really published, maybe just shared with you? (that would explain why you can download it when logged in), but I might be missing something here...

**Comment by hexylena** [comment] 2022-07-20 18:37
> I don't think the same workflow ID will work both in org and e

indeed, typo on my part.

>  If I try to download it (even when I'm logged in) using https://usegalaxy.org/api/workflows/6ae84da19987dc85/download I get:

yes exactly the issue I see :) 

If you try that same URL with your API key, then you should get the workflow.

```
$ curl https://usegalaxy.org/api/workflows/6ae84da19987dc85/download
{"err_msg": "Workflow is not owned by or shared with current user", "err_code": 403002}%                                                                                      $ curl https://usegalaxy.org/api/workflows/6ae84da19987dc85/download\?key\=$GALAXY_USER_KEY| jq | head
{
  "a_galaxy_workflow": "true",
  "annotation": "",
  "format-version": "0.1",
  "name": "GTN - Sequence Analyses - Quality Control (imported from uploaded file)",
  "steps": {
    "0": {
      "annotation": "",
      "content_id": null,
      "errors": null,
```

It is not shared with me, personally. This works with two different API keys.

**Comment by natefoo** [comment] 2022-07-20 22:50
Sooooooooooooo

It was accessible until an hour or two when I disabled it. I just re-enabled it.

Sorry.

**Comment by nsoranzo** [comment] 2022-07-20 23:07
I believe the issue is that (now that @natefoo has made it accessible again) the workflow in question is importable but not published. I think this should fix it, but I need to write a test before making a PR:

```diff
diff --git a/lib/galaxy/managers/workflows.py b/lib/galaxy/managers/workflows.py
index 1f866fb020..d7b492bb96 100644
--- a/lib/galaxy/managers/workflows.py
+++ b/lib/galaxy/managers/workflows.py
@@ -276,7 +277,7 @@ class WorkflowsManager(sharable.SharableModelManager):
         stored_workflow = self.get_stored_workflow(trans, workflow_id, by_stored_id=by_stored_id)
 
         # check to see if user has permissions to selected workflow
-        if stored_workflow.user != trans.user and not trans.user_is_admin and not stored_workflow.published:
+        if stored_workflow.user != trans.user and not trans.user_is_admin and not stored_workflow.importable:
             if (
                 trans.sa_session.query(trans.app.model.StoredWorkflowUserShareAssociation)
                 .filter_by(user=trans.user, stored_workflow=stored_workflow)
```

**Comment by nsoranzo** [comment] 2022-07-21 02:56
It should be fixed by https://github.com/galaxyproject/galaxy/pull/14355 .

**Comment by davelopez** [comment] 2022-07-21 08:35
> It was accessible until an hour or two when I disabled it. I just re-enabled it.

lol, that explains why I was getting the same error also with my API key, I was sooooo confused! :rofl: Thanks for confirming.

So, if I understand it correctly now, it was the other way around, the workflow is not really *published*, but it is *importable* and we want to give access through the API to whoever has the link or the ID right?
In that case thanks for fixing it @nsoranzo :+1:

**Comment by nsoranzo** [comment] 2022-07-21 08:53
Yep, exactly.

**Closed as completed** 2022-07-21 09:25 UTC
Labels: kind/bug, area/API
