### ISSUE TITLE
Indicate state of dataset pair based on state on contained datasets

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#1528] opened 2016-01-17 21:39 UTC
On importing a number of datasets and organising them into a list of pairs, each pair is labelled in green, even when the contained datasets are either grey (not yet processed) or yellow (processing in progress).

The dataset pairs should instead be labelled according to the colour of the individual datasets contained in the pair.

**Comment by jmchilton** [comment] 2016-01-19 14:28
Duplicate of https://github.com/galaxyproject/galaxy/issues/1244, both are particular symptoms of general problem - collections are largely stateless in the UI.

**Closed as completed** 2016-01-19 14:48 UTC
