### ISSUE TITLE
Collections and datasets can end up in different histories during exports from data libraries

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#9714] opened 2020-05-05 08:50 UTC
Steps to reproduce:
- In a data library, select some datasets
- `Export to History` -> `as a Collection`
- In the `Create History Collection from Datasets` dialogue, keep things at their default, but type the name of a new history under `or create new:`
- Finish the export 

Expected outcome: The collection and its constituting datasets should be created in the new history

Actual result: The collection will be created in the new history, but its datasets will become part of the history that was your active history at export time.

**Comment by mvdbeek** [comment] 2020-05-05 11:20
Ah, that's a long standing issue I think. Working on a fix.

**Comment by mvdbeek** [comment] 2020-05-05 11:21
I guess this is a duplicate of https://github.com/galaxyproject/galaxy/issues/8238

**Closed as completed by mvdbeek** 2020-05-05 11:21 UTC
Labels: kind/bug
