### ISSUE TITLE
Notification icon restarts blinking after reload

### ISSUE THREAD

**Issue by mschatz** [galaxyproject/galaxy#16399] opened 2023-07-13 07:14 UTC
**Describe the bug**
The notification icon starts blink to highlight the release notes. After clicking the icon, it displays the release notes and the blinking stops. However, when I navigate to a new page, the notification icon starts blinking again. Clicking the notification icon again stops the blinking but then restarts when navigating to a new page.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org on July 13, 2023
{"version_major":"23.1","version_minor":"rc1"}

**To Reproduce**
Go to https://usegalaxy.org/. See blinking notification icon. Click to stop blinking. Reload the site (e.g. clink the home icon) and the blinking starts again

**Expected behavior**
Blinking should stop after viewing the release notes

**Comment by davelopez** [comment] 2023-07-13 08:04
Duplicate of #16375

**Comment by mvdbeek** [comment] 2023-07-24 09:25
Closing as duplicate, but this is really a very high priority issue to fix.

**Closed as completed by mvdbeek** 2023-07-24 09:25 UTC
