### ISSUE TITLE
Actions "for all selected" seem broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5354] opened 2018-01-20 15:00 UTC
On the dev branch it seems that actions for multiple selected data sets are only executed for one of the selected data sets. This happened for delete and unhide. 

Building dataset lists is working.

**Comment by dannon** [comment] 2018-01-20 20:53
@bernt-matthias Thanks for the report, I'll take a look.

**Comment by dannon** [comment] 2018-02-02 02:38
I thought I reproduced this before, but I tried again today and am not having any luck this time.  Selecting multiple datasets in the history, I'm able to use toggle hide, delete, unhide, and undelete and it's all working.  I don't *think* anyone else has fixed this intentionally yet (I've been out a few days), but I could be wrong.  Are you still seeing the same behavior?

Ping @mvdbeek maybe, I think you said you saw it, too?

**Comment by bernt-matthias** [comment] 2018-02-02 09:20
Also tried. Works on dev and 17.09. Great :)

**Comment by mvdbeek** [comment] 2018-02-02 09:29
What I've seen is that the delete operation fails on the first collection and stops all subsequent operations, that is definitely still an issue on dev and is not fixed by https://github.com/galaxyproject/galaxy/pull/5443
(I did rebuild the client)
![screen shot 2018-02-02 at 10 25 53](https://user-images.githubusercontent.com/6804901/35726069-d996db50-0803-11e8-9b7c-9d90e8033f67.png)

**Comment by dannon** [comment] 2018-02-02 11:05
@mvdbeek Ok, that screenshot is a clue, thanks.  Maybe this only happens when collections are in non-terminal states and/or jobs are running?  I'll try a few more things.

**Comment by mvdbeek** [comment] 2018-02-02 12:32
interesting, a simple collection in a new history has no problems, I'll try to narrow this down some more

**Comment by dannon** [comment] 2018-02-02 13:36
@mvdbeek Well, the traceback you're seeing there is related to the collection job state tracking.  My guess is there's a sync event firing after the model deletion (due to the job state changes, maybe?), causing the failure here.  This patch could fix it - https://gist.github.com/2786abaa792479fdf79345bdb598d682

jobStateSummariesCollection being undefined is guarded against similarly elsewhere.  If you can reproduce it and this works for you, let me know and I'll PR it.

**Comment by mvdbeek** [comment] 2018-02-02 13:47
@dannon fantastic, that works like a charm, thanks so much!

**Comment by dannon** [comment] 2018-02-02 13:57
@mvdbeek Thanks for testing it, I'll open a PR.

**Comment by jmchilton** [comment] 2018-02-02 17:42
Fixed in #5444

**Closed as completed by jmchilton** 2018-02-02 17:42 UTC
