### ISSUE TITLE
Workflow connection is broken when tool param or label updated

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7963] opened 2019-05-14 21:17 UTC
version 19.05
This occurs when a collection is sent to a multiple=true input of a tool. The tool is not mapped over so when I try to remake the connection without breaking the output I get 
![Screenshot_2019-05-14_14-12-27](https://user-images.githubusercontent.com/1768820/57732892-f917e780-7652-11e9-82a6-d116125f6314.png)

**Comment by mvdbeek** [comment] 2019-05-15 15:32
So this is intentional, and not so easy to fix. See https://github.com/galaxyproject/galaxy/issues/7431#issuecomment-478714812

**Comment by martenson** [comment] 2019-05-15 15:54
This seems like a duplicate of the issue linked above, let's discuss there please, closing.

**Comment by innovate-invent** [comment] 2019-05-15 16:00
@mvdbeek The issue isn't that I can't recreate the connection, the issue is that the mapping of the tool is unstable and is reevaluated any time you change a tool parameter. The code that is reevaluating the mapping appears to draw a different conclusion than the code that originally made the mapping, invalidating and breaking existing links.

**Comment by mvdbeek** [comment] 2019-05-15 16:03
And is that wrong ? If yes a reproducible example would be good.

**Comment by innovate-invent** [comment] 2019-05-15 16:04
Why would changing the tool label invalidate the tools connections?

**Comment by mvdbeek** [comment] 2019-05-15 16:06
it doesn't for me, that's why I am asking for an example.

**Comment by mvdbeek** [comment] 2019-05-15 16:12
OK, I see it, need to connect a list to a multiple=True and something to the output.

**Comment by innovate-invent** [comment] 2019-05-15 16:14
I can't readily locate a tool with a single input and a multiple=true input so you will have to patch the awk tool https://raw.githubusercontent.com/bgruening/galaxytools/bc9dc2fc8a806b312d679466d1ea581f3ded35ee/tools/text_processing/text_processing/awk.xml

![image](https://user-images.githubusercontent.com/1768820/57792716-8b23fc80-76f4-11e9-9d4f-c224c02deca6.png)


[Galaxy-Workflow-Tool_Connection_Break.ga.tar.gz](https://github.com/galaxyproject/galaxy/files/3183436/Galaxy-Workflow-Tool_Connection_Break.ga.tar.gz)

Creating this example it appears that it initially tries to map over a multiple=true input but once the connection is made it falls back to not mapped over

**Comment by martenson** [comment] 2019-05-15 16:17
Thanks for clarification and sorry for closing, I misread this as a duplicate.

**Comment by mvdbeek** [comment] 2019-05-15 21:02
Alright, this should be fixed by https://github.com/galaxyproject/galaxy/pull/7979

**Closed as completed** 2019-05-16 17:42 UTC
