### ISSUE TITLE
AVIVATOR can not load TIFF file

### ISSUE THREAD

**Issue by nilchia** [galaxyproject/galaxy#17718] opened 2024-03-14 12:51 UTC
**Describe the bug**
I uploaded to tiff images to check the avivator but it gives this error:
'Something has gone wrong loading your image. Please refer to the [docs](http://viv.gehlenborglab.org/) for information about supported file formats.'
However the images can be opened by Tiff viewer.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**
Operating System: Windows,
Browser: Chrome,

**To Reproduce**
1. upload a Tiff image
2. Go to Visualize
3. Open AVIVATOR

**Expected behavior**
AVIVATOR should be able to work with regular Tiff.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/66441226/f3b29c9d-f948-42fa-984e-5d4265ec2432)

**Comment by davelopez** [comment] 2024-03-14 13:11
Can you check what is the error Avivator is giving in the console?

I guess this is likely Avivator (an external app unrelated to Galaxy) not supporting or liking a particular Tiff format.

You can try to directly load your example Tiff file in Avivator using the "CHOOSE A FILE" button. If it works, then there is a chance we can fix something in Galaxy to make it work, otherwise, there is nothing we can do apart from reporting the issue upstream.

**Comment by nilchia** [comment] 2024-03-14 14:33
The error is this:
Something has gone wrong loading your image. Please refer to the [docs](http://viv.gehlenborglab.org/) for information about supported file formats.

It works fine when I upload with  "CHOOSE A FILE".
![image](https://github.com/galaxyproject/galaxy/assets/66441226/224ed383-8cdb-482b-804b-6980ac80463a)

**Comment by davelopez** [comment] 2024-03-14 14:43
How strange, this is literally the image I tried in the original PR https://github.com/galaxyproject/galaxy/pull/17554 :laughing: 

Ok, I'll take a look when I can.

**Comment by bgruening** [comment] 2024-03-25 14:39
From EU: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/7837d4769d020027aa6b193f7f24c3137f9c90aa/templates/nginx/galaxy-main.j2#L81

ping @natefoo

**Comment by mvdbeek** [comment] 2024-03-25 14:44
The display application should set the CORS header, the issue is likely https://github.com/galaxyproject/galaxy/issues/17643

**Comment by davelopez** [comment] 2024-03-28 10:48
Closing this as a duplicate of https://github.com/galaxyproject/galaxy/issues/17643

**Closed as completed by davelopez** 2024-03-28 10:48 UTC
Labels: kind/bug
