### ISSUE TITLE
create_db.sh not running migration scripts in 20.05

### ISSUE THREAD

**Issue by AndreasSko** [galaxyproject/galaxy#9787] opened 2020-05-19 12:48 UTC
When running the `create_db.sh` script before the first start of Galaxy, the startup will fail with the error:
```
Traceback (most recent call last):
  File "/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "tool_shed_repository" does not exist
LINE 2: FROM tool_shed_repository
```
(this does not happen when letting Galaxy itself initialize the DB on first start).

After looking into this issue, I found that the `create_db.sh` script does not run the migration scripts anymore (the error above would be solved, for example, by https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/migrate/versions/0090_add_tool_shed_repository_table_columns.py). But as `migrate_version` is still getting updated to the newest one, Galaxy won't realize that it still needs to run the migration. 
I believe that https://github.com/galaxyproject/galaxy/pull/9491 introduced this issue (testing it with an earlier commit worked fine).

**Comment by mvdbeek** [comment] 2020-05-19 14:22
The script didn't create the install database, the migrations for the Galaxy database proper were applied (without going through the migrations, that is fine). The script should probably also create the install database if no separate install database is configured.

How did you reach the conclusion https://github.com/galaxyproject/galaxy/pull/9491 is at fault ? I don't think the script would have ever created the install database if you didn't add the `install` argument.

**Comment by AndreasSko** [comment] 2020-05-19 15:06
So I was using `create_db.sh` to initialize the Galaxy DB for a few months now in my [Dockerfile](https://github.com/AndreasSko/docker-galaxy-stable/blob/247287dc325378593a6c0ca8b840048216754963/compose-v2/galaxy-postgres/Dockerfile#L24). This worked for me up to 20.01, see [these logs](https://github.com/AndreasSko/docker-galaxy-stable/runs/655793033?check_suite_focus=true#step:6:1180). Since upgrading to 20.05 the same call would not create a proper DB anymore, resulting in Galaxy not being able to start up ([Logs](https://github.com/AndreasSko/docker-galaxy-stable/runs/656958322?check_suite_focus=true#step:7:7201)). Since reverting the change in #9491 this works again, so I was concluding that the changes there must have changed the behavior of `create_db.sh`.  
Of course, it can be that I misunderstand the behavior of this script (`galaxy` always worked the way I wanted it to, while `install` somehow doesn't find my PSQL, even though I point it to the right config-file), though I'm wondering what `galaxy` is then used for, if Galaxy is not able to start afterwards.

**Comment by mvdbeek** [comment] 2020-05-19 15:32
Arguably Galaxy should not start if it's misconfigured (it expects the install tables to be in the same database, but that's not what create_db.py does), though the exception could be more explicit.

It seems Galaxy may have created the install database if necessary prior to https://github.com/galaxyproject/galaxy/pull/9491, but staring at the change I can't figure out how this PR in particular would be at fault. I try to reproduce this

You may want to create a database without creating a install database because you're creating this somewhere else or your fetching it from CVMFS for instance. That is what create_db.py does by default at this point. https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:fix_9787?expand=1 would change this to match what Galaxy does on startup.

For your project you should probably not ship with either the Galaxy database or the install database and create those on startup.

**Comment by mvdbeek** [comment] 2020-05-19 15:54
OK, so 20.05 (with or without #9491) and 20.01 fail if you use create_db.py and you don't set an external install database
```
migrate.versioning.repository DEBUG 2020-05-19 17:42:09,104 [p:79173,w:0,m:0] [MainThread] Config: {'db_settings': {'repository_id': 'Galaxy', 'version_table': 'migrate_version', 'required_dbs': '[]'}}
galaxy.model.migrate.check INFO 2020-05-19 17:42:09,189 [p:79173,w:0,m:0] [MainThread] At database version 165
galaxy.config INFO 2020-05-19 17:42:09,190 [p:79173,w:0,m:0] [MainThread] Install database targetting Galaxy's database configuration.
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: tool_shed_repository

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 48, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 100, in __init__
    self._configure_datatypes_registry(self.installed_repository_manager)
  File "lib/galaxy/config/__init__.py", line 1079, in _configure_datatypes_registry
    installed_repository_manager.load_proprietary_datatypes()
  File "lib/galaxy/tool_shed/galaxy_install/installed_repository_manager.py", line 653, in load_proprietary_datatypes
    for tool_shed_repository in self.context.query(self.install_model.ToolShedRepository) \
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tool_shed_repository
[SQL: SELECT tool_shed_repository.id AS tool_shed_repository_id, tool_shed_repository.create_time AS tool_shed_repository_create_time, tool_shed_repository.update_time AS tool_shed_repository_update_time, tool_shed_repository.tool_shed AS tool_shed_repository_tool_shed, tool_shed_repository.name AS tool_shed_repository_name, tool_shed_repository.description AS tool_shed_repository_description, tool_shed_repository.owner AS tool_shed_repository_owner, tool_shed_repository.installed_changeset_revision AS tool_shed_repository_installed_changeset_revision, tool_shed_repository.changeset_revision AS tool_shed_repository_changeset_revision, tool_shed_repository.ctx_rev AS tool_shed_repository_ctx_rev, tool_shed_repository.metadata AS tool_shed_repository_metadata, tool_shed_repository.includes_datatypes AS tool_shed_repository_includes_datatypes, tool_shed_repository.tool_shed_status AS tool_shed_repository_tool_shed_status, tool_shed_repository.deleted AS tool_shed_repository_deleted, tool_shed_repository.uninstalled AS tool_shed_repository_uninstalled, tool_shed_repository.dist_to_shed AS tool_shed_repository_dist_to_shed, tool_shed_repository.status AS tool_shed_repository_status, tool_shed_repository.error_message AS tool_shed_repository_error_message
FROM tool_shed_repository
WHERE tool_shed_repository.includes_datatypes = 1 AND tool_shed_repository.deleted = 0 ORDER BY tool_shed_repository.id]
(Background on this error at: http://sqlalche.me/e/e3q8)
```
And all of 19.09, 20.01 and 20.05 versions of create_db.py do not create the install database. At this point I don't understand how your setup works. You must have a install database on 20.01, but where is it being created ?

**Comment by mvdbeek** [comment] 2020-05-19 15:57
When you say you revert https://github.com/galaxyproject/galaxy/pull/9491, is that just reverting 39ac5dbd7a439bd62f2ff7fec65a1db5c5f05089, or do you build against another branch ?

**Comment by AndreasSko** [comment] 2020-05-19 16:02
Hm, strange.. Could using Postgres make a difference? After running the Dockerfile I already got a working DB, I don't think that my Galaxy container does much more (expect running `manage_db.sh upgrade`).

**Comment by AndreasSko** [comment] 2020-05-19 16:02
With revert I mean this: https://github.com/AndreasSko/galaxy/commit/69dde0a56f2e0a8bed2a5857fcd5cf990c9674c6

**Comment by mvdbeek** [comment] 2020-05-19 16:10
> Could using Postgres make a difference

Very unlikely

https://github.com/AndreasSko/docker-galaxy-stable/runs/655793033?check_suite_focus=true#step:6:2120 doesn't show any signs of the install database migrations either.

**Comment by mvdbeek** [comment] 2020-05-19 16:24
> With revert I mean this: [AndreasSko@69dde0a](https://github.com/AndreasSko/galaxy/commit/69dde0a56f2e0a8bed2a5857fcd5cf990c9674c6)
> I use my fork currently for the setup.

Is there a build for this somewhere ?

**Comment by AndreasSko** [comment] 2020-05-19 16:53
> https://github.com/AndreasSko/docker-galaxy-stable/runs/655793033?check_suite_focus=true#step:6:2120 doesn't show any signs of the install database migrations either.

Lines 1180 to 2120 are the ones that were missing in 20.05 for me.


> Is there a build for this somewhere ?

You could try to build https://github.com/AndreasSko/docker-galaxy-stable/tree/247287dc325378593a6c0ca8b840048216754963/compose-v2/galaxy-postgres locally (with the `python3` branch).

with my fork:
`docker build galaxy-postgres -t andreassko/galaxy-postgres --build-arg GALAXY_REPO=https://github.com/andreassko/galaxy`

and without:
`docker build galaxy-postgres -t andreassko/galaxy-postgres`


> > Could using Postgres make a difference
> 
> Very unlikely

I'm not sure, but SQLite and Postgres could actually make a difference (try to remove the `-c /galaxy...` in [Line 24](https://github.com/AndreasSko/docker-galaxy-stable/blob/247287dc325378593a6c0ca8b840048216754963/compose-v2/galaxy-postgres/Dockerfile#L24))

**Comment by mvdbeek** [comment] 2020-05-20 08:10
> Lines 1180 to 2120 are the ones that were missing in 20.05 for me.

I've been saying this since the opening post, this is 100% expected and how it is supposed to be. What you're missing is the install database that stores installed repositories. There's no sign of this anywhere in your build logs, old or new.

What I can say is this: Don't do the dump/restore cycle, just let Galaxy handle the database creation if necessary.

**Comment by mvdbeek** [comment] 2020-05-20 08:19
> I'm not sure, but SQLite and Postgres could actually make a difference (try to remove the `-c /galaxy...` in [Line 24](https://github.com/AndreasSko/docker-galaxy-stable/blob/247287dc325378593a6c0ca8b840048216754963/compose-v2/galaxy-postgres/Dockerfile#L24))

If you don't add `-c <config_file>` the the sample file in `lib/galaxy/config/sample` will be used, which creates a sqlite database in database/universe.sqlite.

**Comment by abretaud** [comment] 2020-06-23 10:15
@mvdbeek we have the same problem in https://github.com/bgruening/docker-galaxy-stable: create_db.sh is called at build time, but the install tables are missing => the container fails to start.
Your patch at https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:fix_9787?expand=1 works fine, any chance to get it merged in 20.05?

**Comment by mvdbeek** [comment] 2020-06-23 14:54
I would prefer if we don't do that. You can just skip create_db.sh entirely. This is not needed anymore.

**Comment by abretaud** [comment] 2020-06-23 15:36
Ok I disabled it in the dockerfile, I thought it would make startup slower the first time, but it looks like it's not the case
Thanks!

**Comment by maikknebel** [comment] 2020-07-06 07:42
I have a same problem, installing a fresh galaxy 20.05 with ansible results in the same error messages on startup as stated in the initial message above. I manally deleted the whole database and started galaxy by hand, now the error is gone and all tables are there.

**Comment by mvdbeek** [comment] 2020-07-06 07:56
This should be fixed in ansible.

**Closed as completed by mvdbeek** 2020-07-06 07:56 UTC

**Comment by mvdbeek** [comment] 2020-07-06 07:59
Should be fixed in https://github.com/galaxyproject/ansible-galaxy/pull/112
