### ISSUE TITLE
Workflows do not allow selection of reference genomes

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1881] opened 2016-03-07 15:00 UTC
Workflows do not work for tools with this parameter type:

```
<param name="reference_genome" type="select" label="Using reference genome">
    <options from_data_table="twobit">
        <filter type="data_meta" key="dbkey" ref="input" column="0"/>
    </options>
    <validator type="no_options" message="A built-in reference genome is not available for the build associated with the selected input file"/>
 </param>
```

Specifically, this tool: https://toolshed.g2.bx.psu.edu/view/iuc/extract_genomic_dna/9af3f57e50b9

When attempting to run the workflow:

![workflow_run_bug](https://cloud.githubusercontent.com/assets/6947053/13572954/0593080c-e44b-11e5-97de-daef7b87c388.png)

Attempting to change the reference genome does not allow for a different selection.  It produces an empty select list.

![ref_genome_select_bug](https://cloud.githubusercontent.com/assets/6947053/13572976/22df27f6-e44b-11e5-98ca-ea8e599d614b.png)

Here is an example workflow that produces this error:

![simple_workflow](https://cloud.githubusercontent.com/assets/6947053/13573008/55ebd52c-e44b-11e5-8593-9fe06770e792.png)

This bug exists in the dev branch and goes back to 15.10.  Please port the fix back to 15.10.  Thanks!

**Comment by mvdbeek** [comment] 2016-03-07 15:11
Just to make sure, you do have entries in the twobit table, right?

**Comment by gregvonkuster** [comment] 2016-03-07 15:26
Yes, I do have entries in the two-bit table.  They were generated by first running the "Create DBKey and Reference Genome" Data Manager tool to add entries into the "All fasta" data table, which can then be leveraged when running the TwoBit Data Manager tool.

**Comment by mvdbeek** [comment] 2016-03-07 15:47
Hmm, I think the underlying problem could be this filter here:
https://github.com/galaxyproject/tools-iuc/blob/master/tools/extract_genomic_dna/extract_genomic_dna.xml#L57

Does it work if you have a compatible input data file in the history?

**Comment by gregvonkuster** [comment] 2016-03-07 15:58
Yes:

![extract](https://cloud.githubusercontent.com/assets/6947053/13574709/52182376-e453-11e5-908c-78e8b6351363.png)

The two-bit table looks like this:
...
sacCer3 ~/galaxy/tool-data/sacCer3/seq/sacCer3.2bit
mm9 ~galaxy-pugh/galaxy/tool-data/mm9/seq/mm9.2bit
hg19    ~/galaxy-pugh/galaxy/tool-data/hg19/seq/hg19.2bit
...

**Comment by mvdbeek** [comment] 2016-03-07 16:08
~~okay, yes, I see similar, but also buggy behaviour on our production 16.01 instance:
It seems that conditional options can't be set to "specify at runtime" in the workflow editor.~~
Edit: That's not a bug, rather a missing feature.

Though if I do set the reference genome selection inside the conditional to "specify at runtime", I can choose the genome (but only the genome that the input file corresponds to).
If I select `history` in the worfkflow editor, I can't change this to `locally_chached` at runtime...

**Comment by gregvonkuster** [comment] 2016-03-07 16:13
Yes, it will be nice to get these issues fixed.  The only work-around I've found is to edit the workflow and set the genome you want to use, save it, and then run it.  Not very useful.

**Comment by mvdbeek** [comment] 2016-03-07 16:17
So inside the workflow editor, you can't click on specify at runtime?
<img width="269" alt="screen shot 2016-03-07 at 17 26 58" src="https://cloud.githubusercontent.com/assets/6804901/13575284/6e7aa4d2-e488-11e5-9f06-55897292edff.png">
This works for me (though your procedure should clearly work)

**Comment by gregvonkuster** [comment] 2016-03-07 16:27
Yes, I can, but then when I try to set it int the Run view, I get an empty select list.  Do you see something different?  I'm seeing this on the dev branch, and for me it goes back to 15.10.

<img width="306" alt="rmpty" src="https://cloud.githubusercontent.com/assets/6947053/13575551/7924f896-e457-11e5-99ba-cd80ef671a89.png">

**Comment by mvdbeek** [comment] 2016-03-07 16:34
Hmm, yes that seems to work ...
<img width="1341" alt="screen shot 2016-03-07 at 17 42 07" src="https://cloud.githubusercontent.com/assets/6804901/13575731/9d1f7112-e48a-11e5-9eb6-c3f7d7c84191.png">
Though this is on a slightly outdated release_16.01.
I'm setting up my dev instance with the extract_genomic_dna tool now.

**Comment by guerler** [comment] 2016-09-15 17:52
This has been fixed with the new run workflow form in dev.

**Closed as completed by guerler** 2016-09-15 17:52 UTC
