### ISSUE TITLE
Workflows list API return wrong `Total_matches`

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#17165] opened 2023-12-11 16:00 UTC
The `/api/workflows` is returning wrong number for all matched workflows with the query (contained duplicate items)
ref: #16607 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `23.1`

**To Reproduce**
1. Go to 'Workflows' from masthead
2. Open the browser Developer Tools (or just call the API directly)
3. In the response headers section, the `Total_matches` is not correct

**Expected behavior**
Return the correct number of the total matched items

**Comment by mvdbeek** [comment] 2023-12-11 16:02
Can you please include a minimal reproducible example or some instructions to follow ?

**Comment by itisAliRH** [comment] 2023-12-11 16:09
> Can you please include a minimal reproducible example or some instructions to follow ?

@mvdbeek I have 33 workflows in my account in the EU instance. The `Total_matches` in the workflows list API response is 59 and for the first page, the result is only 12 items, for the second page 10 items and for the last page returns 11, but the limit is set to 20.

**Comment by mvdbeek** [comment] 2023-12-11 16:10
it would be immensely helpful if you can provide an example of how to get into that state because it works correctly for me.

**Comment by mvdbeek** [comment] 2023-12-11 16:18
It's not that I don't believe you, there's just not much I can do in terms of fixing if I don't know how to reproduce this.

**Comment by mvdbeek** [comment] 2023-12-11 16:19
Also your screenshots don't reveal a problem. Total-matches is the number of total matches, and doesn't override your pagination params.

**Comment by davelopez** [comment] 2023-12-11 16:32
I have just tested it too, I have 8 workflows in total but the total matches say I have 10:

![image](https://github.com/galaxyproject/galaxy/assets/46503462/8a116293-7150-46b7-908c-dd98b903fbe8)


If I search for the letter "c", then it says I have 14 total matches:

![image](https://github.com/galaxyproject/galaxy/assets/46503462/e8cbe6d3-bd47-4947-9418-1d9ed0b268c5)

**Comment by davelopez** [comment] 2023-12-11 17:14
Maybe this `unique` is filtering out something that the `get_count` at line 249 is not?

https://github.com/galaxyproject/galaxy/blob/33acf3f2f7c6390fa7076749b0d66d5dedf6a498/lib/galaxy/managers/workflows.py#L265

**Comment by davelopez** [comment] 2023-12-12 12:48
I will try :+1:

**Comment by davelopez** [comment] 2023-12-14 10:11
Should be fixed in #17176

**Closed as completed by davelopez** 2023-12-14 10:11 UTC
