### ISSUE TITLE
history list icons not clickable when only one history

### ISSUE THREAD

**Issue by lawrence14701-zz** [galaxyproject/galaxy#9701] opened 2020-05-02 16:50 UTC
### **Bug with one history in the list-items**
I noticed a UI bug during testing in the history/view URL. The user is unable to click/hover on icons
 when the history remains collapsed and there is **one history in the list-items**. However, the user is able to interact with the icons when the history item expands as shown in the example below. 

![the_problem2](https://user-images.githubusercontent.com/55111579/80870142-9c05af00-8c72-11ea-8532-3cd4f507e48f.gif)

### **What it looks like with more than one history item**
The problem does not occur when there is **more** than one history item.  
![normal](https://user-images.githubusercontent.com/55111579/80869272-8772e800-8c6d-11ea-9354-f3018d3639a5.gif)

### **Potential bug fix**
Adding the following code to /style/scss/list-item.scss file fixes the issue but also increases the size of the history list items. 
```
  .primary-actions {
        height: 58px;
    }
```
![solution](https://user-images.githubusercontent.com/55111579/80869276-8b066f00-8c6d-11ea-969b-41f93012538d.gif)

**Comment by gbbio** [comment] 2020-05-15 07:32
Also runned into this =)

**Comment by davelopez** [comment] 2021-03-18 15:43
Almost a year later... 😅 I can't reproduce this in the latest version, so I will assume this is now fixed. Thank you for reporting! 

I will close it now but feel free to reopen it if needed.

**Closed as completed by davelopez** 2021-03-18 15:43 UTC
Labels: kind/bug, javascript, paper-cut
