### ISSUE TITLE
Batch operation loading stuck in History panel when adding or removing tags

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#18056] opened 2024-04-25 13:57 UTC
Batch operation loading stuck in History panel:

https://github.com/galaxyproject/galaxy/assets/8046843/f461195f-5c62-4cdb-ab8e-e9b78f6ca4a4

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Go to `Current History`
2. Select few datasets
3. Run an operation with selected items (like adding a tag)
4. See the loading stuck in the datasets list until refreshing the page

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davelopez** [comment] 2024-04-25 14:01
This might be a regression, the factor that makes the `Processing operation` look like is spinning forever is that there is no update_time change triggered in the current history for some reason.

**Comment by itisAliRH** [comment] 2024-04-29 09:21
@davelopez It only happens on the `Add tags` and `Remove tags` operations because changing tags does not change the history `update_time` (for all histories).
I think we should do nothing after these operations like `Build dataset pair` operation etc.

**Comment by itisAliRH** [comment] 2024-04-29 09:34
History pulling is not getting the tag updates until searching or opening a collection.

**Comment by davelopez** [comment] 2024-04-29 09:41
> History pulling is not getting the tag updates until searching or opening a collection.

That is because of the same reason, if the history `update_time` doesn't change after the operation, the history watcher doesn't know it needs to get new updates. I'll investigate why it is not getting triggered now.

**Comment by davelopez** [comment] 2024-05-03 09:59
Should be fixed in https://github.com/galaxyproject/galaxy/pull/18068

**Closed as completed by davelopez** 2024-05-03 09:59 UTC
Labels: kind/bug, area/client, area/backend
