### ISSUE TITLE
Importing shared history issue with multiple entry points

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#15608] opened 2023-02-16 23:16 UTC
**Describe the bug**
All three seem related, the example for 2 below seems to reveal what is going on (incorrect target history ID?)
1. **"copy"** Sharing a History shows up in the other account but doesn't always import (via "copy") but can be reviewed (view).
2. **"Import this History case 1"** Importing from the "view" above or from admin functions (bug reports) results in double popup windows. First is for _your current history_ and the second is for the actual history being imported. 
3. **"Import this History case 2"** Import via a share link is fine IF logged into an account. If anon, the pop-up is correct but nothing happens.

**Galaxy Version and/or server at which you observed the bug**
Usegalaxy.org at Galaxy version 23.0.rc1, commit [15ffadeae9988830f891c637a57b65a7ec48c2af](https://github.com/galaxyproject/galaxy/commit/15ffadeae9988830f891c637a57b65a7ec48c2af)

**To Reproduce**

EDIT Martin: I've extracted the first issue below to https://github.com/galaxyproject/galaxy/issues/15627
<details>
**"copy"** Share a history with another account, then attempt to import it via "copy"
1. Go to "Histories shared with me"
2. Click on the menu for a history in that listing
3. Choose "copy"
4. Screen blinks once, then nothing happens. That history does not become the active history and there is no new history added to the User -> History listing.
</details>

**"Import this History case 1"**  Share a history with another account, then attempt to import it via "view" -> "import"
1. Go to "Histories shared with me"
2. Click on the menu for a history in that listing
3. Choose "view"
4. Click on the "import" button at the top of the page
5. First pop-up is for the existing active history (!). Can cancel, or proceed to get a copy.
6. Second pop-up (hidden underneath) is for the actual history import, and only useable after the first is cleared.

**"Import this History case 2"** 
1. Go to a web browser that is not logged into UseGalaxy.org
2. Paste in a shared URL (any) or can use this one https://usegalaxy.org/u/jen/h/test-listpaired-convert-dataype
3. Compare with this shared URL https://usegalaxy.eu/u/jenj/h/test-gtn-vgpworkflowtraining (EU will "remember" who last logged in (browser cache?) and show that in the side view, but use that import function anyway. After imported you are in an anonymous session).

**Expected behavior** (pre 23.0 behavior)
1. **"copy"** imports a history that becomes the active history 
4. **"Import this History case 1"** imports the target history with a single pop-up (via admin functions or histories-shared-with-me)
5. **"Import this History case 2"** (URL share link) imports a copy of that history into an account OR an anonymous session. Maybe add another orange reminder banner about "log into an account or create one" or it will be lost.
 
**Screenshots**
1. **"copy" -**

<img width="1169" alt="23 0_import_no-popup-expected_screen-refreshed-but-no-change" src="https://user-images.githubusercontent.com/8999735/219507382-c61ba518-9d0e-4de0-a4fa-be18e50aecda.png">

2. **"Import this History case 1"**
<img width="334" alt="23 0_import_function-appears-in-several-views" src="https://user-images.githubusercontent.com/8999735/219503189-19ee1f9c-a423-4da1-8d76-456cd95e0683.png">

<img width="1424" alt="23 0_import_pop-up_1_incorrect-extra" src="https://user-images.githubusercontent.com/8999735/219503220-e8025ef3-4f9e-4cfd-9c4a-bb1142d99d67.png">

<img width="1430" alt="23 0_import_pop-up_2_correct" src="https://user-images.githubusercontent.com/8999735/219503254-69e1c5f8-9565-423d-bb54-b495305ac852.png">

3. **"Import this History case 2"**  (URL share link not signed into an account)

<img width="1184" alt="23 0_import_pop-up_makes-me-think-I-can-view-in-anon-session_but-never-loads" src="https://user-images.githubusercontent.com/8999735/219506501-ad7dde94-c04f-47ef-b2cf-5e95eabf4f5c.png">

**Additional context**
The "copy" problem is not 100% a fail. May take several tests to see a pattern but can't find a definitive pattern eg server1 versus server2 or admin/non-admin account combinations. All definitely new in 23.0.

**Comment by davelopez** [comment] 2023-02-20 13:19
I think these are 3 different issues:
1. This seems to be broken around #14638, I'm not sure how to properly fix this since the copy dialog is now on Vue but this grid is still Backbone and Backbone gives me the chills. Maybe another folk from the UI/UX team can fix this easily?
2. This should be fixed in https://github.com/galaxyproject/galaxy/pull/15619
3. I may not have understood the problem correctly, but I cannot reproduce this in 23.0 locally. I tried, as an anonymous user (incognito mode), to import a History from a link and the imported history replaced the default history successfully.
  ![anonymous_import_history](https://user-images.githubusercontent.com/46503462/220119595-5a5199d6-96fd-47c4-8dee-8e3de7d939e8.gif)

**Comment by jennaj** [comment] 2023-02-20 17:29
Thanks @davelopez -- I retested the third one. I'm working on UseGalaxy.org with a Mac running OS Monterey 12.6.1 and Safari. Maybe the issue only shows up on the public site?

https://user-images.githubusercontent.com/8999735/220169915-04a47c8f-bbd7-43b7-b576-a5a0ab92891a.mov

**Comment by davelopez** [comment] 2023-02-21 08:41
Thanks! I think I understand now better the last issue from your video.
What happens if you go to the "Home" after the import? Is the new imported history not there? (This is what I understood as the issue)
Or are you expecting to be automatically redirected to the "Home" after the import?

**Comment by jennaj** [comment] 2023-02-21 22:09
> What happens if you go to the "Home" after the import? Is the new imported history not there? (This is what I understood as the issue)

"Home" goes to the history in an anon account. But not sure someone who had a share link would understand what to do at that point. Example: clicking on a link in a publication

> Or are you expecting to be automatically redirected to the "Home" after the import?

Yes, this is what I was expecting. I think it is much more clearer about what is going on, and making it as easy as possible for someone new to get started is important. 
----
The landing page from a shared history is slightly different. If that was on purpose (moving the import button?), maybe that is where this was introduced? The extra details are also super useful, in particular the size of the history (will this blow up my account or not, etc)

**22.05 at EU**
<img width="1119" alt="Screen Shot 2023-02-21 at 2 02 09 PM" src="https://user-images.githubusercontent.com/8999735/220468857-86a090e8-b1b1-49d4-a22d-3319515bd200.png">

**23.1 at ORG**
<img width="1115" alt="Screen Shot 2023-02-21 at 2 01 56 PM" src="https://user-images.githubusercontent.com/8999735/220468873-d6caa8db-be08-4737-8c8b-a4d06eaf28ec.png">

**Comment by jennaj** [comment] 2023-03-02 22:38
Update:

I'm not getting a double-popup for the history import anymore, but after I do import a shared history it "appears" to be the active history but really isn't. 

How to reproduce:
1. Import a history into Galaxy while logged in
2. Click "rerun" for any of the jobs
3. Tool form loads up, but the input datasets will be chosen from whatever history was originally the "active" history (or, show up as non available)
4. Use the Switch-to-history function or User -> Histories and notice that the newly imported history is not the active history

**Comment by mvdbeek** [comment] 2023-03-03 10:14
> * Tool form loads up, but the input datasets will be chosen from whatever history was originally the "active" history (or, show up as non available)

That's how it has to work, right ? Otherwise it's not a rerun.

item 4 though does seem buggy.

**Comment by jennaj** [comment] 2023-03-09 19:39
> That's how it has to work, right ? Otherwise it's not a rerun.
> item 4 though does seem buggy.

Sorry, this was difficult to explain, will try again: The rerun form is brought up correctly but none of the original inputs are available because that imported history is not actually active (despite loading into the right history panel). Using the history refresh doesn't swap the history. Reloading the entire webpage will bring up the correct active history (whatever was active before the import).

That is how I found item 4.

**Comment by ahmedhamidawan** [comment] 2023-04-13 18:21
> Update:
> 
> I'm not getting a double-popup for the history import anymore, but after I do import a shared history it "appears" to be the active history but really isn't.
> 
> How to reproduce:
> 
> 1. Import a history into Galaxy while logged in
> 2. Click "rerun" for any of the jobs
> 3. Tool form loads up, but the input datasets will be chosen from whatever history was originally the "active" history (or, show up as non available)
> 4. Use the Switch-to-history function or User -> Histories and notice that the newly imported history is not the active history

@jennaj This has been fixed in https://github.com/galaxyproject/galaxy/pull/15923#:~:text=Importing%20a%20new%20history%20doesn%27t%20potentially%20set%20it%20as%20current%20history%20on%20server

**Comment by davelopez** [comment] 2023-07-04 08:53
I think all those issues are fixed now, if not please open a new issue :)

**Closed as completed by davelopez** 2023-07-04 08:53 UTC
Labels: area/UI-UX
