### ISSUE TITLE
loading tool panel takes 1-2s

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#17825] opened 2024-03-23 16:23 UTC
If you open the tool panel, especially from the Activity bar, it takes 1-2 seconds until something happens. This is slower on EU, but also noticeable on ORG. I assume it has something to do with the number of tools installed?

I think it would be nice to remember the tool panel already and load the tools async without blocking the interface for a few seconds.

**Comment by jdavcs** [comment] 2024-03-25 14:32
I'm de-milestoning it, otherwise we'll treat it as a blocker for 24.0, which, I think, it shouldn't be (despite it being an important performance issue, of course).

**Comment by nuwang** [comment] 2024-03-25 14:40
@cat-bro noticed that the performance impact seems pretty significant: https://stats.usegalaxy.org.au/d/NZUyY1oMz/selenium-tests?orgId=1&from=now-7d&to=now&viewPanel=3

Assuming galaxy-eu deployed 24.0 on the 24th, you can see a visible spike in average home page load times, tool search times etc.

**Comment by bgruening** [comment] 2024-03-25 14:44
Cool graph! Thanks @nuwang and @cat-bro ...

**Comment by mvdbeek** [comment] 2024-03-25 15:17
> I think it would be nice to remember the tool panel already and load the tools async without blocking the interface for a few seconds.

That's how it works after the initial mount. There's no extra request being made to `/api/tools?in_panel=false`, this is only done when first mounting the tool panel component. If you observe a slowness it'd be helpful if you can describe what you did to observe this, and if you can open the network console and check what requests are being made.

The speed of `/api/tools?in_panel=false` (only looking at the server response timing) is faster on usegalaxy.org for more tools than usegalaxy.org.au that is still on 23.1. So I don't think this is a regression and therefor I don't think it's a release blocker.

The selenium timings are interesting, but they are very indirect measures of speed. It clearly doesn't take 55 seconds to load usegalaxy.org, there's a bunch of timed requests form the center panel that might be messing with the stats for "finished". Discarding all cache the load event is reached after 2 seconds, which is reasonable for a cold start. With cache this is 1 second, which again is not too bad.

**Comment by wm75** [comment] 2024-03-25 15:22
so waht's very obvious on .eu is that the tool panel takes a sizeable amount of time *each* time you try to show it from the activity bar.

**Comment by wm75** [comment] 2024-03-25 15:25
right now the delay is a bit less than what it was over the weekend, but still noticeable. Yesterday it was long enough to always make me hit the tools button twice because I thought it hadn't triggered.

**Comment by nuwang** [comment] 2024-03-25 15:33
@mvdbeek Something does indeed appear to be off with the home page loading measurements, but the other seems fairly representative?

For ref, main stats are here, when did it switch to 24.0?:  https://stats.usegalaxy.org.au/d/NZUyY1oMz/selenium-tests?orgId=1&from=now-7d&to=now

The page timing code is here: https://github.com/usegalaxy-au/page_performance_timer/blob/9e96722ce04070c715b4e04c787535fe746d1be6/page_perf_timer.py#L134

**Comment by mvdbeek** [comment] 2024-03-25 15:47
About 2 weeks ago. We do have much finer-grained stats in sentry, we can for instance look at average request duration, which didn't change much with the upgrade, but did make a big reduction on friday when we tweaked the database server settings:

<img width="661" alt="Screenshot 2024-03-25 at 16 44 55" src="https://github.com/galaxyproject/galaxy/assets/6804901/0d31e420-e6d8-4da8-8edc-6918c13c12ed">

**Comment by itisAliRH** [comment] 2024-03-26 09:30
I have discovered the root cause of the issue. When attempting to open the tool from the activity bar, the `ToolSearch` component is fetching [this](https://usegalaxy.eu/static/dist/libs.bundled.js) (that takes around 10 seconds for the first load and 2-3 seconds after) each time, and it is [registering a worker](https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Panels/Common/ToolSearch.vue#L122). When the component is closed, this forces the client build to not cache it.

**Comment by dannon** [comment] 2024-03-26 11:20
@itisAliRH I saw that yesterday but wasn't sure if it was what folks were talking about.  For me, on usegalaxy.eu, it's maybe ~300ms until paint of the tool panel when clicking from workflow invocations back to tools.  And the libs should always be precached, but the worker context should take time to load them.  In your network log, can you verify they're being pulled from cache?

All that said, we should definitely refactor this and 1) move the initial loading of the tool search worker out of mounted, to have it loaded a single time and reused (instead of full initialization in mounted()), and 2) see if we can strip down the worker such that it doesn't need libs -- it may be the lodash usage there causing the bundle use.

**Comment by ahmedhamidawan** [comment] 2024-03-26 15:42
![image](https://github.com/galaxyproject/galaxy/assets/78516064/bb5e5f6a-d36d-4ffb-821b-a324282223a0)

This change is also a fix for this, but yes keeping the worker in the store and only loaded once is more appropriate. I am working on that

**Comment by mvdbeek** [comment] 2024-03-26 15:44
`v-show` sounds good, do you have an idea of the performance impact this would have ?

**Comment by ahmedhamidawan** [comment] 2024-03-26 15:49
Investigating this but the only problem here could be is that we would end up loading all histories for the multiview panel, notifications for the notifications one, and so on for any other panel on load up

**Comment by mvdbeek** [comment] 2024-03-26 15:58
Ah, yeah, that is less than optimal. We could just do it for the tool panel if the worker stuff turns out to be complicated ?

**Comment by ahmedhamidawan** [comment] 2024-03-26 16:47
After some investigation, I've discovered that this computed ref is the main culprit:
https://github.com/ahmedhamidawan/galaxy/blob/dev/client/src/components/Panels/ToolBox.vue#L90-L100

It's taking so long to `getValidToolsInCurrentView`. Commenting that out makes this lightning quick, the worker is not to blame at all infact

**Comment by mvdbeek** [comment] 2024-03-26 17:09
If JS is anything like python turning https://github.com/mvdbeek/galaxy/blob/635274266804be7e9fcade5b6a9eff7f9729c50b/client/src/components/Panels/utilities.ts#L167 into an object or set or anything with fast lookup might help

**Comment by mvdbeek** [comment] 2024-03-26 18:08
How did you find this ? 

If I proxy the dev client against usegalaxy.org I see this in the flamegraph:
<img width="833" alt="Screenshot 2024-03-26 at 18 38 42" src="https://github.com/galaxyproject/galaxy/assets/6804901/51f25753-462e-40b0-9560-53ac104af8fa">
It seems to be relatively minor (9ms), compared to the blue anonymous function (70ms) which corresponds to 

https://github.com/galaxyproject/galaxy/blob/635274266804be7e9fcade5b6a9eff7f9729c50b/client/src/components/Panels/ToolBox.vue#L301-L307

which ... does look like it involves more reactive gets than necessary (see the 2 get / get_value below the anonymous function). I'm sure there's a reason we're doing it, but
```
commit a8152a7402fd28c4de0b14884b2145be3fa8e231
Author: mvdbeek <m.vandenbeek@gmail.com>
Date:   Tue Mar 26 19:03:12 2024 +0100

    Improve panel speed

diff --git a/client/src/components/Panels/ToolBox.vue b/client/src/components/Panels/ToolBox.vue
index 29698f105a..939903b549 100644
--- a/client/src/components/Panels/ToolBox.vue
+++ b/client/src/components/Panels/ToolBox.vue
@@ -135,8 +135,6 @@ const localPanel: ComputedRef<Record<string, Tool | ToolSectionType> | null> = c
     }
 });
 
-const sectionIds = computed(() => Object.keys(localPanel.value || {}));
-
 const favWorkflows = computed(() => {
     const Galaxy = getGalaxyInstance();
     const storedWorkflowMenuEntries = Galaxy && Galaxy.config.stored_workflow_menu_entries;
@@ -298,10 +296,10 @@ function setButtonText() {
                         :query-filter="queryFilter || undefined"
                         :disable-filter="true"
                         @onClick="onToolClick" />
-                    <div v-for="(sectionId, key) in sectionIds" :key="key">
+                    <div v-for="(panel, key) in localPanel" :key="key">
                         <ToolSection
-                            v-if="localPanel[sectionId]"
-                            :category="localPanel[sectionId] || {}"
+                            v-if="panel"
+                            :category="panel || {}"
                             :query-filter="queryFilter || undefined"
                             @onClick="onToolClick" />
                     </div>

```

reduces the click handling to 70ms, which feels very fast.

**Comment by mvdbeek** [comment] 2024-03-26 18:21
On usegalaxy.eu the patch brings it from 300ms to 120ms, with `getValidToolsInCurrentView` and `getValidToolsInEachSection ` each at around 25ms.

**Comment by ahmedhamidawan** [comment] 2024-03-26 18:56
Yes, that does improve it! Maybe I can try out a couple of other things to make it even faster

**Comment by mvdbeek** [comment] 2024-04-05 13:25
Should be fixed in https://github.com/galaxyproject/galaxy/pull/17847

**Closed as completed by mvdbeek** 2024-04-05 13:25 UTC
Labels: kind/bug, area/UI-UX
