### ISSUE TITLE
Importation of workflow with subworkflow

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#5411] opened 2018-01-30 08:44 UTC
Hi,

If I create and export a workflow calling a subworkflow in one Galaxy instance, I can import it on a different Galaxy instance without error (at the importation). 
But when I want to run it, I got:

![screen shot 2018-01-30 at 09 39 15](https://user-images.githubusercontent.com/1842467/35556125-b3d27d34-05a1-11e8-823b-4f6f89aed117.png)

(even if I have a workflow corresponding to the subworkflow with the same name)

I have this issue in both the Freiburg instance and an instance from a Docker image based on 17.09
Any idea?

Bérénice

**Comment by mvdbeek** [comment] 2018-01-30 09:22
If you want to get this to work now you need to transfer both workflows, and the included nested workflow needs to be at the latest version, since we can only download the latest version of a workflow for now.

Ideally you'd get all included workflows when you transfer a subworkflow.

**Comment by bebatut** [comment] 2018-01-30 09:29
Even if I transfer both workflows, I still have the same issue

**Comment by mvdbeek** [comment] 2018-01-30 09:33
That used to work, but it is indeed broken now.

**Comment by mvdbeek** [comment] 2019-01-21 09:04
I think this should be much better now that https://github.com/galaxyproject/galaxy/pull/7227 is merged, at the time this may have been caused by missing or not exact tools. If this is still an issue please re-open with a link to a subworkflow that is problematic. (Also workflow exports now contain the subworkflow, so just downloading the parent workflow should be enough)

**Closed as completed by mvdbeek** 2019-01-21 09:04 UTC
Labels: kind/bug, area/workflows/subworkflows
