### ISSUE TITLE
Workflow link has a shadow icon depending on zoom

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#15645] opened 2023-02-24 08:12 UTC
**Describe the bug**
When I edit a workflow with a zoom which is not 100% I get a "shadow icon that appears" when I want to link outputs to inputs.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org
{"version_major":"23.0","version_minor":"rc1"}

**Expected behavior**
I expect a single green round to link tools

**Screenshots**
![Peek 2023-02-24 09-07](https://user-images.githubusercontent.com/30404086/221126344-a65337f9-8d7b-4f66-9d98-9577e9df3141.gif)

**Additional context**
```
[ldelisle@SV-49-002 ~]$ firefox --version
Mozilla Firefox 110.0
[ldelisle@SV-49-002 ~]$ uname -a
Linux SV-49-002 6.1.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Feb 2023 20:06:08 +0000 x86_64 GNU/Linux
```

**Comment by davelopez** [comment] 2023-02-24 08:57
Thank you @lldelisle! I will close this as it is a duplicate of #15512

**Closed as completed by davelopez** 2023-02-24 08:57 UTC

**Comment by lldelisle** [comment] 2023-02-24 08:59
Sorry I forgot to check

**Comment by davelopez** [comment] 2023-02-24 09:03
No worries!
