### ISSUE TITLE
Bug with running MultiQC on collections

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#5040] opened 2017-11-20 09:39 UTC
Hi, 

If I try to run MultiQC on collection, this error is generated:

![screenshot from 2017-11-20 10-20-05](https://user-images.githubusercontent.com/1842467/33011037-f576ee8e-cddc-11e7-9c27-7377562650f0.png)
And then if I click on "Multiple datasets", a new "dataset" (which seems to correspond to my collection and is "unavailable") is "created"

![screenshot from 2017-11-20 10-22-45](https://user-images.githubusercontent.com/1842467/33011142-508594ec-cddd-11e7-88d3-a02173ff7ce9.png)

Is it a bug because of the `repeat` in the [wrapper](https://github.com/galaxyproject/tools-iuc/blob/master/tools/multiqc/multiqc.xml)?

```
<when value="fastqc">
      <repeat name="output" title="FastQC output" min="1">
            <param name="type" type="select" label="Type of FastQC output?">
                  <option value="data">Raw data</option>
                  <option value="theoretical_gc">Theorectical GC</option>
            </param>
            <param name="input" type="data" format="txt" multiple="true" label="FastQC output"/>
      </repeat>
</when>
```

More info here: 
- https://sentry.denbi.uni-freiburg.de/share/issue/322e34383739/
- https://sentry.denbi.uni-freiburg.de/share/issue/322e33373235/

Any idea @jmchilton @guerler ?

Thanks

Bérénice

**Comment by bebatut** [comment] 2017-11-20 10:30
And I have a similar bug, when I try to run MultiQC on datasets (from a collection, which have been unhided) with a tag:

![screenshot from 2017-11-20 11-27-03](https://user-images.githubusercontent.com/1842467/33013925-e7fb7438-cde5-11e7-96a1-92993cafb2b4.png)

The error does not appear if I do not select the datasets with tag (from the same collection)

**Comment by nsoranzo** [comment] 2017-11-20 10:44
This looks like a duplicate of https://github.com/galaxyproject/galaxy/issues/4975 , which has been fixed already. Is the Freiburg server updated to the latest commit of the 17.09 branch?

**Comment by martenson** [comment] 2018-11-05 16:18
This should be resolved, details in the dup linked above.

**Closed as completed by martenson** 2018-11-05 16:18 UTC
