### ISSUE TITLE
[24.1] Long history name while importing history

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18285] opened 2024-05-31 13:19 UTC
**Describe the bug**
When I import a history and the name is long, it goes beyond the frame.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.rc1 ([test.galaxyproject.org](http://test.galaxyproject.org/))

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to Public Histories
2. Click on a long name history and click on view
3. Click on Import this history
4. See the bug

**Expected behavior**
It should fit within the frame.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/2973722/39e53dea-2325-49e1-8d27-b40a13bb0a4b)

**Comment by davelopez** [comment] 2024-05-31 13:49
Hmmm this seems to be caused by the fact that the name is a "single-word" and the overflow breaks only on words in the Boostrapvue Modal title default. 

![image](https://github.com/galaxyproject/galaxy/assets/46503462/39e23d18-cd9f-4294-95ca-7b14f1bca7f4)

I guess if this is important we can use the title slot to personalize the title a use explicitly `word-break: break-all;` there.

**Comment by ElectronicBlueberry** [comment] 2024-06-03 09:20
Is there any modal where we wouldn't want a `word-break: break-all;` in the title?
Otherwise we could try overwriting the titles CSS instead of using a slot, fixing this for all our modals.

**Comment by itisAliRH** [comment] 2024-06-03 15:05
I fixed it for all modal titles. But this issue is happening in more places which need to be fixed:

### History Rename
![image](https://github.com/galaxyproject/galaxy/assets/8046843/1e11a139-5f2a-4826-b255-25b84ec1b2fc)

### History Grid
![image](https://github.com/galaxyproject/galaxy/assets/8046843/3b46bf3f-d656-4d8f-9b93-00b417ab4abe)

### History Sharing (title and link)
![image](https://github.com/galaxyproject/galaxy/assets/8046843/9fa9d840-a42f-43f6-9687-9784adc9d147)

Would the fixes in the same PR be preferable, or in a follow-up?

**Comment by mvdbeek** [comment] 2024-06-03 15:39
Up to you, I don't think this is very controversial, so if you want to add commits in the same PR that's fine.

**Comment by mvdbeek** [comment] 2024-06-14 16:37
I think that's all fixed in https://github.com/galaxyproject/galaxy/pull/18306 ?

**Closed as completed by mvdbeek** 2024-06-14 16:37 UTC
Labels: kind/bug, area/UI-UX
