### ISSUE TITLE
History - "For all selected" doesn't work across pages

### ISSUE THREAD

**Issue by blankclemens** [galaxyproject/galaxy#4350] opened 2017-07-27 15:28 UTC
When working with histories containing more than one page, the `For all selected...` button only takes the elements from the visible page.

This is for example necessary for `Build List of Dataset Pairs` or `Build Dataset List` if the elements of interest are not on the same page by chance (or are just too many for one page).

I couldn't find a workaround as a user (e.g. deactivating pages) - since it removes the functionality to build these collections, I consider this quite important.

**Comment by nekrut** [comment] 2017-07-27 15:35
This is a major issue!

**Comment by mvdbeek** [comment] 2017-07-27 15:59
That's a duplicate of https://github.com/galaxyproject/galaxy/issues/3911. Or at least they're linked.

**Comment by blankclemens** [comment] 2017-07-27 16:17
Indeed it is, my bad, was focused to much on "For all selected" to find this issue.

**Comment by mvdbeek** [comment] 2017-07-27 16:31
> I couldn't find a workaround as a user (e.g. deactivating pages) - since it removes the functionality to build these collections, I consider this quite important.

One workaround is to create 2 collections, and then you should be able to merge them. Less than ideal, but if you do need to do this a lot right now it may help

**Comment by blankclemens** [comment] 2017-07-28 10:15
@mvdbeek Thanks, I didn't know that I can merge collections. But to use this, I still need to have my pairs on one page - e.g. having a page with 500 forward reads and a page with 500 reverse reads wont be solvable through this, or am I missing something?

Another workaround: Upload all files again (which might take hours cause of #4347 and #1090) and use the history directly afterwards to create the collections, since the pages haven't been generated yet. Just don't reload the page until you're finished! ;)

While it makes sense to close duplicates, shouldn't we at least merge the labels to the remaining open issue, since this is quite major?

**Comment by mvdbeek** [comment] 2017-07-28 10:24
> @mvdbeek Thanks, I didn't know that I can merge collections. But to use this, I still need to have my pairs on one page - e.g. having a page with 500 forward reads and a page with 500 reverse reeds wont be solvable through this, or am I missing something?

Yes, you're right. In principle you could use the Zip Collection tool to merge forward and reverse, but that is getting a bit more complicated ...

I'm inclined to close the other one, since there is more information in here.

**Comment by mvdbeek** [comment] 2017-07-28 10:29
@dannon you assigned yourself to #3911, do you want to take on this issue ?

**Comment by dannon** [comment] 2017-08-07 14:30
@mvdbeek I will eventually, but I'm happy for anyone else interested to pick it up and run with it.  I've been out of action having a kid and stuff, and probably won't get to this in the very near future.

Pending a more comprehensive selector dialog solution, the easiest fix that popped into my mind last time I looked at this was to just to have a button on the history to 'load it all' spanning pagination.   There are definitely performance concerns to look into and test with *very* large histories, but that was going to be my first stab at it.

**Comment by mvdbeek** [comment] 2017-08-07 14:51
Thanks @dannon, I totally get that, hope all is well! 
I'll add this to the 17.09 milestone, and we'll see if someone picks it up :).

**Comment by blankenberg** [comment] 2017-09-22 20:52
Bumping into this as well...

**Comment by dannon** [comment] 2021-01-28 14:44
This is on the Q1 UI-UX roadmap to be addressed in the new history.

**Comment by dannon** [comment] 2022-05-12 16:16
This is resolved with the new history and bulk operations.

**Closed as completed by dannon** 2022-05-12 16:16 UTC
Labels: kind/bug, area/UI-UX, area/dataset-collections
