### ISSUE TITLE
NGS: RNA-seq: gffread > errors when loading tool form at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#999] opened 2015-10-28 17:40 UTC
Click on the tool to see error: 

<img width="337" alt="screen shot 2015-10-28 at 10 39 57 am" src="https://cloud.githubusercontent.com/assets/8999735/10797517/43fdd02e-7d60-11e5-8792-252c887b22d6.png">

**Comment by martenson** [comment] 2015-10-30 01:41
also happens on test; the exception in the log is:

```
==> /srv/galaxy/test/log/uwsgi.log <==
galaxy.web.framework.decorators ERROR 2015-10-29 20:40:16,159 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 258, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 97, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "lib/galaxy/tools/__init__.py", line 2391, in to_json
    populate_state(trans, self.inputs, state_inputs, state_errors, params.__dict__)
  File "lib/galaxy/tools/__init__.py", line 2267, in populate_state
    state[input.name] = input.get_initial_value(trans, context, history=history)
  File "lib/galaxy/tools/parameters/grouping.py", line 620, in get_initial_value
    current_case = self.get_current_case( test_value, trans )
  File "lib/galaxy/tools/parameters/grouping.py", line 569, in get_current_case
    raise ValueError( "No case matched value:", self.name, str_value )
ValueError: ('No case matched value:', 'gffs', None)
```

**Comment by jennaj** [comment] 2015-11-16 18:02
Duplicate? https://github.com/galaxyproject/galaxy/issues/980

**Comment by martenson** [comment] 2016-01-18 16:02
yes @jennaj , this is a duplicate of #980
closing

**Closed as completed by martenson** 2016-01-18 16:02 UTC
Labels: kind/bug, area/API, triage
