### ISSUE TITLE
Download files in a list of datasets with the name from the list

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2023] opened 2016-03-28 17:47 UTC
Idea:

Download files in a list of datasets with the name from the list (Samplexyz.bam) as output instead of the name given by galaxy (Galaxy5-[Filter_SAM_or_BAM,_output_SAM_or_BAM_on_data_181__bam]).

Submitted by:

markus.ball via https://biostar.usegalaxy.org/p/16676/

**Comment by lparsons** [comment] 2016-05-17 14:55
This is basically a duplicate of #2140 and related to #2346.

My general suggestion would be name the files according to the element identifiers in the collection. However, when downloading, prefix the names with the name of the collection to provide context. This would be made even better if one could easily rename the collection in a workflow.

**Comment by jmchilton** [comment] 2016-09-30 15:09
Okay - so currently the naming for downloaded datasets from the history panel when coming in through a collection is:

`<GalaxyDatasetHID>-[<name>].<extension>`

But it would be more usable if it was:

`<GalaxyDatasetCollectionName>-[<element_identifier>].<extension>`?

What about the HID of the collection - should that be included? (Currently the HID of the dataset is included - which is useless and really problematic that it even has an HID - see https://github.com/galaxyproject/galaxy/issues/1810).

**Comment by lparsons** [comment] 2016-09-30 15:13
At the moment, I'm voting for `<GalaxyDatasetCollectionName>-[<element_identifier>].<extension>`. Thanks @jmchilton.

**Comment by stevecassidy** [comment] 2017-02-02 02:46
Just wanted to comment on this. An important use case for us would be for the user to upload a collection of files, run some processing pipeline on them and download the result. We can preserve the element_identifier between processing steps, but then they can't download the resulting dataset. If they could, the filenames would have a useless (for us) prefix named for the dataset collection .  Better would be to download this as a zip file with a directory structure, the directory could be the dataset name but the individual data files would be <element_identifier>.<extension>.  

Perhaps the addition of the prefix could be optional in a download dialogue?

**Comment by jmchilton** [comment] 2017-04-27 13:27
@stevecassidy Indeed - this would be great. Thanks for the input!

**Comment by jmchilton** [comment] 2017-04-27 13:48
Closing as a duplicate of #2140. Opened an issue based on @stevecassidy's comment above with #3984.

**Closed as completed by jmchilton** 2017-04-27 13:48 UTC
Labels: kind/enhancement, friendliness/intermediate, area/dataset-collections
