### ISSUE TITLE
Deleting a collection doesn't stop scheduling of unscheduled jobs

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#16563] opened 2023-08-16 16:42 UTC
I wrote about this in the matrix dev channel at the end of last year and forgot about it, but bumped into it again just now and thought it was worth an issue.

> Hi, I launched 1000 jobs (using a collection) and later deleted the collection, this should stop scheduling of unscheduled jobs right?
Because I see in logs that they are still being scheduled 😣
This is 22.01 fwiw
Nicola Soranzo
I don't think that never worked properly for me either, had to hack in the database to mark the invocation as scheduled or something.
M BerntM
Had a similar problem recently .. but with an additional implicit conversion .. then its basically impossible for users to even delete the generated datasets (or jobs)

**Comment by mvdbeek** [comment] 2023-08-17 08:04
Duplicate of https://github.com/galaxyproject/galaxy/issues/10442. It's hard since we can't just grab a lock or check at every step that inputs or outputs aren't deleted, and it's easy to run into race conditions, see https://github.com/galaxyproject/galaxy/pull/16252

**Closed as completed by mvdbeek** 2023-08-17 08:04 UTC
