### ISSUE TITLE
Tool install_dependencies endpoint times out

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9038] opened 2019-11-26 19:54 UTC
The `/api/tools/{tool id}/install_dependencies` api endpoint times out when installing a tool because it is waiting for conda to finish. It would be better if it immediately returned with the installation status so it can be polled and tools like Ephemeris don't always return exceptions.

**Comment by nsoranzo** [comment] 2020-06-19 21:45
Duplicate of https://github.com/galaxyproject/galaxy/issues/6254

**Closed as completed by nsoranzo** 2020-06-19 21:45 UTC
