### ISSUE TITLE
Column numbers of tabular files not displayed II

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#14666] opened 2022-09-21 13:32 UTC
Hi, 

since quite a while the header with the column numbers of tabular files are not displayed anymore in the central pane (EU and main Galaxy). The column headers are quite important for me to work with larger tabular files and I hope there is interest in the community to bring them back. 

More information and screenshots can be found in previous issues about the same bug: 
https://github.com/galaxyproject/galaxy/issues/11644 and https://github.com/galaxyproject/galaxy/issues/11443

Thank you,
Melanie

**Comment by dannon** [comment] 2022-09-21 13:36
This is likely fixed with https://github.com/galaxyproject/galaxy/pull/14396.

I'm working on a followup to that fixing VCF header parsing (while still including the comment lines), but I think your core issue is resolved.

**Comment by mvdbeek** [comment] 2022-09-21 13:41
I think there's still something wrong beyond that:
<img width="439" alt="Screenshot 2022-09-21 at 15 39 39" src="https://user-images.githubusercontent.com/6804901/191519305-ea447aad-e9ac-4e9c-b5fb-cf2009456add.png">

That's a plain tabular file, so shouldn't be related to VCF header parsing.

**Comment by dannon** [comment] 2022-09-21 13:42
@mvdbeek Is that EU you're testing against?  The code I refer to is not in 22.05.

**Comment by dannon** [comment] 2022-09-27 15:40
I did follow up with the vcf-specific work I mentioned in https://github.com/galaxyproject/galaxy/pull/14671, and have confirmed again that the headers are displaying (due to the original csv parser fix in https://github.com/galaxyproject/galaxy/pull/14396) so I'm closing this one out.

Since it's a dependency change (and there was already the extra vcf issue) I hadn't planned on backporting this, but folks can let me know if we really want to.

**Closed as completed by dannon** 2022-09-27 15:40 UTC
Labels: kind/bug
