### ISSUE TITLE
Download collection broken fails with "file incomplete"

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15390] opened 2023-01-24 20:44 UTC
**Describe the bug**
I tried to download a small list collection, and the download immediately errors with `Failed - file incomplete`.

**To Reproduce**
Try to download a list collection on Galaxy 23.0

**Comment by davelopez** [comment] 2023-01-25 16:59
Might be a deployment issue? It works on a local Galaxy.

**Comment by mvdbeek** [comment] 2023-01-25 17:16
Yep, definitely. I think nginx-mod-zip is at fault here.

**Comment by natefoo** [comment] 2023-02-01 17:09
Did this just break after the upgrade? I haven't changed the nginx config for this in quite some time.

**Comment by davelopez** [comment] 2023-02-17 08:39
Anything I can do to help here? or can someone with access to usegalaxy.org logs and config have a closer look? Please feel free to reassign the issue.

**Comment by mvdbeek** [comment] 2023-02-17 08:58
I don't think this is related to the new release, no. I can't tell for how long it's been broken though.

**Comment by mvdbeek** [comment] 2023-10-13 14:48
We may give mod-zip another try, any chance @jmchilton or @neoformit could dig out a nice test case ?

**Comment by mvdbeek** [comment] 2023-10-13 14:48
(since it didn't happen with every collection)

**Comment by neoformit** [comment] 2023-10-17 00:57
I just failed to recreate this on usegalaxy.org with the same history I reported this against back in release testing. Looks like it works fine now?

**Comment by jdavcs** [comment] 2024-03-01 19:31
Closing this since it can't be reproduced. Feel free to reopen if this resurfaces.

**Closed as completed by jdavcs** 2024-03-01 19:31 UTC
Labels: kind/bug
