### ISSUE TITLE
LDAP: setting (some) options not working

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4153] opened 2017-06-06 12:32 UTC
It seems that currently setting LDAP options is not working. When I uncomment `<ldap-options>OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_ALLOW</ldap-options>` in auth_conf.xml I get an ValueError. 

I can reproduce the error in the python ldap module that is installed in the galaxy virtual environment:

```
. .venv/bin/activate
python 
import ldap
ldap.set_option( ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW )
```

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs1/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/site-packages/ldap/functions.py", line 137, in set_option
    return _ldap_function_call(None,_ldap.set_option,option,invalue)
  File "/gpfs1/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/site-packages/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
ValueError: option error
```

I have tested this for galaxy_17.05 and 17.01 with the same result. Both have ldap.__version__ = '2.4.27'. When I test it with my local python installation (ldap.__version__ = '2.4.22') the test works. So I guess that the problem is the underlying ldap library (_ldap.so ?). 

Some options seem to work: e.g. ldap.set_option(ldap.OPT_REFERRALS, 0)

Unencrypted LDAP authentication is working fine since no options are required, but now my admins asked me to switch to a secure connection. Would be great if somebody has a solution or workaround.

**Comment by nsoranzo** [comment] 2017-06-06 13:42
Duplicate of #3178.

Solution would be to fix https://github.com/galaxyproject/starforge/issues/130.

**Closed as completed by nsoranzo** 2017-06-06 13:42 UTC
