### ISSUE TITLE
Hide password change option if using external auth

### ISSUE THREAD

**Issue by tjansse5** [galaxyproject/galaxy#3880] opened 2017-04-05 14:53 UTC
If Galaxy is configured to use external authentication it shouldn't be possible to change the password in Galaxy. Therefore the password reset link on the login page and the password change option in the user preferences should be hidden for external authentication.

**Comment by nsoranzo** [comment] 2017-04-05 15:18
Duplicate of #3747.

**Closed as completed by nsoranzo** 2017-04-05 15:18 UTC
