### ISSUE TITLE
Option to expose command line and job metrics

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3252] opened 2016-12-01 17:59 UTC
1. Log into a Galaxy as a non-administrator, e.g. https://usegalaxy.org
2. Click on the "i" (view details) icon of a tool output
3. You get lots of information in first block of entries, from Name to UUID.
4. Log into your Galaxy as an administrator
5. Click on the "i" (view details) icon of a tool output
6. You get lots of extra information after the UUID:

 - Full Path
 - Job Command-Line
 - Job Runtime (Wall Clock)
 - Cores Allocated
 - Job Start Time
 - Job End Time

There is an option in ``config/galaxy.ini`` to allow non-admins to see the full path:

```
# This option allows users to see the full path of datasets via the "View
# Details" option in the history.  Administrators can always see this.
#expose_dataset_path = False
```

This is implemented in ``templates/show_params.mako`` here:

https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/templates/show_params.mako#L169

```
        %if trans.user_is_admin() or trans.app.config.expose_dataset_path:
            <tr><td>Full Path:</td><td>${hda.file_name | h}</td></tr>
        %endif
        %if job and job.command_line and trans.user_is_admin():
            <tr><td>Job Command-Line:</td><td>${ job.command_line | h }</td></tr>
        %endif
        %if job and trans.user_is_admin():
            <% job_metrics = trans.app.job_metrics %>
            %for metric in job.metrics:
                <% metric_title, metric_value = job_metrics.format( metric.plugin, metric.metric_name, metric.metric_value ) %>
                <tr><td>${ metric_title | h }</td><td>${ metric_value | h }</td></tr>
            %endfor
        %endif
```

Original commit https://github.com/galaxyproject/galaxy/commit/68c9d80fe8b5d3aeb5dc47d78a377a0c5dab1863 by @dannon

I would like two extra options, something like ``expose_job_command_line`` and ``expose_job_metrics``, to make these fields available to non-admins.

There is a security concern as the command line will reveal the dataset paths, but if you are using ``expose_dataset_path=True`` then showing the command line too would help some of your power users (e.g. debugging why a job failed, or how it differs from a similar job run by hand at the command line).

I see little downside to exposing the job metrics, and this has the upside of helping users review jobs later (e.g. if left to run overnight they can't really know how long/slow/expensive each step was).

See also https://github.com/galaxyproject/galaxy/commit/95baa6950ebd6bf3ba917f90d41978ebc294e431 by @jmchilton which added the metric report.

(I'm happy to attempt a pull request if this is likely to be accepted)

**Comment by nsoranzo** [comment] 2016-12-01 18:04
Kind-of duplicate of #2954.

**Closed as completed** 2016-12-22 15:40 UTC
