### ISSUE TITLE
Tool showing older version by Default

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#15599] opened 2023-02-16 16:59 UTC
**Describe the bug**

When clicking on a scanpy tool form it will usually default to a previous version. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0

**To Reproduce**
1. Go to Use Galaxy
2. Click on scanpyread10x
3. Look at the version number

**Expected behavior**
The tool should default to the most recent version of the tool.

**Screenshots**
![image](https://user-images.githubusercontent.com/62220253/219435001-0c4675e8-c814-42cf-8af5-716d08e17998.png)
![image](https://user-images.githubusercontent.com/62220253/219435112-aba639c1-479a-433a-a3bf-bea0b4de30a8.png)

**Comment by nsoranzo** [comment] 2023-02-16 17:03
Duplicate of https://github.com/galaxyproject/galaxy/issues/15580

**Closed as completed by nsoranzo** 2023-02-16 17:03 UTC
