### ISSUE TITLE
Admin "Impersonate a user" search box should allow for search by username

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#6525] opened 2018-07-22 13:48 UTC
Currently only allows for search by email address.

**Comment by mvdbeek** [comment] 2018-07-22 15:58
I've changed the title, while you can call this a usability issue and it is a missing feature it is clearly not a bug.

**Comment by nsoranzo** [comment] 2018-11-30 16:20
Fixed by https://github.com/galaxyproject/galaxy/pull/6176 .

**Closed as completed by nsoranzo** 2018-11-30 16:20 UTC
Labels: feature-request, area/admin
