### ISSUE TITLE
include allowed datatypes in tool form at all times

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17005] opened 2023-11-09 19:47 UTC
It would be helpful to users to always understand what are the datatypes an input field allows even if you have some suitable datasets in the current history. E.g. on he screenshot below, if I have `fastq` dataset I will not know that a `bam` dataset is also supported.

![Screenshot 2023-11-09 at 11 44 59 AM](https://github.com/galaxyproject/galaxy/assets/1814954/7581f61b-f261-4073-8823-5ba9fc79594e)

**Comment by bernt-matthias** [comment] 2023-11-09 23:10
Duplicate of https://github.com/galaxyproject/galaxy/issues/9218

**Closed as not planned** 2023-11-09 23:14 UTC
Labels: kind/enhancement, area/UI-UX
