### ISSUE TITLE
Scratchbook and Saved Visualizations

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#6862] opened 2018-10-12 10:15 UTC
If you activate the scratchbook and click on `Visualize -> Saved Visualizations ` it opens as a scratchbook and not in the main view. The only question is: Is this a bug or a feature?

![screenshot from 2018-10-12 12-10-33](https://user-images.githubusercontent.com/13435136/46863624-36e03380-ce18-11e8-8d16-f98516521d62.png)

**Comment by martenson** [comment] 2018-10-12 15:15
@joachimwolff what version of Galaxy? I cannot reproduce in 18.09 or dev

**Comment by martenson** [comment] 2018-10-12 15:16
I checked the url you shared, that is 18.05 atm. Given it has already been fixed and not really critical I am closing this issue. Thanks for reporting it though.

**Comment by joachimwolff** [comment] 2018-10-12 15:16
@erasche You know this way better than I do.

**Closed as completed by martenson** 2018-10-12 15:16 UTC
