### ISSUE TITLE
LDAP auth broken

### ISSUE THREAD

**Issue by ppouchin** [galaxyproject/galaxy#9178] opened 2020-01-06 15:28 UTC
On Debian Buster, LDAP authentication now leads to an error message on the server:
`RuntimeError: ('Failed to load LDAP module: %s', '/opt/galaxy-server/.venv/local/lib/python2.7/site-packages/.libs_ldap/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference')`

**Comment by nsoranzo** [comment] 2020-01-06 15:35
@ppouchin Can please you provide:
- information about your operating system (e.g. distribution and version)
- version of Galaxy you are using (e.g. output of `git show`)
- version of installed python-ldap (e.g. output of `pip list|grep ldap` from within Galaxy's virtualenv)

**Comment by ppouchin** [comment] 2020-01-06 15:39
Yes sorry. I realized I was a bit too quick to create the issue and was gathering this information. 

- OS: Debian Buster
- Galaxy version: release_19.09
- python-ldap: 2.4.44

**Comment by ppouchin** [comment] 2020-01-06 15:43
Ok. My bad.
So, at first, I had Galaxy re-create the virtual environment, which installed python-ldap 2.4.44, but if I upgrade it manually to the latest version (3.2.0), it works.

**Comment by ppouchin** [comment] 2020-01-06 15:54
I guess the problem lies in this file: https://github.com/galaxyproject/galaxy/blob/39ee8c64b6462f1f9c1c319d47182468f0490ccf/lib/galaxy/dependencies/conditional-requirements.txt#L13

**Comment by nsoranzo** [comment] 2020-01-06 16:22
The problem is with the python-ldap wheel hosted on https://wheels.galaxyproject.org/ and is due to https://github.com/pypa/auditwheel/issues/80 .
You can work around it with `pip install --force-reinstall --no-binary python-ldap python-ldap==2.4.44`

**Comment by ppouchin** [comment] 2020-01-07 10:09
Ok. Thanks. That worked.

**Comment by ppouchin** [comment] 2020-01-29 22:08
I recently upgraded our .venv to Python3 and got other problems with LDAP. 
When logging in, I kept getting this error:

> Traceback (most recent call last):
>   File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
>     rval = func(self, trans, *args, **kwargs)
>   File "lib/galaxy/webapps/galaxy/controllers/user.py", line 120, in login
>     return self.__validate_login(trans, payload, **kwd)
>   File "lib/galaxy/webapps/galaxy/controllers/user.py", line 154, in __validate_login
>     elif not trans.app.auth_manager.check_password(user, password):
>   File "lib/galaxy/auth/__init__.py", line 84, in check_password
>     auth_result = provider.authenticate_user(user, password, options)
>   File "lib/galaxy/auth/providers/ldap_ad.py", line 249, in authenticate_user
>     return self.authenticate(user.email, user.username, password, options)[0]
>   File "lib/galaxy/auth/providers/ldap_ad.py", line 213, in authenticate
>     _get_subs(options, 'auto-register-email', params),
>   File "lib/galaxy/auth/providers/ldap_ad.py", line 25, in _get_subs
>     return str(d[k]).format(**params)
> KeyError: 'mail'

When I replaced
```
<auto-register-username>{uid}</auto-register-username>
<auto-register-email>{mail}</auto-register-email>
```
by
```
<auto-register-username>{username}</auto-register-username>
<auto-register-email>{email}</auto-register-email>
```
it worked once again... which I find weird.

Did I miss something?

**Comment by bernt-matthias** [comment] 2020-01-30 17:39
Same workaround worked for me. But no new users can login at our Galaxy. @ppouchin do you observe the same bahavior?

In the logs I see `mail: none, auto-register with username: xxxxx` I guess the problem in none in the mail? 

This is quite urgent for me, I could start debugging it, but for this I would need a method to remove a user entirely from the data base (because I do not have the possibility to create users at our LDAP). Is there an possibility to do this?

**Comment by bernt-matthias** [comment] 2020-01-30 17:40
If I got @nsoranzo correctly this might be a python2/3 (together with the use of different module versions)...?

**Comment by ppouchin** [comment] 2020-01-30 17:42
> Same workaround worked for me. But no new users can login at our Galaxy. @ppouchin do you observe the same bahavior?

Yes, I had not noticed yet, but I do have the same issue.

**Comment by nsoranzo** [comment] 2020-01-31 01:22
Indeed I started looking at this some days ago but got distracted. Can you please test the fixes in #9290 ?

**Comment by bernt-matthias** [comment] 2020-01-31 01:34
Guess I can test tomorrow

**Comment by ppouchin** [comment] 2020-01-31 09:50
It works for me apparently.

**Comment by bernt-matthias** [comment] 2020-01-31 14:58
Fixed by https://github.com/galaxyproject/galaxy/pull/9290

**Closed as completed by bernt-matthias** 2020-01-31 14:58 UTC
Labels: kind/bug, area/auth, area/python3
