### ISSUE TITLE
Tool burst submission fails on 16.01 release

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#2259] opened 2016-04-27 18:30 UTC
Attempted to use tool burst submission parameters from galaxy.ini on a multiple paralleled workflow. First stage worked correctly but got  the following stacktrace when attempting stage two.

https://gist.github.com/Takadonet/080ca51143cefee4a15268b54598b749

commit : b79474083b08860923f7f28fc1e7442b53f925db

galaxy.ini
tool_submission_burst_threads = 4
tool_submission_burst_at = 30

Using supervisord for headless handlers.

**Comment by dannon** [comment] 2016-05-03 22:20
Hopefully resolved with #2260 

Please let us know if you still see this after that change.

**Comment by jmchilton** [comment] 2016-05-03 22:25
I think he said it still isn't working - but sounds like we made some progress. I'm looking into the next problem now - I'll see if I can reproduce locally.

**Comment by dannon** [comment] 2016-05-03 23:06
Yeah, reopening this, because I'm pretty sure the change in #2260 won't fix the problem above.

**Comment by Takadonet** [comment] 2016-05-04 02:19
#2260 patch does fix the issue but still was not able to successfully run a  full workflow.  What is happening now is that downstream tools are not waiting for their inputs to be 'ok' state but simple starting right after being created. In my case, freebayes and mpileup jobs will immediate run even before their smalt map  job is done. http://imgur.com/tgkbj6n

**Comment by mvdbeek** [comment] 2020-08-04 14:02
We've removed the broken burst scheduling quite some time ago, closing this then.

**Closed as completed by mvdbeek** 2020-08-04 14:02 UTC
