### ISSUE TITLE
Workflow run form reloads with history state changes

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#18546] opened 2024-07-15 14:47 UTC
**Describe the bug**
The workflow run form keeps reloading (I think triggered by state changes in the current history because I don't see it happening with histories without queued jobs) and forgets about previous parameter changes or whether it was in expanded mode before

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org and usegalaxy.eu

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Switch to a history with an ongoing analysis and some expected dataset state changes
2. Click on the run button of any WF
3. Expand the WF run form to full form and/or reconfigure some input params
4. Watch your changes getting reverted after a while

**Expected behavior**
Only dataset inputs should potentially offer new select options, but the rest of the form state should be preserved.

**Comment by ElectronicBlueberry** [comment] 2024-07-19 14:01
I failed to reproduce the simple form resetting. Do you have an (preferably minimal) example workflow?

**Comment by wm75** [comment] 2024-07-19 14:15
The workflow shouldn't matter much, but you need a history with an ongoing analysis, not a static one with no dataset state changes.

one second ...

**Comment by wm75** [comment] 2024-07-19 14:24
You can use this history: https://usegalaxy.eu/u/wolfgang-maier/h/issue-18546-test-history

and @Sch-Da 's workflow: https://usegalaxy.eu/u/wolfgang-maier/w/imported-comparing-differences-in-two-english-texts

Launch the WF a first time (which should work without issues, then while it's running try a second time and you should see the reloading occur.

**Comment by ElectronicBlueberry** [comment] 2024-07-19 14:51
Can still not reproduce this with the simple run form. Can you confirm this only happens in the full run form for you as well, or record a video?

**Comment by mvdbeek** [comment] 2024-07-19 14:53
I guess it can't happen for that particular workflow since it has a runtime parameter, and so only the legacy form is available.

**Comment by wm75** [comment] 2024-07-19 14:59
The collapsing of the full form into the simple form *does* happen.

What doesn't get reset are dataset selections.

**Comment by ElectronicBlueberry** [comment] 2024-07-19 15:04
The collapsing of the full form is fixed in #18574
What I cannot reproduce is simple form parameters being reset.

**Comment by wm75** [comment] 2024-07-19 15:10
I thought I had seen that independently of the full form collapsing, but cannot reproduce it on eu currently and on org my scheduled jobs aren't starting.
Will update you here, but maybe only on Monday.

**Comment by wm75** [comment] 2024-07-22 08:36
Ok, cannot reproduce the param resetting on .eu, nor on .org.
Must have been confused, when I first experienced this, by the constant collapsing and probably misremembered where I had entered values (because they get reset, as has always been the case, when switching between simple and full form).

@ElectronicBlueberry thanks for #18574 and sorry for the partially wrong report.

**Comment by ElectronicBlueberry** [comment] 2024-07-22 09:35
Fixed in #18574

Thanks for double checking!

**Closed as completed by ElectronicBlueberry** 2024-07-22 09:35 UTC
Labels: kind/bug, area/UI-UX
