### ISSUE TITLE
Rule-based Upload Manager window disappears

### ISSUE THREAD

**Issue by cumbof** [galaxyproject/galaxy#14154] opened 2022-06-22 16:37 UTC
The Rule-Based window of the Galaxy Upload Manager disappears after clicking the `Build` button, instead of showing up the Build Rules window. It sometimes tries to open the window but only the header comes out, like in the figure posted below:

<img width="1440" alt="Screenshot 2022-06-22 at 11 43 01" src="https://user-images.githubusercontent.com/3764656/175089139-633aeab6-0312-49cb-9f62-3ca479a83b05.png">

The issue emerged while I was testing the [Group tags for complex experimental designs](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/group-tags/tutorial.html) tutorial, `Hands-on: Set group tags during upload` section, up to point 6, on [usegalaxy.org](usegalaxy.org)

It happens on Chrome, but it seems working as expected on Safari.

**Comment by fabio-cumbo** [comment] 2022-06-22 16:48
I have these three errors in the JavaScript Console:

```javascript
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Uncaught (in promise) Error: Request failed with status code 500
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.onloadend (xhr.js?b50d:66:1)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at Function.__webpack_require__ (analysis.bundled.js?v=1655913235:1:13745737)
    at async buildCollectionModal (buildCollectionModal.js?c543:40:1)
    at async HistoryPanelProxy.buildCollection (HistoryPanelProxy.js?b1e2:79:1)
```

**Comment by mvdbeek** [comment] 2022-06-23 08:53
I can't reproduce this, and we had a bunch of intermittent database errors, i would assume that's what's happening here. That said we should display an error.

**Comment by assuntad23** [comment] 2022-06-29 21:13
I just saw this on a local branch @dannon  @mvdbeek 
Same errors in the console.

**Comment by dannon** [comment] 2022-06-29 23:50
Just to update this -- I am betting this is webpack dynamic import going wonky due to a cached application.  When you click "build", we dynamically load the (expensive, large) rule builder component dynamically (https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Collections/RuleBasedCollectionCreatorModal.js#L22), in a request something like thsi:

```
http://localhost:8081/static/dist/vendors-node_modules_handsontable_dist_handsontable_js-node_modules_moment_locale_af_js-node_-a6bf32.bundled.js
```

Note the hash.  That is going to change as the client is rebuilt, and it'd explain missing module stacktrace.  If you have a primary analysis application loaded and the bundles change underneath (as would happen in development watch-mode or the like, without hot reloading -- maybe this is what happened to Assunta), you'd get this error.

**Comment by mvdbeek** [comment] 2022-06-30 08:38
Anything we can do to make this more robust?

**Comment by dannon** [comment] 2022-06-30 10:30
Best future plan I have to avoid this completely is something in the primary client that periodically checks for an updated build, then does a "Your Galaxy client is out of date, please reload" just like other apps (like element) do.

Bottom line though is that if you get half a client build and it changes on you, you've gotta reload.  For right now, we could catch these and at least log it to the console, or pop up a message saying "Your galaxy client build is out of date, please reload".  I'll try to tinker with options.

**Comment by mvdbeek** [comment] 2023-02-14 15:55
I think we can close this ?

**Closed as completed by mvdbeek** 2023-02-14 15:55 UTC
Labels: kind/bug, area/UI-UX

**Comment by dannon** [comment] 2023-02-14 15:57
@mvdbeek Yeah.  It's not related to the rule based manager at all -- it's a wishlist item to eventually have a client say "Hey, new client available, get it!", but it's not a bug nor on the immediate roadmap.
