### ISSUE TITLE
`shared_inputs` is not defined in Galaxy Tool XSD

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3317] opened 2016-12-15 11:26 UTC
Error:
```
Applying linter tool_xsd... FAIL
.. ERROR: Invalid tmp_2JcNZ found. Errors [/tmp/tmp_2JcNZ:3:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_3_2_1: Element 'parallelism', attribute 'shared_inputs': The attribute 'shared_inputs' is not allowed.
```
Implementation:
https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/lib/galaxy/jobs/splitters/multi.py#L25

**Comment by nsoranzo** [comment] 2016-12-15 11:30
Duplicate of #3303.

**Closed as completed by nsoranzo** 2016-12-15 11:30 UTC
Labels: area/documentation
