### ISSUE TITLE
History Pagination seems broken 

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#3337] opened 2016-12-19 16:05 UTC
On commit https://github.com/galaxyproject/galaxy/commit/c1397908cd1fc81b294849008b1e5ec1b1381660  

Attempting to switch to 2nd or 3rd page on a history with 1115 shown datasets. I can see the GET request go thru with
api/histories/fc0c1264f7cdbee0/contents?limit=500&offset=500&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True

However, as soon as I can see the those datasets, the browser immediately request another GET work for the original first page again. No idea why. Using Chrome 55.0.2883.75 on Linux

**Comment by Takadonet** [comment] 2016-12-19 17:42
So looks like it works for some history and redirects on others. Hoping to find the reason why...

**Comment by dannon** [comment] 2016-12-19 17:47
Yeah, I'm having a hard time reproducing this with my quickly generated 'test' large histories.  If you could try to narrow down what is similar in histories where this happens it'd be a huge help.

**Comment by Takadonet** [comment] 2016-12-19 17:51
My assumption so far is that if the history has any non finished state jobs, it will always refresh back to the first page. I can see the auto refresh going and it may be the reason why its keeps going back to the main page.

**Comment by dannon** [comment] 2016-12-19 17:51
Ahh, that's useful info.  I'll try that out here.

**Comment by dannon** [comment] 2016-12-19 18:21
Yeah, I can verify this is due to new datasets and state changes.  I'm going to look into possible fixes, but this is likely more complicated than a quick fix.  We need to notify user of new datasets and state changes, but we certainly don't want it to be this jarring force-refresh back to page1.

**Comment by Takadonet** [comment] 2017-01-17 17:45
FYI:  Current workaround is to open the developer panel and select offline mode till I see the auto update fail and turn networking back on. Once it fails, you can navigate between pages with no fear of auto-refreshing away.

**Comment by dannon** [comment] 2017-01-17 17:47
@Takadonet Yeah, the running callback for refreshing is what's updating the page, so once it fails you're good to go.  I started digging through this logic before the holiday break, but I'm back working on UI stuff now, so hopefully I'll have a fix out soon.

**Comment by Takadonet** [comment] 2017-01-17 17:51
Sounds good. Just wanted to add a note for future searchers.

**Comment by jennaj** [comment] 2017-01-31 21:24
Linking in a recent user report of the problem: https://biostar.usegalaxy.org/p/21431

**Comment by dannon** [comment] 2017-10-30 00:16
This was fixed in #3621 (though feel free to reopen if you're seeing it again)

**Closed as completed by dannon** 2017-10-30 00:16 UTC
Labels: kind/bug, area/UI-UX
