### ISSUE TITLE
Make the current Galaxy version visible to the user

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10937] opened 2020-12-16 17:35 UTC
As a user it is not clear which (major) version of Galaxy is being used. usegalaxy.org for example, includes the version at the bottom of the custom `welcome.html` page but the framework should make this available by default. Perhaps a new Help -> About page that includes some general info about Galaxy as well as the current version, or even just Help -> Version page that displays the version and links to the Github branch/release.

**Comment by nsoranzo** [comment] 2020-12-16 19:17
Such page can just expose the information available via the API endpoint `/api/version`

**Comment by hexylena** [comment] 2020-12-17 09:22
duplicate of https://github.com/galaxyproject/galaxy/issues/3143 (I'll close that one since this has more detail.)

Agreed, it would be nice. Personally I think we need something like every other app's user menu, with your profile name / picture at top right, a drop down menu with information, and then the version displayed there in greyed out text. 

![image](https://user-images.githubusercontent.com/458683/102468201-869e9300-4051-11eb-9c69-62129163404c.png)

**Comment by astrovsky01** [comment] 2020-12-17 18:02
Any opinion on hybridizing the two? A tab on the help menu that lists version and redirects to the release notes?

**Comment by afgane** [comment] 2020-12-17 20:54
Starting with just a accessible version would be a great start, but linking it to the release notes would be even better from my perspective.

**Closed as completed** 2021-01-21 18:39 UTC
Labels: area/UI-UX, paper-cut
