### ISSUE TITLE
Filter by quality not working

### ISSUE THREAD

**Issue by AngelicaLindlof** [galaxyproject/galaxy#9814] opened 2020-05-26 08:49 UTC
I am using Filter by quality tool on FastQ data and it is giving the following error. Have tried two days in a row now, still the same issue.

/galaxy-repl/main/jobdir/028/593/28593634/tool_script.sh: line 41: -q: command not found

**Comment by bernt-matthias** [comment] 2020-05-26 09:42
Hi @AngelicaLindlof. Thanks for the report. Could you open the issue over here: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/fastx_toolkit/fastq_quality_filter 

- Please also include the information on the tool version. 
- If possible the content of the `tool_script.sh` could be helpful.

I'm closing the issue here.

**Comment by mvdbeek** [comment] 2020-05-26 09:44
That's generally useful advice @bernt-matthias. I've tracked this down due to other reports we received -- strings after tokens aren't expanded on 20.05. I'm working on it.

**Comment by AngelicaLindlof** [comment] 2020-05-26 09:53
I'm not sure if this is what you request:

Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/devteam/fastq_quality_filter/cshl_fastq_quality_filter/1.0.2+galaxy0
-- | --
Galaxy Tool Version: | 1.0.2+galaxy0

**Comment by mvdbeek** [comment] 2020-05-26 09:55
Thanks, that's fine. All the necessary information will also be submitted to us if you click on the bug icon on the red dataset. I've reproduced this and will take care of it.

**Comment by AngelicaLindlof** [comment] 2020-05-26 10:54
Unfortunately it never turned red, but became green.

**Closed as completed** 2020-05-26 14:18 UTC
Labels: kind/bug
