### ISSUE TITLE
Download file from usegalaxy.eu history fails with err code 500001

### ISSUE THREAD

**Issue by hrukkudyr** [galaxyproject/galaxy#15757] opened 2023-03-10 08:44 UTC
**Describe the bug**
Working on [this ](https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.html) tutorial which imports two files from Zenodo including [this .ipynb one](https://zenodo.org/record/7075718/files/Trajectories_Instructions.ipynb)
This file should be downloaded then up loaded to a Jupyter Notebook but [fails ](https://usegalaxy.eu/api/datasets/4838ba20a6d867655fe570f3c839290e/display?to_ext=ipynb)
`{"err_msg":"Could not get display data for dataset: _serve_raw() got multiple values for argument 'headers'","err_code":500001} `
Workaround possible by manual means but breaks the GTN Tutorial for non=savvy users.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `{"version_major":"23.0","version_minor":"rc1"}`
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to any history
2. Add data use https://zenodo.org/record/7075718/files/Trajectories_Instructions.ipynb
3. Expand history entry
4. Click download icon
5. Get error

**Expected behavior**
A clear and concise description of what you expected to happen: file should download via browser

**Comment by wm75** [comment] 2023-03-10 08:55
see #15738, which has the fix. Actually, this should only be a display and download issue, but you can use the file in an interactive notebook, can't you?

**Comment by wm75** [comment] 2023-03-10 08:56
duplicate of #15737 and #14759.

**Closed as completed by wm75** 2023-03-10 08:56 UTC

**Comment by hrukkudyr** [comment] 2023-03-10 09:15
> see #15738, which has the fix. Actually, this should only be a display and download issue, but you can use the file in an interactive notebook, can't you?

Manually pulling file from Zenodo and then up to Interactive Notebook works just fine #15738 would be the fix
