### ISSUE TITLE
[release testing] Composite dataset uploads do not start

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14125] opened 2022-06-21 03:34 UTC
**Describe the bug**
Attempting to upload a composite dataset file fails.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**To Reproduce**
1. Go to 'Analysis'
2. Click on 'Upload Data'
3. Select the 'Composite' tab
4. Select a file type and specify individual files5. 
5. Click 'Start'
6. See console error 

**Expected behavior**
Composite uploading should work.

**Comment by guerler** [comment] 2022-06-21 13:56
This happens when I attempt to upload an `affybatch` file: 
<img width="940" alt="image" src="https://user-images.githubusercontent.com/2105447/174817282-3a0ebbf2-15e2-4ee3-82a7-2e0c84ffdfb8.png">

**Comment by dannon** [comment] 2022-06-21 16:24
See debugging screenshot here:

![image](https://user-images.githubusercontent.com/155398/174849628-c4ea5c07-99d7-4c83-8c0c-f8364178b672.png)

**Comment by guerler** [comment] 2022-06-22 01:38
We could test this by adding a tour to https://github.com/galaxyproject/galaxy/tree/dev/config/plugins/tours instead of adding a regular selenium test.

**Comment by jdavcs** [comment] 2022-06-22 16:15
> `elements` doesn't exist, but we should be using `items` it appears. Not sure when this changed.

It changed here: 69ada9989cee3f54623aed518f25d427e9df8cad. The problem is that the structure of pasted data uploaded under the Regular tab is different from pasted data uploaded under the Composite tag. In the former, the first pasted item is `data.targets[0].elements[0]`, but in the latter it's `data.targets[0].items[0].items[0]` (the first items array holding the composite item that holds its parts in its own items array). Fixing...

**Comment by mvdbeek** [comment] 2022-06-29 12:28
Should be fixed by https://github.com/galaxyproject/galaxy/pull/14191

**Closed as completed by mvdbeek** 2022-06-29 12:28 UTC
Labels: kind/bug, area/UI-UX
