### ISSUE TITLE
Edit link after creating workflow from the current history

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15402] opened 2023-01-25 13:17 UTC
**Describe the bug**
The `edit` link of the success alert of creating a workflow from the current history is linked to workflow JSON:
![image](https://user-images.githubusercontent.com/8046843/214572405-73755332-e021-40d8-b6c6-31f0548becbd.png)

**Galaxy Version and/or server at which you observed the bug**
23.0.rc1

**To Reproduce**
1. Click on the arrow down at the top of the current history panel
2. Select `Extract Workflow`
3. Click on `Create Workflow`
4. After the workflow is created successfully, Click on `edit`

**Expected behavior**
Open the workflow editor of the created workflow by clicking on `edit`

**Comment by dannon** [comment] 2023-01-25 13:23
This should be fixed in https://github.com/galaxyproject/galaxy/pull/15384

**Comment by ElectronicBlueberry** [comment] 2023-01-25 13:23
Duplicate of #15367
Potentially fixed in #15384

**Closed as completed** 2023-01-25 13:23 UTC
Labels: kind/bug, area/UI-UX
