### ISSUE TITLE
Datasets of type ipynb cannot be viewed or downloaded

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15737] opened 2023-03-08 12:00 UTC
**Describe the bug**
When trying to view or download .ipynb notebook files the server response is `{"err_msg":"Could not get display data for dataset: _serve_raw() got multiple values for argument 'headers'","err_code":500001}`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Upload any file of datatype ipynb
2. Click on the eye or download icons of the dataset

**Comment by hexylena** [comment] 2023-03-08 12:19
Duplicate of https://github.com/galaxyproject/galaxy/issues/14759, https://github.com/usegalaxy-eu/issues/issues/340 which affects @nomadscientist so I'm sure she'll be happy.

**Closed as completed by hexylena** 2023-03-08 12:19 UTC
Labels: kind/bug
