### ISSUE TITLE
[Bug 16.04+] Auto-conversion does not appear anymore in Tool form Select dropdown

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/galaxy#2704] opened 2016-08-02 22:39 UTC
Hi!

During my workshop, we have seen that the BigWig format does not seen to be filtered properly in the dropdown select of my tool. The Galaxy version is 16.04.
I investigated a bit, and it did not find anything particular in `datatypes_conf.xml(.sample)`.

No logs with errors neither. (`galaxy.datatypes.registry DEBUG 2016-08-02 18:28:47,739 Retrieved datatype module galaxy.datatypes.binary:BigWig from the datatype registry.`)

But the behavior is the same on main. Included a screenshot taken on usegalaxy.org.

<img width="1920" alt="screen shot 2016-08-02 at 6 33 46 pm" src="https://cloud.githubusercontent.com/assets/2152858/17347846/652fde52-58e0-11e6-9fbe-719e393f726a.png">

Let me know if I can help ;).\

**Comment by nsoranzo** [comment] 2016-08-03 10:58
I suppose these are simply all datasets in formats that can be automatically converted in `bigwig` as specified in `config/datatypes_conf.xml.sample` .

**Comment by dannon** [comment] 2016-08-03 15:54
I think nicola is right here and that datatypes which can be implicitly converted (correctly) display in this list.  Feel free to re-open if you think this is a bug @remimarenco

**Comment by remimarenco** [comment] 2016-08-03 16:14
@Thanks for the explanation @nsoranzo and @dannon!

So, if I understand well...If I give a .gff3 as input, on the tool side he will get a .bigwig? That's quite handy...although my users (and me) were a bit confused by this during the workshop. Maybe we can add another hint next to the name in the select box, like `(Conversion)`.

**Comment by nsoranzo** [comment] 2016-08-03 17:13
> So, if I understand well...If I give a .gff3 as input, on the tool side he will get a .bigwig?

Yes, Galaxy will run the converter tool specified in `config/datatypes_conf.xml.sample` and use that as input for your tool.

**Comment by bgruening** [comment] 2016-08-03 17:19
This is actually a regression of the new tool form. The old one has displayed datasets with an implicit conversion as "**(as gff) for bar**" (or similar). The brackets where added - and I think this was very useful.
ping @guerler

**Comment by jgoecks** [comment] 2016-08-04 01:42
I agree with @bgruening: this is a UI bug/regression and this issue should be reopened and addressed.

**Comment by remimarenco** [comment] 2016-08-04 02:00
@dannon and @jgoecks: Github rules do not allow me to re-open the issue as a repo collaborator closed it.

**Comment by dannon** [comment] 2016-08-04 02:03
There ya go, thought you could reopen it :)  Can you update the title to identify the issue a little better, or do you want me to?

**Comment by remimarenco** [comment] 2016-08-04 02:12
Thanks @dannon. Yes [this StackOverflow thread](http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github?answertab=votes#tab-top) clearly states that I can't:

> If you are not a collaborator of a repo, then (in regards to issues):
> [...]
> you cannot re-open your own issues if a repo collaborator closed them

I am (still) not a collaborator of this repo.

I can update the title though, and will do it thanks ;)

**Comment by dannon** [comment] 2016-08-04 02:24
@remimarenco I believed you that you couldn't reopen it, I just didn't realize that was the case.  Good to know.

**Comment by blankenberg** [comment] 2016-08-04 15:27
+1 on adding back an indicator that the dataset is only accessible due to datatype conversion

**Comment by remimarenco** [comment] 2016-08-04 19:19
This is maybe a separate issue, but I wanted to add the conversion is either not possible in Worflows or not detected => We can't connect a `.bigwig` input with a `.<convertible_to_bigwig>` output.

**Comment by dannon** [comment] 2016-08-11 15:31
Fixed in #2734.

**Closed as completed by dannon** 2016-08-11 15:31 UTC
