### ISSUE TITLE
Issue with updating annotation

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#2606] opened 2016-07-12 14:09 UTC
In the workflow editor new workflow annotations do not get displayed after entering them (tested on latest 16.04 and usegalaxy.org).
Reloading the workflow then shows the entered annotation, but this is quite confusing and should be fixed. Curiously, this is working fine when galaxy is served locally through paste without any proxy,
so that may as well be a problem in the uwsgi/nginx configuration (but it's broken at usegalaxy.org as well!)
![screenshot from 2016-07-12 15-31-46](https://cloud.githubusercontent.com/assets/6804901/16769908/e4c5efd6-484a-11e6-9b97-39fe6d1d218a.png)

**Comment by dannon** [comment] 2016-07-18 16:46
This is a duplicate of #2567.

**Closed as completed by dannon** 2016-07-18 16:46 UTC
