### ISSUE TITLE
Export History to File: doesn't deal with list of datasets

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#4517] opened 2017-08-30 08:32 UTC
I'm trying to export histories from one Galaxy to another.

List of datasets are not exported.
I' have tried  with a really simple history, one .len file (not in a list) and 4 small bed files grouped in a list.

Those 4 bed files are not present in the tar.gz created.

The test dataset is here:
[https://usegalaxy.org/u/fredbga/h/export-list-of-datasets](url)

The link for archive:
[https://usegalaxy.org/history/export_archive?id=9da3f9862e28defd](url)

The imported history:
[https://usegalaxy.org/u/fredbga/h/imported-from-archive-export-list-of-datasets](url)

Is this complicated to develop ? May I help ? (really need this I think :) )

**Comment by mvdbeek** [comment] 2017-08-30 08:38
That's a duplicate of https://github.com/galaxyproject/galaxy/issues/4345.

I guess it's a nice project, most of the relevant code is in https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tools/imp_exp

**Closed as completed by mvdbeek** 2017-08-30 08:38 UTC

**Comment by FredericBGA** [comment] 2017-08-30 08:39
ok, missed that.
I will have a look.
