### ISSUE TITLE
Updating tool from toolshed fails to update in memory version

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1515] opened 2016-01-14 21:36 UTC
- Install tool from toolshed into Galaxy.
- Update tool in toolshed without changing version number. (add some help text, tweak cmd line, etc)
- Update installed tool in Galaxy.
- Everything is updated on disk, but the in-memory version of the tool interface isn't updated.

The tool is executed using the old interface, but any new included scripts, etc files are run. Restarting Galaxy will load the correct interface.

This seems to be a recent reversion. Seen on dev galaxy @ f617f739dc3e4d5e60b2060f77ac64894cd29173.
Did not test any other releases.

**Comment by gregvonkuster** [comment] 2016-01-14 21:48
I've seen this behavior as well.

**Comment by jmchilton** [comment] 2016-01-14 21:49
On it.

**Comment by jmchilton** [comment] 2016-01-18 21:02
I believe this has been fixed, please reopen if the problem is not resolved.

**Comment by gregvonkuster** [comment] 2016-02-17 13:16
@jmchilton @blankenberg I'm, still experiencing this in the dev branch, and there was no intermittent period in which I was not experiencing this behavior, so I don't believe the changes that were made corrected the problem.  Dan, are you still seeing this problem?  I cannot reopen this issue since I am not a collaborator on this repository.

**Comment by blankenberg** [comment] 2016-02-17 13:57
I did still see the problem as of a week or two ago on dev. The fix PR was against 16.01, was 16.01 merged into dev since this PR?

**Comment by dannon** [comment] 2016-02-17 14:00
@blankenberg Yes, it had been merged over recently (and I just did so again).

**Comment by blankenberg** [comment] 2016-02-17 14:07
thanks @dannon !

**Comment by blankenberg** [comment] 2016-02-17 14:08
@gregvonkuster do you still see the issue with the latest dev? (no time to test myself right now)

**Comment by gregvonkuster** [comment] 2016-02-17 14:22
Yes, I'm definitely on the dev branch, running the latest commit and I just tested again and am still seeing this issue.

$ git status
On branch dev
Your branch is up-to-date with 'origin/dev'.

**Comment by jmchilton** [comment] 2016-02-17 14:42
I'll try to reproduce and take another shot at fixing it :angry:.

**Closed as completed** 2017-01-30 20:28 UTC
Labels: kind/bug, major, area/tools
