### ISSUE TITLE
Collection Job Status not Updating

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15460] opened 2023-01-31 14:52 UTC
**Describe the bug**
When opening a collection while it's contents are being processed, the status of the datasets is not set to "completed", but stay on "processing" indefinitely. 

**Galaxy Version and/or server at which you observed the bug**
23.0

**To Reproduce**
1. Run a tool on a collection
2. Open the collection in the history while it is running
3. Wait for all jobs to finish (check via progress bar or in new tab)
4. See all jobs still shown as running

**Expected behavior**
The status is updated to completed

**Screenshots**
![image](https://user-images.githubusercontent.com/44241786/215793240-01eef38c-3fbc-4aa7-b261-c301c58cedfe.png)
All of these jobs are completed

**Comment by davelopez** [comment] 2023-01-31 14:57
Duplicate of #15414 I think

**Closed as completed** 2023-01-31 15:01 UTC
Labels: kind/bug
