### ISSUE TITLE
Debugging info is missing with failed job that outputs empty collection because of the failure

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/galaxy#6210] opened 2018-05-23 23:30 UTC
Actually, all info about the above-mentioned failed job is missing. 
Without the functionality that is available to dataset output, we can't check the job detail, read the stdout, stderr, and rerun the job, which is quit inconvenient.

**Comment by bernt-matthias** [comment] 2019-12-09 09:16
Duplicate of https://github.com/galaxyproject/galaxy/issues/6507

**Closed as completed by bernt-matthias** 2019-12-09 09:16 UTC
Labels: kind/bug, area/UI-UX
