### ISSUE TITLE
Dataset tags lost when copying or sharing histories

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/galaxy#1133] opened 2015-11-19 20:38 UTC
One of our users is using dataset tags to manage the datasets in an RNA-seq experiment, and has reported that these tags are lost when making a copy of a history to run different analyses, or when the history is shared with another user so they can run their own.

We're running off the 15.07 branch.

**Comment by GuyReeves** [comment] 2015-11-19 21:25
I just noticed this as well.

**Comment by nsoranzo** [comment] 2015-11-20 10:30
Duplicate of #1135.

**Closed as completed by nsoranzo** 2015-11-20 10:30 UTC
