### ISSUE TITLE
creating new datasets in history inserts them in the middle of it

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#548] opened 2015-08-03 21:03 UTC
As you can see on the following pictures the latest dataset is numbered 310 but if I run fastqc it will create datasets numbered 16 and 17 and after refresh it will put them in the middle of the history.

I also think the history have been imported from @nekrut .

History link: https://usegalaxy.org/u/martenson/h/f4

ping @carlfeberhard 

![screenshot 2015-08-03 16 58 00](https://cloud.githubusercontent.com/assets/1814954/9047675/73188310-3a01-11e5-87ac-7426a9dd4f17.png)
![screenshot 2015-08-03 17 01 35](https://cloud.githubusercontent.com/assets/1814954/9047674/73180b6a-3a01-11e5-9c23-0c126a515dd3.png)
![screenshot 2015-08-03 17 01 46](https://cloud.githubusercontent.com/assets/1814954/9047673/73126020-3a01-11e5-807e-5c292f25c3af.png)

**Comment by carlfeberhard** [comment] 2015-08-10 14:07
I can't reproduce this on main, importing f4 from aun1, and running fastqc on dataset 1.

Can you reproduce this with a fresh import?

**Comment by martenson** [comment] 2015-08-10 15:44
I am unable to import this history again (I got 'Galaxy could not be reached' after clicking import, three times in a row). Will try later.

**Comment by carlfeberhard** [comment] 2015-09-23 15:41
@martenson Did you get a chance to check this again?

**Comment by martenson** [comment] 2015-09-23 16:13
@carlfeberhard I just tried few times (thanks for the reminder). Same 'could not be reached' message. I guess we can close this as irreproducible? I mean I can reproduce it on the history I have but I guess it somehow got into weird state.

**Comment by carlfeberhard** [comment] 2015-09-23 16:27
I think the hid generator got borked for that history. That might be a side effect of a timeout or a server restart maybe. We should probably validate the hid against the contained datasets once and a while (maybe on add_dataset and add_dataset_collection).

**Comment by carlfeberhard** [comment] 2015-10-06 13:59
@martenson Closing this down if it's alright with you

**Closed as completed** 2015-10-06 13:59 UTC

**Comment by martenson** [comment] 2015-10-06 14:14
completely alright, thank you for looking into this @carlfeberhard !
