### ISSUE TITLE
Tool grouping in the tool bar fails for bwa_mem

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#552] opened 2015-08-04 18:51 UTC
Originally opened as https://github.com/galaxyproject/tools-devteam/issues/197 by @kaktus42 .

Confirmed also on my server with 3 different entries in the tool menu (and no `Versions` select menu in the tool central panel) for `bwa_mem` tool, while everything works fine for `bwa` tool (both from  https://toolshed.g2.bx.psu.edu/view/devteam/bwa/ TS repository).

I suspect the grouping fails because of the underscore in the tool id.

**Comment by nsoranzo** [comment] 2015-08-07 18:32
@jmchilton This seems related to tool lineages, any idea?

**Comment by jmchilton** [comment] 2015-08-07 18:46
Hmm... it does seem related to tool lineages. I think that feature is quite brittle and it fails for us frequently on usegalaxy.org and we land up just hiding the old revisions.  Tool lineages is one of those things that I would rather just put the effort into redoing (and some extent I have - regular tools have tool lineages now that work more simply and cleanly than tool shed tools) than hunting down the current bugs due to it sort of being broken by design (or at least very brittle by design).

**Comment by nsoranzo** [comment] 2015-08-11 17:43
So, I've done some more investigation, and the problem is indeed with tool lineages. In fact, installing more than 1 revision of https://toolshed.g2.bx.psu.edu/view/devteam/bwa/ , creates these tool lineages (as found in `tool_version_association` database table):

bwa/0.3.1 -> bwa/0.3.0 -> bwa/0.2.3 -> bwa/0.2.1 -> bwa/0.1 -> bwa
bwa_mem/0.3.1 -> bwa_mem/0.1
bwa_mem/0.3 -> bwa_mem/0.1
bwa_mem/0.2.2 -> bwa_mem/0.1
bwa_mem/0.2.1 -> bwa_mem/0.1
bwa_mem/0.1 -> bwa_mem

The tool lineage of bwa_mem is not linear, which breaks the tool grouping in the toolbar and the "Tool lineage" view in the Admin panel.

Probably we can fix the tool shed installation to correctly create linear tool lineages, but we would still have the problem of already installed repositories with broken lineages.

Commit https://github.com/nsoranzo/galaxy/commit/0bf20a1f5637f6c1a95242d50a6f851135959aae fixes `ToolVersion.get_versions()` to return all versions of a tool, but there is no easy way to fix their ordering.

@jmchilton: suggestions?

**Comment by jmchilton** [comment] 2015-08-11 17:49
@nsoranzo Probably we just need to fix that table at the outset rather than fixing it up after the fact.

My experience with populating that table is this commit: https://github.com/galaxyproject/galaxy/commit/3e592eeb51681ee7127cfad1eafdb1341232e61c. I don't know if that commit caused the problem (would be interested in knowing if 14.10 has this problem).

What I might try next on to 15.07/dev is to instrument that `fetch_tool_versions` method to see if the Tool Shed is returning the wrong lineage or if Galaxy is somehow populating/using it wrong.

Edit: Also by the way - wow thanks for looking into that - this is really helpful!

**Comment by nsoranzo** [comment] 2015-08-12 00:14
Thank you for the suggestions and comments! The Tool Shed is returning the wrong lineage, just look at https://toolshed.g2.bx.psu.edu/repository/get_tool_versions?name=bwa&owner=devteam&changeset_revision=09a7281d24c5

**Comment by jmchilton** [comment] 2015-08-12 12:35
Anybody think just resetting the metadata on the repository would fix this problem? Someone want to try that?

**Comment by nsoranzo** [comment] 2015-08-12 12:37
I think it may, but I don't have the privileges to do that on the Tool Shed (it's a devteam repo).

**Comment by jmchilton** [comment] 2015-08-12 12:52
Before and after reset - https://gist.github.com/jmchilton/1df3d7ece7b9a8ad907d

Tool Shed response seems fixed!

**Comment by nsoranzo** [comment] 2015-08-12 14:43
Wonderful! I've verified that this fixes new installations.

Unfortunately, for existing installations neither "Reset repository metadata", nor a complete reinstall of all `bwa` repositories fixes the problems. I'm now working on a way to remove the wrong existing entries from the `tool_version_association` database table.

**Comment by bgruening** [comment] 2015-08-12 15:43
@jmchilton can you please rebuild all metadata from devteam? I will do this for IUC.
(there is a special admin menu to reset metdata for all repos at once)

**Comment by martenson** [comment] 2015-08-12 15:50
@bgruening on it
edit: I can also reset metadata on _all_ repositories at once...

**Comment by jmchilton** [comment] 2015-08-12 15:52
Is there any reason to believe that is any more likely to fix something broken than break something previously working. :unamused:

**Comment by martenson** [comment] 2015-08-12 15:54
@jmchilton Hope is the reason. :monkey_face:

**Comment by jmchilton** [comment] 2015-08-12 15:56
"The Tool Shed - Hope is the reason." :sweat_smile:

**Comment by martenson** [comment] 2015-08-12 15:58
"The Tool Shed - By Any Means Necessary." :godmode:

**Comment by martenson** [comment] 2015-08-12 16:00
btw all devteam repos' metadata should be re-set

**Comment by bgruening** [comment] 2015-08-12 16:00
thanks @martenson

**Comment by nsoranzo** [comment] 2015-08-12 16:41
Looks like this mega-reset broke `bwa` repository again, now only the last revision is installable and the lineage is wrong too: https://toolshed.g2.bx.psu.edu/repository/get_tool_versions?name=bwa&owner=devteam&changeset_revision=09a7281d24c5

**Comment by jmchilton** [comment] 2015-08-12 16:43
Stupid hope, hope will always disappoint.

**Comment by martenson** [comment] 2015-08-12 16:46
@nsoranzo individual reset brought back the installable_revisions and lineage is...different again

**Comment by martenson** [comment] 2015-08-12 16:51
as a bonus some other devteam repositories lost their installable revisions too

**Comment by martenson** [comment] 2015-08-13 19:18
the lost instalalble revision as mentioned above seem to be fixed by https://github.com/galaxyproject/galaxy/pull/600

**Closed as completed** 2015-08-14 14:02 UTC
Labels: kind/bug
