### ISSUE TITLE
add_column_regex functionality of __APPLY_RULES__ tool broken for more than one expression group

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11519] opened 2021-03-02 10:59 UTC
I don't quite understand why, but
https://github.com/galaxyproject/galaxy/blob/ce23f963e036722865ecd27fda509f173406ab61/lib/galaxy/util/rules_dsl.py#L45
gets triggered when you're setting up a rule containing an "add_column_regex" type with group_count >=2.
It's only the tool, not the rule-based uploader that is affected by this.

**Comment by mvdbeek** [comment] 2021-03-02 11:03
Do you have an example table and the JSON rule maybe ?

**Comment by wm75** [comment] 2021-03-02 11:10
Try to apply:

```
{
  "rules": [
    {
      "type": "add_column_metadata",
      "value": "identifier0"
    },
    {
      "type": "add_filter_regex",
      "target_column": 0,
      "expression": ".+_\\d",
      "invert": false
    },
    {
      "type": "add_column_regex",
      "target_column": 0,
      "expression": "(ERR\\d+)_(\\d)",
      "group_count": "2"
    }
  ],
  "mapping": [
    {
      "type": "list_identifiers",
      "columns": [
        1
      ],
      "editing": false
    },
    {
      "type": "paired_identifier",
      "columns": [
        2
      ]
    }
  ]
}
```

to the collection in https://usegalaxy.eu/u/wolfgang-maier/h/applyrules

**Comment by mvdbeek** [comment] 2021-03-02 13:58
The group_count is a string, when it should be an integer.
I'll see if we can fix that in the rule builder, but this works
```json
{
  "rules": [
    {
      "type": "add_column_metadata",
      "value": "identifier0"
    },
    {
      "type": "add_filter_regex",
      "target_column": 0,
      "expression": ".+_\\d",
      "invert": false
    },
    {
      "type": "add_column_regex",
      "target_column": 0,
      "expression": "(ERR\\d+)_(\\d)",
      "group_count": 2
    }
  ],
  "mapping": [
    {
      "type": "list_identifiers",
      "columns": [
        1
      ],
      "editing": false
    },
    {
      "type": "paired_identifier",
      "columns": [
        2
      ]
    }
  ]
}
```

**Comment by wm75** [comment] 2021-03-02 14:38
Ah, well spotted! Thanks @mvdbeek, that helps a bit already!

**Comment by jmchilton** [comment] 2021-03-02 19:40
Seems to be a duplicate of https://github.com/galaxyproject/galaxy/issues/11439. I'll see if I can fix it.

**Comment by mvdbeek** [comment] 2021-03-09 09:28
Fixed in https://github.com/galaxyproject/galaxy/pull/11553

**Closed as completed by mvdbeek** 2021-03-09 09:28 UTC
Labels: kind/bug
