### ISSUE TITLE
History feature request

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#14359] opened 2022-07-21 15:49 UTC
locked/frozen histories would be a brilliant feature

Why?
 - I run training
 - I provide 'answer key' history & input links
 - I need these to be unchanged
 - It's very easy to accidentally change/add to these answer keys in the practice of troubleshooting for lots of students during a session
 - No easy way to 'undo this' short of having histories with lots of deleted stuff
 - Please save me from myself

**Comment by hexylena** [comment] 2022-07-21 18:14
duplicate of https://github.com/galaxyproject/galaxy/issues/1734

**Closed as completed by hexylena** 2022-07-21 18:14 UTC
Labels: feature-request, area/histories
