### ISSUE TITLE
Reach parity of the old WF controller and the API

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2899] opened 2016-09-06 14:24 UTC
When we merged #2077 and #2895 we introduced a technical debt that is caused by non-equivalency of old workflow controller and the workflow API. The GUI now temporarily talks to an inferior internal endpoint and the improvements of such is either limited or will introduce more inconsistency.

We should gather a list of disparities and fix them before 16.10 so we can remove the /api_internal/ route.

@guerler @jmchilton @dannon @blankenberg @natefoo please help me make this list, I took the initial set from @guerler's [comment](https://github.com/galaxyproject/galaxy/pull/2077#issuecomment-223062827)
- [x] Sending the outputs to one or multiple new histories
- [x] Linked batchmode
- [x] Unlinked batchmode
- [x] Support for workflow parameters
- [x] Support for data selection within steps
- [ ] Support for resolving output dataset ids and names
- [ ] Unaddressed queuing effect that the history does not auto-refresh anymore
- [x] Support for multi-selection data inputs (addition @guerler)

And the initial answers from @jmchilton's [comment](https://github.com/galaxyproject/galaxy/pull/2077#issuecomment-223107706) 

> > Support for workflow parameters
> 
> This is supported I believe - https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_workflows.py#L1324.
> 
> > Sending the outputs to one or multiple new histories
> 
> I don't think you should build a WorkflowRunConfig directly - there is an existing abstraction that both API endpoints use and it seems to cover this functionality:
> https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/run_request.py#L214
> build_workflow_run_config would also cover workflow parameters if used properly.
> 
> > Linked batchmode
> > Unlinked batchmode
> 
> The implementation here is okay and could probably be adapted in the invocation API? I wish it reused the tools stuff and I wish there logic wasn't placed
> 
> > Support for data selection within steps
> 
> If this works - my intuition suggests either you are not properly backgrounding the workflow or encoded IDs are being saved to the database. I can fix the invocation endpoint to accept these - but previous @dannon and I purposely decided that we should discontinue support for non-input data selection. I don't know if his opinions have changed - but mine have't - it is a mistake to allow it. I've outlined how I believe it should be approached - but if you do not wish to do that and insist the API needs to support the data parameters we hoped to deprecate - I will begrudgingly update build_workflow_run_config and the invocation endpoint to allow this (will require a database migration I believe).
> 
> > Support for resolving output dataset ids and names
> > Unaddressed queuing effect that the history does not auto-refresh anymore
> 
> This needs to be resolved longer term (there is an open issue about limitations regarding history updates - fixing it at the history level would help dynamic tool outputs, collection stuff, GIEs that publish to the history, this workflow endpoint, etc...) - but as a basic starting point the invocation landing page could take the invocation ID and poll the workflow and update the history as new datasets are created. Do you want me to do the UI for that?

**Comment by jmchilton** [comment] 2016-09-06 15:20
The new endpoint dumps encoded HDA ids into the database in deeply nested JSON blobs. We shouldn't ever be doing that:

```
>>> sa_session.query(WorkflowInvocation).all()[1].step_states[0].value
u'{"__page__": 0, "__rerun_remap_job_id__": null, "__STEP_META_STATE__": "{\\"__POST_JOB_ACTIONS__\\": {}}", "input1": "{\\"values\\": [{\\"src\\": \\"hda\\", \\"id\\": \\"911dde3ddb677bcd\\"}]}", "queries": "[]"}'
```

@guerler seemingly refuses to acknowledge this or engage in a discussion as to whether it is a good idea to allow dataset selection within an step - it might be but I feel like we need to reach a consensus on that and the implementation should never be dumping encoded HDA ids into the database.

**Comment by martenson** [comment] 2016-09-06 15:52
@jmchilton I've hit that before back when I was implementing sample tracking, it is hell of a problem when you change the `id_secret`(you have to resolve this manually with the knowledge of the past `id_secret`). 
If this is in dev we should address it quick.

**Comment by jxtx** [comment] 2016-09-06 16:01
This is definitely a serious problem for the reason @martenson mentions -- encode ids can change if id_secret changes.

Is this a regression or did the old PJA code do this? 

Seems like an easy fix, just unpack the dict and translate the ID?

**Comment by dannon** [comment] 2016-09-06 16:06
@jxtx Unless I misread the concern, it's not the PJA code, but the input mappings that are unencoded.  PJAs work off the names of outputs (so, 'output_bam', or whatever).

**Comment by jxtx** [comment] 2016-09-06 16:08
Sorry @dannon, I misread the JSON blob that was posted above. But, still an easy fix?

**Comment by dannon** [comment] 2016-09-06 16:10
Looks like it should be, yeah.

**Comment by jmchilton** [comment] 2016-09-06 16:16
One could imagine unpacking and repacking the dict - but I worked through this - there are actually tables WorkflowRequestToInputDatasetAssociation and WorkflowRequestToInputDatasetCollectionAssociation that allow for real referential integrity. It is a better solution - and it kills me that they will be ignored.

**Comment by guerler** [comment] 2016-09-06 16:39
Yeah this definitely needs to be fixed, and I am sorry but I was not aware of it. June 1, you said about data inputs in steps that you "will begrudgingly update build_workflow_run_config and the invocation endpoint to allow this (will require a database migration I believe).". @jmchilton are you still willing to do that?

**Comment by martenson** [comment] 2016-09-06 16:46
I created an issue for the bug with encoding ids: https://github.com/galaxyproject/galaxy/issues/2900

**Comment by guerler** [comment] 2016-09-07 13:26
Do we want to allow data inputs within steps?

**Comment by martenson** [comment] 2016-09-07 16:05
@guerler If I understand it correctly we need to support it for a while because of existing workflows that use it. Is that correct? Moving ahead it makes sense to me to make it more consistent, remove the implicit data inputs and make user define it explicitly. I assume this would also help CWL @jmchilton ?

**Comment by jmchilton** [comment] 2016-09-07 16:34
> are you still willing to do that?

@guerler I'm taking a break from workflow state - I don't foresee myself implementing that feature at this time.

> we need to support it for a while

We don't "need" to allow it - we could auto-promote the workflows as they are loaded into the run form and warn users the workflow will be saved in a newer state. 

>  Do we want to allow data inputs within steps?

At the time I thought it was a good idea not to allow this, but none of the people who agreed with me have spoken up and if there is no intention from @guerler to work on replacing them - I guess we should just continue down the current path.

**Comment by martenson** [comment] 2016-09-07 16:54
> we could auto-promote the workflows as they are loaded into the run form and warn users the workflow will be saved in a newer state.

I like that. Does this (force explicit data input nodes) help CWL, and/or are there other benefits besides consistency @jmchilton ?

**Comment by jmchilton** [comment] 2016-09-07 17:53
This issue doesn't cut either way on the CWL I don't think. I'd like to move toward more regular, documented, and tested workflow and tool state - that would help any new application.

**Comment by guerler** [comment] 2016-09-13 22:55
Well if you do not want to implement this anymore and there are no benefits, I suggest to close this issue and upgrade the internal_api endpoint to a regular one.

**Comment by jmchilton** [comment] 2016-09-13 23:55
There are clear benefits to having a single and properly RESTful endpoint that is well tested and has bioblend client support. I am fairly confident I will quit this project or use my first -1 before I let that happen.

**Comment by guerler** [comment] 2016-09-14 00:13
Ok. Fair enough. I guess we wait then.

**Closed as completed** 2016-10-05 12:47 UTC
Labels: kind/enhancement, kind/refactoring, area/workflows

**Comment by martenson** [comment] 2016-10-05 14:34
Thanks fellas.
