### ISSUE TITLE
Automatically close obsolete PRs and issues

### ISSUE THREAD

**Issue by beatrizserrano** [galaxyproject/galaxy#11841] opened 2021-04-14 17:33 UTC
This issue is motivated by a discussion with @mvdbeek, @bgruening, @hexylena and some others a few Papercuts ago. There are around 1500 issues and 150 PRs open, which indicates a high level of activity and that the project is very successful. @tnabtaf and I have been thinking recently (and reading [papers](https://ieeexplore.ieee.org/document/8823598) too!) about the potentially harmful effects that this could have on new contributors and the Galaxy community in general: people might be discouraged thinking that their efforts might not lead to a successful merged PR and ultimately, that contributing to Galaxy is a waste of time and resources. 

We assume (just assume, we don't really know) that many of these stale issues/PR don't apply anymore. To prevent the harmful effects, and to show that we care about contributors, we propose using [a bot like this](https://github.com/probot/stale) to clean up a bit. It doesn't have to be something very radical, but incremental (only 30 issues/hour can be closed either way) and many params can be adjusted (date, labels, etc.). The closing message can be tailored too and we can give the option to reopen if still applies.

What is the general feeling about this? Has this been discussed already? If we agree that this is a good idea, would it be a papercut?

Thank you all!

**Comment by bernt-matthias** [comment] 2021-04-19 10:18
While seeing to pros of this approach I have some doubts. 

Mainly I think that this is just a cosmetic change, i.e. it will just make the project look better. And actually I think we are not doing that bad (e.g. we usually close/finish more issues/PRs than we open https://github.com/galaxyproject/galaxy/pulse/monthly).

Also many of the auto-closed issues will still be relevant and potential developers will need to search also for closed+labelled issues if they search for things to work on.

Also the more active developers would get spammed with notifications (in the beginning). Each of the persons mentioned above have 50-150 open issues (would be interesting to see how many issues are from the committers group :) ). And I guess most of them are still relevant. But if I get 80 mails about closed issues in short time I probably don't have the time to check and reopen them.

Maybe there is a good compromise? Maybe just auto-label inactive issues. Then we can detect and treat such cases more efficiently manually. 

> would it be a papercut?

I think so .. if we specify the parameters well enough.

We could also use paper cut days to scan stale issues.

**Comment by hexylena** [comment] 2021-04-20 07:52
I've heard the question first hand about "so many issues is it reliable?" but when they're mostly planning issues, closing doesn't feel productive.

If the problem is appearances and the above question I've heard, then mybe we need more 'advertising' in the readme? (10k citations :writing_hand:, 120+ servers, EU processes 300k jobs a month :tada:)

**Comment by nsoranzo** [comment] 2021-04-20 11:08
I agree with @bernt-matthias and @hexylena , if I want to know if a project is active, I look at the latest commits and the repo pulse Matthias already linked above. A large number of issues is mostly a symptom of a widely-used software.

> We could also use paper cut days to scan stale issues.

I'd vote for this, but without the stale bot.

Of course we could do better with responding/fixing/closing issues and reviewing/merging/closing PRs, but overall I think it's more discouraging for new contributors to have your issue/PR closed by a bot.

**Comment by martenson** [comment] 2021-04-20 11:34
My 2c: This repository is for development work, it is not supposed to serve as a face of the project towards users. For that we have galaxyproject.org, help.galaxyproject.org and most importantly training.galaxyproject.org. Pure users have no business going through the issues and even less through PRs. From my experience the committers group does a decent job at keeping the PRs up to date. When it comes to issues I think they are mostly relevant. 

To test I propose this: do a dry-run of that bot and show me a list of 50 issues that it would like to close. Let's discuss its benefits over that list.

**Comment by bernt-matthias** [comment] 2021-04-20 14:16
> edit: It might be important to note, that if Galaxy could be installed with apt install galaxy

or even better: `conda install galaxy`

**Comment by bernt-matthias** [comment] 2021-04-21 14:00
One further idea: It might be a good idea to auto close issues that have certain labels. For instance if we request additional information and the reporter (or somebody else) answers.  Then a bot would need to auto remove this special label if there is any activity.

**Comment by natefoo** [comment] 2021-04-21 14:25
> or even better: `conda install galaxy`

FWIW this is on the Deployment WG's 2021 T2 roadmap (more specifically `pip install galaxy` but `conda install galaxy` will flow naturally from that).

**Comment by simonbray** [comment] 2021-04-27 12:49
Maybe it's also worth bearing in mind that a large minority of issues never receive a response. I would find it rather irritating to open an issue and to receive the first reply from a bot 1 year later informing me it is about to be closed due to inactivity.

**Closed as completed** 2021-12-23 07:47 UTC

**Comment by hexylena** [comment] 2021-12-23 07:57
Similar issues in the future might be better fits as "discussions" https://github.com/galaxyproject/training-material/discussions as well, we could consider that for ideas that need to be voted on or like this could have multiple viewpoints expressed in their own threads
