### ISSUE TITLE
Cannot tag items in dataset lists or pair of datasets

### ISSUE THREAD

**Issue by nakucher** [galaxyproject/galaxy#13416] opened 2022-02-18 22:44 UTC
**Describe the bug**
Dataset tags can't be added to items in a dataset list, the two items in a pair of datasets, or to the pair of datasets object (this object may be within a list of pairs, which can be tagged).

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Upload files (can use this tutorial: https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html)
2. Select the files and build a dataset list
3. Click into the list and click to tag the item
4. See error - allows you to type in the tag, but no action is performed when you hit enter or the check mark

**Expected behavior**
Expect to be able to add a tag to any item where a tag icon is shown.

**Screenshots**

Item in pair of datasets (same for item in list) -  you can type in the tag, but no action when you hit enter or check
![Screen Shot 2022-02-18 at 5 35 43 PM](https://user-images.githubusercontent.com/80000074/154770352-81ed262b-91e0-42ff-9191-92222f45e875.png)

Pair of datasets - same as above
![Screen Shot 2022-02-18 at 5 37 52 PM](https://user-images.githubusercontent.com/80000074/154770547-eafb39a7-2650-490a-9b8c-d5af0b8c784e.png)

**Additional context**
EU doesn't support tagging lists or items in lists (no tag icon displayed).
![Screen Shot 2022-02-18 at 5 35 08 PM](https://user-images.githubusercontent.com/80000074/154770282-e56cad5a-e8bb-476e-b983-47fa4f2c6fd5.png)

**Comment by mvdbeek** [comment] 2022-03-04 10:49
This isn't a new bug, moving the milestone.

**Comment by bernt-matthias** [comment] 2023-08-03 20:05
https://usegalaxy.eu/root?tool_id=__TAG_FROM_FILE__ might be a solution / workaround?

**Comment by nsoranzo** [comment] 2023-08-04 10:17
Duplicate of https://github.com/galaxyproject/galaxy/issues/14399.

**Closed as not planned by nsoranzo** 2023-08-04 10:17 UTC
Labels: kind/bug, area/UI-UX
