### ISSUE TITLE
Change datatype stuck in constraint loop

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#12066] opened 2021-05-28 00:49 UTC
When trying to change the datatype of a input dataset I get:
```
Dataset metadata could not be updated because it is used as input or output of a running job.
```

The job reports:
```
Input dataset 'SRR3028776_2.fastq' failed to properly set metadata, Input dataset 'SRR3028776_1.fastq' failed to properly set metadata. To resume this job fix the input dataset(s).
```

Deleting the paused job dataset did not resolve the constraint.

**Comment by mvdbeek** [comment] 2021-05-28 07:41
Duplicate of https://github.com/galaxyproject/galaxy/issues/5764

**Closed as completed by mvdbeek** 2021-05-28 07:41 UTC
