### ISSUE TITLE
Restricting tools to "txt" input includes other file types in dropdown

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#670] opened 2015-08-28 15:07 UTC
Hello everyone,
Filter and Sort->Select(grep.xml) is an example of a stock tool that excepts "txt" format input, although it also allows html and fastq files to be selected as inputs for the tool. I have a tool which parses plain text output from FastQC, although the following are available from the input dropdown:
FastQC on data 2: Plain Text
FastQC on data 2: Webpage

Thus, the correct input is more ambiguous (besides a big label that says "pick a plain text file").
I have seen this in 15.05, it may be present elsewhere.

**Comment by jmchilton** [comment] 2015-09-09 18:55
@MatthewRalston This is the intended behavior - there is no way to specify an input should take only a plain text dataset and not a more specific datatype. The type system is sort of modeled on object oriented  type systems - so an HTML datatype "[is a](https://en.wikipedia.org/wiki/Is-a)" text datatype - so any tool that operates on any text dataset should work on HTML datatypes as well.

Is this fair, can I close this issue? It would be easy enough to add an `extact_format` attribute or something to the tool XML format but I would be hesitant to add it since it would violate the nature of "is a" relationships.

**Closed as completed** 2016-09-22 17:19 UTC
