### ISSUE TITLE
Data libraries search on folders returns no results

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11461] opened 2021-02-24 12:02 UTC
The search is working at the top level `https://{your-galaxy}/library/list` but if you try to search inside one of the folders the search returns no results.

## Steps
1. Go to `https://{your-galaxy}/library/list`.
2. Select one of the folders, for example, `GTN - Material`.
3. Try to search for any known folder.

![bug_search](https://user-images.githubusercontent.com/46503462/108997741-433f5100-76a0-11eb-8461-53f312bd1648.gif)

This seems to affect 20.09

**Comment by mvdbeek** [comment] 2021-02-24 12:03
@OlegZharkov can you take a look at this ?

**Comment by OlegZharkov** [comment] 2021-02-24 12:20
That's weird, for some reason, I cannot reproduce it locally. This shouldn't affect 20.09, because it doesn't have pagination

**Comment by mvdbeek** [comment] 2021-02-24 12:21
It is not related to pagination.

**Comment by OlegZharkov** [comment] 2021-02-24 12:22
> It is not related to pagination.

I mean, 20.09 search is UI only, while 21.01's search is done on backend.

**Comment by mvdbeek** [comment] 2021-02-24 12:24
Are we maybe not talking of the same search ? This is 20.09 in the screenshot:
![Uploading Screenshot 2021-02-24 at 13.23.58.png…]()

**Comment by OlegZharkov** [comment] 2021-02-24 12:30
> Are we maybe not talking of the same search ? This is 20.09 in the screenshot:
> <img alt="Screenshot 2021-02-24 at 13 23 58" width="2000" src="https://user-images.githubusercontent.com/6804901/109000174-a54d8580-76a3-11eb-9cca-c9b815273601.png">

That is probably 20.09 on galaxy.eu? It was backported on eu, but not on upstream. Here's the PR https://github.com/galaxyproject/galaxy/pull/10204

**Comment by mvdbeek** [comment] 2021-02-24 12:32
ugh ... thanks. Can you look at this anyway please ? The API response is correct, so looks like a state issue ?

**Comment by OlegZharkov** [comment] 2021-02-24 12:34
> ugh ... thanks. Can you look at this anyway please ? The API response is correct, so looks like a state issue ?

API response is not correct, it returns an empty array 
https://usegalaxy.org/api/folders/Fb063e4a03864ef16/contents?include_deleted=false&limit=15&offset=0&search_text=Eco
and I really wonder why, for some reason everything works fine locally

**Comment by mvdbeek** [comment] 2021-02-24 12:38
... ok, sorry about that, I was expect a literal empty response when there's no match. On the bright side it's the API response then that is not correct.

**Comment by OlegZharkov** [comment] 2021-02-24 12:58
> ... ok, sorry about that, I was expect a literal empty response when there's no match. On the bright side it's the API response then that is not correct.

that's right :+1: 
anyway, I will something out

**Comment by mvdbeek** [comment] 2021-02-25 08:50
Should be fixed in https://github.com/galaxyproject/galaxy/pull/11463

**Closed as completed by mvdbeek** 2021-02-25 08:50 UTC
Labels: kind/bug, area/API, area/libraries

**Comment by OlegZharkov** [comment] 2021-02-25 10:22
damn, I wanted to see whether it's getting closed automatically after we merge 21.01 in dev :sweat_smile:
