### ISSUE TITLE
Edited workflow not getting invoked

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy#11593] opened 2021-03-11 01:10 UTC
There seems to be a problem blocking workflow invocation when some parameters are edited right before running (works if same changes are made in workflow editor first).

Came up when my partner was running through the last step of: https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html

I was able to replicate it on both Main (https://usegalaxy.org/u/almahmoud/w/from-peaks-to-genes-imported-from-uploaded-file) and a cloud instance running 21.01, no relevant logs that I could find in either web or workflow handler. Seems to be an issue before the workflow is ever invoked though cause the request gets `400 Bad Request` when running with the changes.
Not sure how relevant, but:
1) The workflow was originally created from a history, as per the tutorial.
2) Changing some other parameters on the same tool still works (eg: switching true to false, so seems something to do with these params specifically).
3) The two requests have identical bodies, with the exception of the two changed things.

![workflow-bug](https://user-images.githubusercontent.com/14061824/110720042-eb463580-81db-11eb-862c-e3d7d2526adb.gif)

**Comment by mvdbeek** [comment] 2021-03-11 10:43
These runtime parameter changes are prone to breaking, that is why we worked hard on adding workflow parameters. What you're seeing there happens when you change a data_column parameter that references a dataset that is not available in the workflow context. We can probably fix this, but I'd also say that we need to deprecate these ad-hoc parameter changes in favor of structured workflow parameters. This is essentially a duplicate of https://github.com/galaxyproject/galaxy/issues/11524 (with slightly different setup)

**Comment by mvdbeek** [comment] 2021-03-11 16:11
Thanks @almahmoud, https://github.com/galaxyproject/galaxy/pull/11596 should fix this.

**Closed as completed** 2021-03-16 15:25 UTC
Labels: kind/bug, area/workflows
