### ISSUE TITLE
GenomeDiversity Admixture has dependency/config issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2641] opened 2016-07-20 23:55 UTC
Example of error - see last lines for where the missing module (lapack_lite) is noted:

> Tool execution generated the following error message:
> Traceback (most recent call last):
>   File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/miller-lab/genome_diversity/884ccb07885b/genome_diversity/dpmix.py", line 8, in <module>
>     from dpmix_plot import make_dpmix_plot
>   File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/miller-lab/genome_diversity/884ccb07885b/genome_diversity/dpmix_plot.py", line 7, in <module>
>     import matplotlib as mpl
>   File "/galaxy/main/deps/matplotlib/1.2.1/iuc/package_matplotlib_1_2/9d164359606b/lib/python/matplotlib/**init**.py", line 165, in <module>
>     from matplotlib.rcsetup import (defaultParams,
>   File "/galaxy/main/deps/matplotlib/1.2.1/iuc/package_matplotlib_1_2/9d164359606b/lib/python/matplotlib/rcsetup.py", line 20, in <module>
>     from matplotlib.colors import is_color_like
>   File "/galaxy/main/deps/matplotlib/1.2.1/iuc/package_matplotlib_1_2/9d164359606b/lib/python/matplotlib/colors.py", line 52, in <module>
>     import numpy as np
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/**init**.py", line 137, in <module>
>     import add_newdocs
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/add_newdocs.py", line 9, in <module>
>     from numpy.lib import add_newdoc
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/lib/**init**.py", line 13, in <module>
>     from polynomial import *
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/lib/polynomial.py", line 17, in <module>
>     from numpy.linalg import eigvals, lstsq, inv
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/linalg/**init**.py", line 48, in <module>
>     from linalg import *
>   File "/galaxy/main/deps/numpy/1.7.1/iuc/package_numpy_1_7/028df1ddd7a2/lib/python/numpy/linalg/linalg.py", line 23, in <module>
>     from numpy.linalg import lapack_lite
> ImportError: liblapack.so.3: cannot open shared object file: No such file or directory

**Comment by natefoo** [comment] 2016-09-28 15:50
I updated the genome diversity tools. Compiling eigensoft required manually hacking the package_eigensoft_5_0_1 tool_dependencies.xml to find liblapack.so:

``` xml
    <action type="shell_command">make LDFLAGS='-I../include -pthread -L/galaxy/main/deps/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib -Wl,-rpath=/galaxy/main/deps/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib' install</action>
```

miller_lab's package_eigensoft_5_0_1 should probably be updated to depend on atlas to fix this properly. ping @richard-burhans 

This update also resulted in reinstalling genome_diversity's tool_dependency on iuc's numpy 1.7 to a newer version which does not depend on atlas. The old version needed atlas but was not sourcing atlas' env.sh, which was the cause for the missing liblapack.

The location files for these tools are also manually configured and may be out of date. For example, the only reference in `gd.heterochromatic.loc` for this tool is canFam2.

Running this tool on the test data (which would previously fail with the above error) now fails with the error:

```
FAILED:
SNP at chr1 -1 is out of order; run the Filter SNPs tools with 'Minimum spacing between SNPs' set to 1

COMMAND:
dpmix /galaxy-repl/main/files/017/328/dataset_17328569.dat 6 all 0 1 10.0 /galaxy/data/genome_diversity/dpmix/canFam2_heterochrom.txt
```

So I ran sample.gd_snp through Filter SNPs and got the same answer. So I am not sure what the next step is, but at least the dependency problem is fixed.

**Comment by jennaj** [comment] 2016-09-28 19:26
@natefoo I'll run a test, feedback soon

**Comment by jennaj** [comment] 2016-10-07 22:04
@natefoo works now. guessing that other tests have a data problem? Close or fix sample.gd_snp first?

**Comment by natefoo** [comment] 2016-10-14 20:03
I'd say let's just close it.

**Closed as completed by natefoo** 2016-10-14 20:03 UTC
