### ISSUE TITLE
Exception on tool install

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7206] opened 2019-01-11 14:15 UTC
I tried to install the new version of the datamash suite. First with epemeris (using ansible) which resulted in tools with unknown toolshed status (blue icon). When I click install (also after updating toolshed status which gave me an installed tool in status New): 

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 75, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 166, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 181, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 98, in decorator
    return func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py", line 591, in manage_repository
    repository = repository_util.get_installed_tool_shed_repository(trans.app, repository_id)
  File "lib/tool_shed/util/repository_util.py", line 399, in get_installed_tool_shed_repository
    repository_ids = [app.security.decode_id(i) for i in id]
  File "lib/galaxy/web/security/__init__.py", line 84, in decode_id
    return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
```

I got quite some tools stuck in status New ...

**Comment by mvdbeek** [comment] 2019-01-22 12:47
duplicate of https://github.com/galaxyproject/galaxy/issues/5619, fix is incoming

**Closed as completed by mvdbeek** 2019-01-22 12:47 UTC
