### ISSUE TITLE
The context manager that is supposed to silence a migration error doesn't work for postgresql. 

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#13617] opened 2022-03-24 21:19 UTC
The context manager that is supposed to silence a migration error (#13595) doesn't work for postgresql. As per Mike Bayer (author of Alembic and SQLAlchemy), "when an integrity error is issued by Postgresql, such as attempting to insert a primary key that already exists, the ongoing transaction is then marked as invalid. If you try to do anything else in the transaction, you get that error." ([ref](https://groups.google.com/g/sqlalchemy/c/r43b26pjzpY/m/g0aoIiVBWmYJ); same in [psycopg docs](https://www.psycopg.org/docs/faq.html))

**To Reproduce**
1. Make sure galaxy is up-to-date (current dev branch: `source_metadata` column should exist in `workflow` table)
2. Delete rows from `alembic_version` table
3. Run `manage_db.sh upgrade`, observe error (this will only happen on postgresql)

```
(.venv) rivendell$ ./manage_db.sh upgrade
Activating virtualenv at .venv
Traceback (most recent call last):
  File "/home/sergey/0dev/galaxy/_galaxy/dev/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/home/sergey/0dev/galaxy/_galaxy/dev/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

...

  File "/home/sergey/0dev/galaxy/_galaxy/dev/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: UPDATE alembic_version SET version_num='b182f655505f' WHERE alembic_version.version_num = 'e7b6dcb09efd']
(Background on this error at: https://sqlalche.me/e/14/2j85)
```

**Expected behavior**
The error should be ignored.

**Solution Thoughts**
Ideally, we'd like to rollback the transaction - but if we do that, Alembic will not proceed to update the version, defeating the purpose of silencing the error.

**Comment by ic4f** [comment] 2022-03-24 23:21
So, if we know the cause of this error (e.g. a revision is being executed on a database that already contains the change specified in the revision), we can just use the `stamp` command to stamp the database with the correct version. For example, if the `alembic_version` table is empty or has incorrect values, we can restore the correct versions for both gxy and tsi models (galaxy and tool shed install) by running these 2 commands that will add the correct revision numbers to the alembic_version table:

```sh
sh run_alembic.sh  stamp gxy@b182f655505f  # this will add revision b182f655505f for the gxy model 
sh manage_db.sh upgrade  # this will add the current revision for the tsi model
# (or, instead of manage_db, you could run the stamp command for the tsi revision)
```
The revision numbers are stored in the revision files in `lib/galaxy/model/migrations/alembic/version_[gxy|tsi]/*`:
```py
  1 """add workflow.source_metadata column
  2 
  3 Revision ID: b182f655505f
  4 Revises: e7b6dcb09efd
  5 Create Date: 2022-03-14 12:56:57.067748
  6 
  7 """
  8 from alembic import op
  9 from sqlalchemy import Column
 10 
 11 from galaxy.model.custom_types import JSONType
 12 from galaxy.model.migrations.util import (
 13     drop_column,
 14     ignore_add_column_error,
 15 )
 16 
 17 # revision identifiers, used by Alembic.
 18 revision = "b182f655505f"
 19 down_revision = "e7b6dcb09efd"
 20 branch_labels = None
 21 depends_on = None
 22 
 23 
 24 def upgrade():
 25     table, column = "workflow", "source_metadata"
 26     with ignore_add_column_error(table, column):
 27         op.add_column(table, Column(column, JSONType))
 28 
 29 
 30 def downgrade():
 31     drop_column("workflow", "source_metadata")
```
This will work after #13618 is merged.

**Comment by mvdbeek** [comment] 2022-03-25 09:02
Are you implying that deployers should run `run_alembic.sh` ? Can we not just check if the column is there ? This seems like a much better UX. I'm not super comfortable with users having to touch alembic outside of the manage_db.sh script.

**Comment by mvdbeek** [comment] 2022-03-25 09:06
Alternatively, can we not just add those exceptions to the ignored exceptions in ignore_add_column_error ?

**Comment by ic4f** [comment] 2022-03-25 15:01
> Are you implying that deployers should run `run_alembic.sh` ? 

No, deployers shouldn't have to deal with alembic. The referenced PR fixes a specific bug which prevents running that particular alembic command. (which, still, helps solve the issue without touching the database)

> Can we not just check if the column is there ? 

Yes, and if I can't come up with a better solution, I'll do that. But I'm afraid it's not very scalable: that approach implies that we do a check for every type of database schema update - like adding/dropping/altering a column/table/index/trigger in any number of ways. A case-by-case basic implies we wait for things to break, which is not optimal too.

> I'm not super comfortable with users having to touch alembic outside of the manage_db.sh script.

You mean a wrapper script with a well defined and very limited interface - but we've never had that. Because `manage_db.sh` is nothing but a wrapper around the SQLAlchemy Migrate CLI runner - so users have been using the previous migration tool directly since the very beginning. That said, I agree that a wrapper with a permanent and simplified/limited interface is the way to go.

> Alternatively, can we not just add those exceptions to the ignored exceptions in ignore_add_column_error ? 

So, if my understanding is correct, the ***first error*** is issued by psycopg as a result of the "duplicate column" (in this particular case) transaction error. The current error handling works fine - ***it catches this error***, which is why it works in SQLite. However, with postgres the failed transaction needs to be rolled back before a subsequent transaction can be executed. We don't do that (I am not sure how to do that yet - might be under the hood in alembic for all I know, but I'm looking now); which is why ***the next transaction*** - the one which updates the version table - fails with the `psycopg2.errors.InFailedSqlTransaction` error (which is raised outside the revision script). Furthermore, I suspect that Alembic may not want to update the version table if the transaction that was supposed to modify the database was rolled back. (suspicion only - don't know for sure)

**Comment by mvdbeek** [comment] 2022-03-25 15:05
> Yes, and if I can't come up with a better solution, I'll do that. But I'm afraid it's not very scalable: that approach implies that we do a check for every type of database schema update - like adding/dropping/altering a column/table/index/trigger in any number of ways. A case-by-case basic implies we wait for things to break, which is not optimal too.

There are very limited circumstances in which we need to ignore an exception because the column may or may not be there. I don't think we need to come up with something general or re-usable.

**Comment by ic4f** [comment] 2022-03-25 15:14
> There are very limited circumstances in which we need to ignore an exception because the column may or may not be there. I don't think we need to come up with something general or re-usable.

OK, I'll handle this (or, rather, this type of change) as a special case then.

**Closed as completed** 2022-03-28 16:34 UTC
Labels: kind/bug, area/database
