### ISSUE TITLE
Conda dependency resolution does not always create ~/_conda/bin/activate

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2797] opened 2016-08-16 15:05 UTC
I have repeatedly encountered an issue where Galaxy creates a new conda environment when a tool is installed from the Tool Shed that defines conda dependencies.  This behavior seems to be intermittent though, but can be reproduced (intermittently).

Steps to repoduce:
1. Eliminate any conda environment previously created by Galaxy.
2. Install this tool from the TTS: https://testtoolshed.g2.bx.psu.edu/view/greg/r_hello_world/887b76c1b7d1
3. Check for activate in ~/_conda/bin - it may not be there (although it may be, if it is, start step1).

The tool will fail to find dependencies during execution, which is a bit misleading when reading the tool error via the bug icon.  The dependencies are properly installed, but activate is missing, so the job fails due to this component of the tool_script.sh file which attempts to activate the conda environment.

```
[ "$CONDA_DEFAULT_ENV" = "/home/greg/jwd/000/69/conda-env" ] || . /home/greg/_conda/bin/activate '/home/greg/jwd/000/69/conda-env' 2>&1
```

**Comment by mvdbeek** [comment] 2016-08-16 15:09
Ah yes, I have seen this once before, thanks for confirming!
My guess is that this happens either when we install conda or when we downgrade to 3.19.3.
Perhaps we can check that `activate` is really there after the install and try again if it is not?!

**Comment by nsoranzo** [comment] 2016-08-16 15:15
IIRC I also had this problem when the conda environment was not created correctly due to the infamous Conda prefix issue.

**Comment by mvdbeek** [comment] 2016-08-16 15:19
I'll run a loop and see how often this fails

**Comment by gregvonkuster** [comment] 2016-08-16 15:20
I'm hoping my conda prefix is now ok - it is about as short as I can make it: /Users/gvk/_conda.

**Comment by mvdbeek** [comment] 2016-08-23 08:58
Yup, turns out this can happen when we downgrade conda.
Fix for conda is here https://github.com/conda/conda/pull/3210/files, but we're stuck with the old conda due to some other bugs :(.
On the bright side, I may have coincidentally fixed this with https://github.com/conda/conda/pull/3210/files, since we're avoiding parallel conda installations now.

**Comment by stevecassidy** [comment] 2016-08-29 04:40
@mvdbeek I'm seeing this issue consistently when I install my packages via conda. 100% repeatable. Is there a workaround that i can apply to get things working?

**Comment by mvdbeek** [comment] 2016-08-29 07:03
@stevecassidy this is very interesting and confirming once more that the bug is on the conda side,
because the docker image installs conda through their regular install script.
Yes, you should be able to copy `activate`, `conda` and `deactivate` from /tool_deps/_conda/pkgs/conda-4.1.11-py35_0/bin/ into /tool_deps/_conda/bin/.
Please let us know if this works, because then I think @bgruening should update the container.

So apparently this has been fixed in the 4.2.3 release, we could upgrade to 4.2.3, then downgrade to 3.19.3 to avoid the problem.

**Comment by stevecassidy** [comment] 2016-08-29 07:25
@mvdbeek thanks. I tried copying in activate and deactivate (conda is there already) and then get an error output from my tool:

Error: did not expect more than one argument.

which looks like it comes from 'activate' 

Note that I seem to be running the 'dev' branch of galaxy which is what comes down with bgruening/galaxy-stable at the moment.  Not sure if this is making a difference to anything. I'm trying to get 16.07 into a docker image to test that.

**Comment by mvdbeek** [comment] 2016-08-29 08:34
OK, this worked for me inside of the docker container:

```
rm -R /tool_deps/_conda && wget https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh && bash Miniconda2-4.0.5-Linux-x86_64.sh -b -p $GALAXY_CONDA_PREFIX && rm Miniconda2-4.0.5-Linux-x86_64.sh && $GALAXY_CONDA_PREFIX/bin/conda install -y conda==3.19.3
```

My preliminary conclusion is that the up/downgrade has been broken with the 4.1 release. Can you confirm this works for you, @stevecassidy ?

**Comment by stevecassidy** [comment] 2016-08-30 02:53
Yes @mvdbeek, I can confirm that this works (thanks!!). In my case I used Miniconda3 since that was what had been installed in the container. 

I added this to my Dockerfile and was able to build an image derive from bgruening/galaxy-stable:16.07 that installs my tool and works ok.

**Comment by mvdbeek** [comment] 2016-08-30 07:31
Good to hear @stevecassidy. I've opened a PR to galaxy and to docker-galaxy-stable, so that this will not be a problem in the future. I hope this will also fix @gregvonkuster problem,
though this seems to be a `sometimes it works, sometimes it doesn't` problem.

**Comment by bgruening** [comment] 2016-09-03 02:23
I updated the 16.07 Docker Image as well as :latest. Hope this helps. Thanks @mvdbeek!

**Comment by jmchilton** [comment] 2017-02-20 12:59
We've upgraded our target Conda version so this should no longer be a problem with 17.01. Please re-open and let me know if this occurs with 17.01 or later.

**Closed as completed by jmchilton** 2017-02-20 12:59 UTC
