### ISSUE TITLE
Activating the "modules" dependency resolver prevent a Galaxy instance to start properly

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/galaxy#4452] opened 2017-08-18 08:19 UTC
If you try to uncomment the "**modules**" dependency resolver in the **dependency_resolvers_conf.xml** file and try to start the Galaxy instance then it will fail with the following errors:

```
Traceback (most recent call last):
  File "./scripts/manage_tool_dependencies.py", line 87, in <module>
    main()
  File "./scripts/manage_tool_dependencies.py", line 26, in main
    action_func(args)
  File "./scripts/manage_tool_dependencies.py", line 33, in _init_if_needed
    _build_dependency_manager_no_config(kwargs)
  File "./scripts/manage_tool_dependencies.py", line 76, in _build_dependency_manager_no_config
    dependency_manager = DependencyManager( **dependency_manager_kwds )
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/__init__.py", line 84, in __init__
    self.dependency_resolvers = self.__build_dependency_resolvers( conf_file )
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/__init__.py", line 195, in __build_dependency_resolvers
    return self.__parse_resolver_conf_xml( plugin_source )
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/__init__.py", line 210, in __parse_resolver_conf_xml
    return plugin_config.load_plugins( self.resolver_classes, plugin_source, extra_kwds )
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/util/plugin_config.py", line 36, in load_plugins
    return __load_plugins_from_element(plugins_dict, source, extra_kwds)
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/util/plugin_config.py", line 48, in __load_plugins_from_element
    plugin = plugins_dict[ plugin_type ]( **plugin_kwds )
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/resolvers/modules.py", line 47, in __init__
    self.module_checker = AvailModuleChecker(self, self.modulepath, prefetch, self.default_indicator)
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/resolvers/modules.py", line 118, in __init__
    for module in self.__modules():
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/resolvers/modules.py", line 137, in __modules
    raw_output = self.__module_avail_output().decode("utf-8")
  File "/home/arbernard/galaxy_project/galaxy/lib/galaxy/tools/deps/resolvers/modules.py", line 156, in __module_avail_output
    return Popen(avail_command, stderr=PIPE, env={'MODULEPATH': self.modulepath}).communicate()[1]
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] Aucun fichier ou dossier de ce type
```

The message in the log file is a bit more explicit:

> IOError: [Errno 2] Aucun fichier ou dossier de ce type: ./config/environment_modules_mapping.yml.sample'

There is indeed no such file in the config folder of recent Galaxy version.
I didn't found any documentation about this file yet.

**Comment by nsoranzo** [comment] 2017-08-18 11:01
Introduced in https://github.com/galaxyproject/galaxy/pull/3444 . Probably the easiest solution is to add an empty `config/environment_modules_mapping.yml.sample` file.

**Comment by jmchilton** [comment] 2017-08-18 17:31
@mvdbeek I just noticed you self-assigned this issue - I didn't notice that before I started hacking on it - sorry. I'm missing a lot of details today.

**Comment by mvdbeek** [comment] 2017-08-18 17:32
I didn't do anything yet, no worries.

**Comment by FredericBGA** [comment] 2019-02-19 16:50
On branch release_18.05 : the issue is still here.
Can we use the same type of file as lmod_modules_mapping.yml.sample ?

**Comment by mvdbeek** [comment] 2019-03-31 14:02
Should be fixed by https://github.com/galaxyproject/galaxy/pull/7398, many thanks to @FredericBGA

**Closed as completed by mvdbeek** 2019-03-31 14:02 UTC
Labels: kind/bug, area/tool-dependencies
