### ISSUE TITLE
Preserve a readable masthead, even when a brower window is smaller

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#10417] opened 2020-10-13 19:14 UTC
One use case brought up at Galaxy Help (and that many have run into before): Tutorial and Galaxy both in open browser windows -- Galaxy's Masthead becomes messy when the window shrinks. GTN website creates a "hamburger" menu -- Galaxy could do the same.

Users can manage the panes open (right, middle, left). Or it could autoscale -- but that's a bigger ask. Keeping this simple.

Good
<img width="507" alt="masthead-gtn-hamburger" src="https://user-images.githubusercontent.com/8999735/95905046-2fc4c680-0d4d-11eb-9759-da14390de86f.png">

Good
<img width="1101" alt="masthead-full" src="https://user-images.githubusercontent.com/8999735/95905007-22a7d780-0d4d-11eb-9a46-f50b0babd927.png">
Going
<img width="761" alt="masthead-crunch-1" src="https://user-images.githubusercontent.com/8999735/95905018-263b5e80-0d4d-11eb-8f49-9a9df141a996.png">
Gone
<img width="586" alt="masthead-crunch-2" src="https://user-images.githubusercontent.com/8999735/95905026-29364f00-0d4d-11eb-972e-9f8ed09901f3.png">

**Comment by mvdbeek** [comment] 2020-10-14 11:13
Duplicate of https://github.com/galaxyproject/galaxy/issues/9844

**Closed as completed by mvdbeek** 2020-10-14 11:13 UTC
Labels: triage, paper-cut
