### ISSUE TITLE
[Feature Request] Default values for integer/float workflow params

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#18412] opened 2024-06-17 13:05 UTC
Hi,

The default for integer/float workflow params seem to be set to zero. It would be great if there was an option to provide sensible defaults. 

![def](https://github.com/galaxyproject/galaxy/assets/22501424/d7122f26-5138-452f-a454-5fd793c34447)

Thanks!

**Comment by bernt-matthias** [comment] 2024-06-17 17:57
You can do this for optional workflow parameters: 

![Screenshot from 2024-06-17 19-55-42](https://github.com/galaxyproject/galaxy/assets/25689525/286ac871-b2bc-48fe-9747-75dcde285a5a)

For required workflow parameters I would expect that the default of the tool is used .. but overriding this default might be useful.

**Comment by mvdbeek** [comment] 2024-06-18 07:32
I think the bug here is that 0 is auto-filled ? In which case that's a duplicate of https://github.com/galaxyproject/galaxy/issues/16091

**Comment by microfuge** [comment] 2024-06-18 09:23
Thanks @bernt-matthias , Thanks @mvdbeek 
I was not aware of this option being available for optional workflow params. Unfortunately the default from the tool is not used and in this case 0 is getting used when the tool runs.

**Comment by mvdbeek** [comment] 2024-08-06 13:40
I'll close this as a duplicate of https://github.com/galaxyproject/galaxy/issues/16091 and will plan to start working on more workflow parameter types, restrictions and fixes soon.

**Closed as completed by mvdbeek** 2024-08-06 13:40 UTC
