### ISSUE TITLE
Cannot add or remove tags on datasets inside collections via Web-UI

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11745] opened 2021-03-29 10:18 UTC
Unlike for regular datasets the UI doesn't allow you to add tags to or remove tags from datasets that are part of collections.
Here's a history for reproducing/testing:
https://usegalaxy.eu/u/sars-cov2-bot/h/cog-uk-mar-2---mar-24
The top-most collection in this history has the first couple of elements tagged already (through bioblend), others untagged.

**Comment by jmchilton** [comment] 2021-03-30 14:20
I think this is a duplicate of https://github.com/galaxyproject/galaxy/issues/8553.

**Comment by bernt-matthias** [comment] 2023-08-03 20:04
https://usegalaxy.eu/root?tool_id=__TAG_FROM_FILE__ might be a solution / workaround.

**Comment by nsoranzo** [comment] 2023-08-04 10:17
Duplicate of https://github.com/galaxyproject/galaxy/issues/14399.

**Closed as not planned by nsoranzo** 2023-08-04 10:17 UTC
Labels: kind/bug
