### ISSUE TITLE
Numeric "simple inputs used for workflow logic" do not attach appropriately in workflows

### ISSUE THREAD

**Issue by jraysajulga** [galaxyproject/galaxy#7977] opened 2019-05-15 19:38 UTC
![Screen Shot 2019-05-15 at 2 32 22 PM](https://user-images.githubusercontent.com/32586466/57803527-4319cf80-771e-11e9-92d4-7ef8bf0e06f5.png)

Textual _"simple inputs used for workflow logic"_ connect to string inputs as intended.

However, **numeric** _"simple inputs used for workflow logic"_ do not. I believe this might be a bug of some sort within the Workflow Editor.

Galaxy version 19.01 I believe? (https://usegalaxy.eu)

**Comment by mvdbeek** [comment] 2019-05-15 21:01
So the issue is probably that the workflow editor wouldn't update the param type when you switch it to integer. Saving and reloading the workflow works as a workaround, but we also fixed this to be immediate with https://github.com/galaxyproject/galaxy/pull/7780, which will be included in 19.05. usegalaxy.org and test.galaxyproject.org are already running 19.05 if you want to double-check this.

Thanks for the report & feel free to re-open if that still doesn't work on 19.05

**Closed as completed by mvdbeek** 2019-05-15 21:01 UTC

**Comment by jraysajulga** [comment] 2019-05-15 21:36
@mvdbeek Thank you! That worked :D Should have tried doing that first.
