### ISSUE TITLE
"Get repository updates" fails to update in memory version of Tool

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3813] opened 2017-03-24 12:08 UTC
This is a regression.

- In admin interface update a tool repository, without version change
- Tool on disk is updated.
- Tool in memory is not, the old form is displayed and the old tool logic (cmdline, configfiles, etc) is used.
- Current Workaround: You can manually click 'Reload Tool XML' in the tool interface as an admin to fix the problem. (or restart Galaxy)

**Comment by mvdbeek** [comment] 2017-03-24 12:12
Xref https://github.com/galaxyproject/galaxy/issues/3298

**Comment by nsoranzo** [comment] 2017-03-24 13:53
Duplicate of #3298.

**Closed as completed by nsoranzo** 2017-03-24 13:53 UTC
Labels: kind/bug, area/tools
