### ISSUE TITLE
RO Crate download not working (on EU), .tgz download doesn't include . in the filename.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15895] opened 2023-04-04 13:34 UTC
## RO Crate

1. Export History
2. Advanced
3. RO-Crate
4. Download

After a few minutes I'm redirected to https://usegalaxy.eu/api/short_term_storage/e011ff85-3f80-45ab-94bd-4bba286b8093 and see:

K | V  
-- | --
err_msg | "Unknown error: dest_path must be provided if source is not a path or URI"
err_code | 500001

## tgz downloads

```
$ ls Downloads/*targz*
Downloads/Unnamed-historytargz
Downloads/Unnamed-historytargz(1)
```

Seen on UseGalaxy.eu

**Comment by hexylena** [comment] 2023-04-04 13:34
I'm not sure if either of these are related to #15894  but wanted to flag them just in case.

**Comment by mvdbeek** [comment] 2023-04-04 13:35
Duplicate of #15821, closing this since the other one has the traceback.

**Closed as completed by mvdbeek** 2023-04-04 13:35 UTC
