### ISSUE TITLE
Importing data through the UCSC browser logs out user

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#9451] opened 2020-02-26 21:36 UTC
Using the get data -> UCSC browser tool to import a dataset logs out a user on the .org server across all tabs in chrome. 

This originally started when trying to go back to the "Submitted request" page after the main page reloaded, but now occurs whenever pulling data with the tool

**Comment by ic4f** [comment] 2021-02-23 02:05
This is still an issue (discovered in the course of 21.01 release testing).

**Comment by dannon** [comment] 2021-02-23 02:20
xref https://github.com/galaxyproject/galaxy/issues/11374, which was a duplicate of this but now has more pertinent information (so I'm closing this one again)

**Closed as completed** 2021-02-23 02:20 UTC
Labels: kind/bug, area/UI-UX

**Comment by ic4f** [comment] 2021-02-23 03:14
@dannon thanks - I didn't find that one!
