### ISSUE TITLE
SnpEff Download retrieving wrong genome

### ISSUE THREAD

**Issue by madelaineb** [galaxyproject/galaxy#4677] opened 2017-09-22 17:51 UTC
Tested 'SnpEff Download' with Zea_mays and Zhouia_amylolytica_ad3 - in both cases the tool is downloading Yersinia_pseudotuberculosis_gca_001110725.

**Comment by jennaj** [comment] 2017-09-27 00:12
Thanks @madelaineb - the issue is tracked here so I am going to close this out and link the two.

https://github.com/galaxyproject/tools-iuc/issues/1354

**Closed as completed by jennaj** 2017-09-27 00:12 UTC
