### ISSUE TITLE
Tags not immediately displayed when using rule builder

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11446] opened 2021-02-23 04:26 UTC
May be too minor for an issue - please close if that's the case.
When tags are set with Rule Builder, they are not immediately displayed; however, during job execution, when datasets changes state, the tag is very briefly displayed (< 1 sec). Once the datasets are uploaded, it takes a page refresh to display the tags. 

Expected behavior: tags should appear either immediately once the dataset appears, or at least once job completes. Definitely no blinking tags.

Discovered during 21.01 release testing, tutorial: Name tags for following complex histories

**Comment by hexylena** [comment] 2021-02-23 08:45
duplicate of https://github.com/galaxyproject/galaxy/issues/8768, sorry :( it's a longstanding bug, would love to see it fixed.

**Closed as completed by hexylena** 2021-02-23 08:45 UTC
Labels: kind/bug, area/UI-UX
