### ISSUE TITLE
Saving a broken workflow hangs forever and requires a page refresh

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7140] opened 2018-12-20 12:24 UTC
Seen on dev with @shiltemann, if you upload a 'broken' workflow with missing tools/etc, and try to save it, the safe dialog hangs and renders the interface unresponsive. You must refresh the page and lose your changes. It should just show the error message / toast that the saving failed / something, and let you regain control of the interfac.e

**Comment by guerler** [comment] 2018-12-21 18:18
Can you share a workflow which causes that?

**Comment by guerler** [comment] 2018-12-26 20:47
This happens to any workflow with missing tools. It seems to be caused by #6741.

**Comment by mvdbeek** [comment] 2019-01-21 08:46
Should be fixed by https://github.com/galaxyproject/galaxy/pull/7227, please re-open if you see it again.

**Closed as completed by mvdbeek** 2019-01-21 08:46 UTC
Labels: kind/bug, area/UI-UX
