### ISSUE TITLE
(Permanently) deleting datasets has no (immediate) effect

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#14966] opened 2022-11-10 12:20 UTC
**Describe the bug**

If I (permanently) delete datasets from a history then a text `Processing operation ...` appears and stays for a while. Then the history is loaded again and still shows the data sets. The datasets are deleted after some while. 

https://user-images.githubusercontent.com/25689525/201086954-acf6ea32-8fed-4fa0-8fb8-5888942fc9e9.mp4

This is in particular confusing because the user needs to wait and thereby might expect a result.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: b709a19c5e

**To Reproduce**

See video.

**Expected behavior**

Datasets should be removed immediately .. it would be fine if removing the actual data from disk might need some time.

**Comment by davelopez** [comment] 2022-11-16 08:20
I'm trying to investigate if this is a backend or frontend issue. I think it might be a refresh issue on the client side since you can see in your video that after the `Processing...` message goes away your dataset count correctly changes from 172 to 170, so the backend should be fine.

Unfortunately, I can't reproduce it on https://usegalaxy.eu/ or locally. Can you help me debug it a bit by checking the following? :pray: 

1. Does this behavior happen systematically in every history or just in this particular one?

2. Can you check in the browser dev tools the contents of the requests immediately after the "bulk" operation request? The next requests should have those permanently deleted items with at least `deleted=True` on them.
![image](https://user-images.githubusercontent.com/46503462/202125992-f099a7d4-56a2-4bfa-a44e-52ca78681199.png)

**Comment by bernt-matthias** [comment] 2022-11-17 15:47
> Does this behavior happen systematically in every history or just in this particular one?

I checked another history and have seen the same behavior.

> Can you check in the browser dev tools the contents of the requests immediately after the "bulk" operation request? The next requests should have those permanently deleted items with at least deleted=True on them.

I did a few experiments. See videos below.


Funnily, the first try worked (so its not deterministic): 

https://user-images.githubusercontent.com/25689525/202490867-3a2a5754-072f-4a0c-8f53-77ae88feaac6.mp4

Same history different result (the request looks the same): 

https://user-images.githubusercontent.com/25689525/202490874-ca1558df-87ae-46b7-855a-7ada1874cf68.mp4

Different history (I felt like purging collections might be a good test :) .. the waiting text never disappeared .. request looks good to me

https://user-images.githubusercontent.com/25689525/202490876-1e45331b-944d-4fe0-9044-cc440d5d9220.mp4

Tried a simple delete of a single collection with the same result:

https://user-images.githubusercontent.com/25689525/202490880-d9055bb1-6974-4f5a-8e1c-d822030fabab.mp4

Finally I tested to purge single datasets .. same result as in the other history:

https://user-images.githubusercontent.com/25689525/202490886-5508417d-a5ab-4f4a-aa9c-5a49a1153e10.mp4

Hope this helps

**Comment by davelopez** [comment] 2022-11-17 17:30
Thanks a lot, this certainly helps!

> Funnily, the first try worked (so its not deterministic)

I need to investigate more in-depth, but this sounds like an issue synchronizing the client state. If you look closer, in the first video, you have 9 active datasets, they are correctly removed from the list but the count is still 9 so it is just the opposite error (before the dataset count was correctly updated but the datasets remained in the list...) :exploding_head: 

The `Processing...` message not going away is because the bulk operation is expecting a change in the history (basically a change of the update_time) but it's not happening.

It seems you don't have Celery enabled in your instance, I wonder if this could be the main difference between usegalaxy.eu and this one. The purge operation behaves slightly differently in that case.

**Comment by bernt-matthias** [comment] 2022-11-18 07:59
Indeed I have the default setting for 22.05 which seems to be no celery. Did not have time to configure this. Also docs listed in the config file do not mention celery at all

```
  # Offload long-running tasks to a Celery task queue. Activate this
  # only if you have setup a Celery worker for Galaxy. For details, see
  # https://docs.galaxyproject.org/en/master/admin/production.html
  #enable_celery_tasks: false
```

Will ask at the admin channel where this is...

**Comment by bgruening** [comment] 2022-11-22 16:44
@bernt-matthias can you reproduce that locally as well?

**Comment by bernt-matthias** [comment] 2022-11-22 22:55
You mean just `run.sh` on my laptop?

**Comment by bgruening** [comment] 2022-11-23 06:52
Yes.

**Comment by bernt-matthias** [comment] 2022-11-24 07:29
Wait. Is celery enabled by default on 22.05?

**Comment by davelopez** [comment] 2022-11-24 09:23
It shouldn't be enabled by default, check your `enable_celery_tasks` setting in `galaxy.yml`. I also tried locally without enabling celery and couldn't reproduce it either...

Any idea of what can be affecting this in your instance? missing or unordered responses? I'm kind of out of ideas... :disappointed:

**Comment by bernt-matthias** [comment] 2022-11-24 14:05
> It shouldn't be enabled by default, check your enable_celery_tasks setting in galaxy.yml. I also tried locally without enabling celery and couldn't reproduce it either...

I use the sample config, i.e. `enable_celery_tasks: false` is commented. 

But in the logs I see:

```
2022-11-24 15:04:44,018 INFO supervisord started with pid 2528181
2022-11-24 15:04:44,691 INFO spawned: 'celery' with pid 2528182
2022-11-24 15:04:44,694 INFO spawned: 'celery-beat' with pid 2528183
2022-11-24 15:04:44,698 INFO spawned: 'gunicorn' with pid 2528184
celery                           STARTING  
celery-beat                      STARTING  
gunicorn                         STARTING  

...

 -------------- celery@MOLSYB009 v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.15.0-52-generic-x86_64-with-glibc2.35 2022-11-24 15:04:52
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         galaxy:0x7fcd98e7d310
- ** ---------- .> transport:   sqlalchemy+sqlite:////home/berntm/projects/galaxy/database/control.sqlite
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (thread)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                .> galaxy.external  exchange=galaxy.external(direct) key=galaxy.external
                .> galaxy.internal  exchange=galaxy.internal(direct) key=galaxy.internal

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . galaxy.celery.tasks.change_datatype
  . galaxy.celery.tasks.cleanup_short_term_storage
  . galaxy.celery.tasks.export_history
  . galaxy.celery.tasks.fetch_data
  . galaxy.celery.tasks.finish_job
  . galaxy.celery.tasks.import_model_store
  . galaxy.celery.tasks.materialize
  . galaxy.celery.tasks.prepare_dataset_collection_download
  . galaxy.celery.tasks.prepare_history_content_download
  . galaxy.celery.tasks.prepare_history_download
  . galaxy.celery.tasks.prepare_invocation_download
  . galaxy.celery.tasks.prepare_pdf_download
  . galaxy.celery.tasks.prune_history_audit_table
  . galaxy.celery.tasks.purge_hda
  . galaxy.celery.tasks.recalculate_user_disk_usage
  . galaxy.celery.tasks.set_job_metadata
  . galaxy.celery.tasks.set_metadata
  . galaxy.celery.tasks.setup_fetch_data
  . galaxy.celery.tasks.write_history_content_to
  . galaxy.celery.tasks.write_history_to
  . galaxy.celery.tasks.write_invocation_to

[2022-11-24 15:04:52,283: DEBUG/MainProcess] | Worker: Starting Pool
[2022-11-24 15:04:52,284: DEBUG/MainProcess] ^-- substep ok
[2022-11-24 15:04:52,284: DEBUG/MainProcess] | Worker: Starting Consumer
[2022-11-24 15:04:52,284: DEBUG/MainProcess] | Consumer: Starting Connection
[2022-11-24 15:04:52,300: INFO/MainProcess] Connected to sqlalchemy+sqlite:////home/berntm/projects/galaxy/database/control.sqlite
[2022-11-24 15:04:52,301: DEBUG/MainProcess] ^-- substep ok
[2022-11-24 15:04:52,302: DEBUG/MainProcess] | Consumer: Starting Events
[2022-11-24 15:04:52,307: DEBUG/MainProcess] ^-- substep ok
[2022-11-24 15:04:52,307: DEBUG/MainProcess] | Consumer: Starting Tasks
[2022-11-24 15:04:52,370: DEBUG/MainProcess] ^-- substep ok
[2022-11-24 15:04:52,370: DEBUG/MainProcess] | Consumer: Starting Heart
[2022-11-24 15:04:52,370: DEBUG/MainProcess] ^-- substep ok
[2022-11-24 15:04:52,370: DEBUG/MainProcess] | Consumer: Starting event loop
[2022-11-24 15:04:52,372: INFO/MainProcess] celery@MOLSYB009 ready.
[2022-11-24 15:04:52,373: DEBUG/MainProcess] basic.qos: prefetch_count->8
```

Confusing ... 

> Any idea of what can be affecting this in your instance? missing or unordered responses? I'm kind of out of ideas... disappointed

My guess would be (randomly?) slow file access times (on our system all is on network filesystem .. which is sometimes quite slow).

**Comment by mvdbeek** [comment] 2022-11-24 14:34
No, enable_celery_tasks is not enabled by default. The commented avlue is always the default setting.

**Comment by bernt-matthias** [comment] 2022-11-24 15:57
That's what I thought @mvdbeek I tried with a fresh clone of Galaxy 

```bash
git clone https://github.com/galaxyproject/galaxy.git -b release_22.05
cd galaxy
virtualenv .venv
./run.sh
```

and still see the Celery related output shown above. So celery is enabled, by default, isn't it? Or am I mis-interpreting the log output?

**Comment by bernt-matthias** [comment] 2022-11-24 16:10
I also see the same output if I uncomment `enable_celery_tasks`

**Comment by davelopez** [comment] 2023-02-17 08:47
@bernt-matthias I just realise that this might be related to https://github.com/galaxyproject/galaxy/pull/15305.
I will close this assuming this was the issue, if you still can reproduce it with that fix, feel free to reopen it. Thanks!

**Closed as completed by davelopez** 2023-02-17 08:47 UTC

**Comment by bernt-matthias** [comment] 2023-02-17 08:49
Will do. Thanks a lot.
