### ISSUE TITLE
Main Tool Shed (MTS) has inactive Help and User pull-down menus

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1822] opened 2016-02-29 20:02 UTC
https://toolshed.g2.bx.psu.edu

Testing on OSX Chrome and Safari. @blankenberg also confirmed.

**Comment by davebx** [comment] 2016-02-29 20:04
@martenson is in the process of looking at this issue.

**Comment by martenson** [comment] 2016-02-29 20:11
dupe of https://github.com/galaxyproject/galaxy/issues/1525
hopefully fixed by https://github.com/galaxyproject/galaxy/pull/1823

**Closed as completed by martenson** 2016-02-29 20:11 UTC

**Comment by jennaj** [comment] 2016-03-01 17:26
Thx! Sorry for dup
