### ISSUE TITLE
Tool search returns old tool links when searching for old tools' name

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16145] opened 2023-05-24 13:00 UTC
The name of the tool with the id `Add_a_column1` has changed, it is now called “Compute on rows”, while previously it was called “Compute an expression on every row”. If you search for “Compute an expression on every row” (as the tutorial asks you to do) you get the older version. Old versions are often buggy, I think we should either not return them at all in the tool search, or we should return the newest tool in the lineage.

This happened in the context of smorgasbord, but I think this can be a tricky and frustrating gotcha.

**Comment by nsoranzo** [comment] 2023-05-24 13:33
Not sure I agree, one may want to specifically search for the old version. Given our focus on reproducibility, my feeling is this is better solved by updating the tutorial.

**Comment by mvdbeek** [comment] 2023-05-24 14:11
We can also turn this around and say it will now not be possible anymore to update a tool name, because then you will always be stuck with users finding old broken versions. That can't be our intention? It also didn't work that way before, I'm sure this wasn't an intentional change. I also don't follow the reproducibility argument, can you explain how returning the latest version of a tool breaks reproducibility?

**Comment by nsoranzo** [comment] 2023-05-24 14:26
Supposing that the tool have changed parameters/behaviour between versions, you may want to run the old version for whatever reason, and this would make it slightly more work, but maybe it's not that important.

I guess the main problem with the simple tool search is that searching for "Compute row" returns nothing.

**Comment by mvdbeek** [comment] 2023-05-24 14:32
Its not more steps than it used to be, and it's of course not feasible to rename the tool whenever parameters have changed, i am sure that's not what you're suggesting, but it does seem to follow from your concern?


I don't understand what you mean by searching for compute row returns nothing. We could easily collapse tools by lineage, like the backend search used to do, and what i suggested in the opening post.

**Comment by martenson** [comment] 2023-05-24 16:11
I like the idea of returning the newest tool in lineage. If the match was for older version we can make Clippy say "we loaded the newest version, if you want older stuff click here on the version switch".

**Comment by nsoranzo** [comment] 2023-05-25 18:47
>> I guess the main problem with the simple tool search is that searching for "Compute row" returns nothing.

> I don't understand what you mean by searching for compute row returns nothing.

E.g. on UseGalaxy.eu typing "Compute on rows" in the simplified tool search displays the "Compute on rows" tool (Add_a_column1 v 2.0), typing "Compute an expression on every row" displays the old v 1.4 (your issue here), but typing "Compute row" (which I think should match both and display the latest version) instead displays "No results found!".
That looks like a problem to me as well.

**Comment by hujambo-dunia** [comment] 2023-05-30 16:26
Yes - we could handle this on the frontend, just remember to add a method in the `client/src/components/Panels/utilities.js` that prevents older tools from showing - could be something like `filterMostRecent(tools)` or something similar.

**Comment by ahmedhamidawan** [comment] 2023-09-26 17:05
Fixed in https://github.com/galaxyproject/galaxy/pull/16290

(Alternative, improvable solution in https://github.com/galaxyproject/galaxy/pull/16238)

**Closed as completed by ahmedhamidawan** 2023-09-26 17:05 UTC
Labels: kind/bug, area/UI-UX, area/tools
