### ISSUE TITLE
Hidden datasets are annotated as unavailable to tools on tool forms at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3487] opened 2017-01-25 16:52 UTC
Example

Input with status "hidden". **Clarification**: the job will still run with the hidden input (for tools tested)
<img width="727" alt="hidden_dataset_unavailable" src="https://cloud.githubusercontent.com/assets/8999735/22300087/3d4339a4-e2db-11e6-8f05-a883ac224da2.png">

After unhiding
<img width="867" alt="hidden_changed_unhidden" src="https://cloud.githubusercontent.com/assets/8999735/22300140/642f288e-e2db-11e6-91d1-85eff82a96ba.png">

May be related to: https://github.com/galaxyproject/galaxy/issues/3481

ping @dannon @galaxyproject/guac

**Comment by jxtx** [comment] 2017-01-25 16:54
Is the current behavior not the correct one?

**Comment by dannon** [comment] 2017-01-25 16:55
@jennaj I think it's intentional that they're not available here.  #3481 is a real issue though, caused by us no longer populating the backbone collection with hidden datasets by default.

**Comment by guerler** [comment] 2017-01-25 17:02
Yes, this is the correct behavior but the info label "unavailable" is misleading. Tools can be re-run with hidden datasets if those datasets were used before and hidden after job completion. I will fix the label to make this more apparent.

**Comment by bgruening** [comment] 2017-01-25 17:20
"unavailable" should be just "hidden" isn't it?

**Comment by guerler** [comment] 2017-01-25 17:51
Right.

**Comment by jennaj** [comment] 2017-01-25 21:53
That is exactly what needs to be changed - eg. (unavailable) to (hidden). Title is misleading, I'll fix. Thanks!

**Comment by nsoranzo** [comment] 2017-01-30 15:53
Fixed in #3495.

**Closed as completed by nsoranzo** 2017-01-30 15:53 UTC
Labels: area/UI-UX, triage
