### ISSUE TITLE
lock down histories

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#9419] opened 2020-02-23 13:57 UTC
For projects like https://github.com/galaxyproject/SARS-CoV-2 it would be useful to lock-down histories and make them basically read-only and maybe add an extra step to prevent deletion.

This will help prevent executing tools into those histories or delete them or unshare them ...

ping @nekrut - useful?

**Comment by blankenberg** [comment] 2020-02-24 18:48
xref https://github.com/galaxyproject/galaxy/issues/1734

**Comment by hexylena** [comment] 2020-02-25 10:06
Duplicate of my issue from four years ago https://github.com/galaxyproject/galaxy/issues/1734 :)

**Closed as completed** 2020-08-04 16:06 UTC
Labels: kind/enhancement, area/histories
