### ISSUE TITLE
Performance issues with new run workflow form, improve load times

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/galaxy#3893] opened 2017-04-06 16:22 UTC
Hi everyone,

I've recently updated my Galaxy instance from version 16.07 to version 17.01 and I have multiple issues with the "Run" form !

- [ ]  Slow loading time for workflows with more than 25 steps

In 16.07 I have no issue to load the "Run" page of a 50+ steps workflow in just a few second.

Now, with the new version, I have to wait more than 15s in average for a workflow with 2 times less steps.

On the Chrome browser the page is just very slow to load but i got no crash if i don't click elsewhere on the interface (The page crash if I perform other actions at the same time).

On Firefox I directly get a "script not responding error" for the libs.bundled.js script.

A look in the Chrome development tools/console shows that the issue is on the script part, not the rendering part.

- [x]  The Name field of an "Input dataset" step is no longer displayed

You have to edit every existing workflow and rename the "Input dataset" step itself if you want your users to see which file is expected for every Input dataset.

The Name field of the "Input dataset" step is not displayed in the new "Run" form.

- [x]  Broken "Set at runtime" value "{'class': 'RuntimeValue'}" for some tools

For some tools, if i set a parameter on "Set at runtime" in the the workflow editor then, when i click the Run button, the "Run" form display a broken value "{'class': 'RuntimeValue'}" for this parameter.

I get this behavior for some tools (like some Qiime wrappers from the TTS) and not for the "shipped with Galaxy" tools i tried.

- [x]  Disappearing default values

Another issue is that the default value of a parameter is lost when you set it on "Set at runtime", save the workflow and run it. The text field where the user have to specify a value is empty instead of having a "gray" default value displayed.

Thanks in advance for your help :)

**Comment by arbernard** [comment] 2017-04-11 13:31
I have made some tests with various tools to find a pattern for point N°3.

It appears that the input field does not appear and is replaced by the "{'class': 'RuntimeValue'}" message in a very specific condition.

Indeed, this behavior only happens when a "param" tag of a type different than "data" (for example: type=text) have an "optiontal" attribute set to "true".

To reproduce this issue you have to:
- Create/edit a wrapper with a "param" of type "text" that possess an "optional" attribute set to "true"
     <param name="test" type="text" value="test" optional="true" label="" help="" />
- Create a new workflow
- Add your special tool into the workflow
- Save the workflow
- Run the workflow

The Run form should displat the "{'class': 'RuntimeValue'}" message just under the test parameter.

Hope this helps

**Comment by guerler** [comment] 2017-04-11 17:04
Yes, that helped a lot I am working on a fix for No. 3 now. Thanks a lot.

**Comment by guerler** [comment] 2017-04-11 17:15
Is No. 2 the same as #3672? If not can you help me to reproduce that one too. Thanks a lot for catching these things and helping me to solve them.

**Comment by arbernard** [comment] 2017-04-12 06:41
@guerler: Yes, It looks like No. 2 is the same issue than https://github.com/galaxyproject/galaxy/issues/3672 .

Great to hear that you are working on No. 3 ! So it is indeed a bug or is it that non "data" param can no longer have an optional attribute ?

Any idea for No. 4 ?

**Comment by arbernard** [comment] 2017-04-12 08:07
I found another critical issue with the "Set at Runtime" feature in 17.01:

During workflow edition, if you "Set at runtime" a parameter which is a drop-down menu, then the value displayed in the "Run" form is always the first one, not the selected=true value.

That's a really critical issue since it can make end users execute workflows with improper parameters without even knowing it :(

**Comment by guerler** [comment] 2017-04-12 12:44
This is the same as No. 4. It is related to default values. If a parameter is specified to be "Set at Runtime" there is no value for it until the value has been set at runtime. I will look into it.

**Comment by guerler** [comment] 2017-08-24 18:46
Duplicate of #4286.

**Closed as completed by guerler** 2017-08-24 18:46 UTC
