### ISSUE TITLE
Invisible noodles in workflows (due to missing tools) causes confusion

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11501] opened 2021-02-26 14:28 UTC
There's an invisible noodle due to this missing tool:

![image](https://user-images.githubusercontent.com/458683/109311999-c9959780-7846-11eb-8362-132048839cd2.png)

Even after removing the tool, the invisible noodle is still there!

![image](https://user-images.githubusercontent.com/458683/109312032-d3b79600-7846-11eb-993f-1fb68a2e4e66.png)

And I can't connect anything to it which looks like a lie (as a user)

![image](https://user-images.githubusercontent.com/458683/109312364-4163c200-7847-11eb-9ff7-acf3a9a038b2.png)

It would be great if the noodles could be shown (even if a broken tool, you still know some inputs/outputs go there.) Or if removing the broken tool removed it's downstream connections?

**Comment by nsoranzo** [comment] 2021-02-26 18:40
> It would be great if the noodles could be shown (even if a broken tool, you still know some inputs/outputs go there.) Or if removing the broken tool removed it's downstream connections?

I agree the noodles should still be attached to the broken tool and shown, but for the second part I'd argue that it would be nice that they stay there after you remove the tool, so that it's easier to replace it with another tool and reconnect the hanging noodles.

**Comment by mvdbeek** [comment] 2021-03-18 21:21
Pretty sure the first part is fixed now (no more floating disconnected noodles). We do however lose connections ... maybe we can call that a feature request now 😆

**Comment by mvdbeek** [comment] 2021-03-19 18:19
OK, the second part is a duplicate of https://github.com/galaxyproject/galaxy/issues/7141.

**Closed as completed by mvdbeek** 2021-03-19 18:19 UTC
Labels: kind/bug, area/UI-UX, area/workflows
