### ISSUE TITLE
Share link edit icon doesn't work after generating share link

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#7868] opened 2019-05-01 18:24 UTC
per @jennaj -- On main and eu, after generating a share link, if I click on the little pencil to edit the link name, the middle pane flips to being blank. This is 100% reproducible across many histories, both servers.

xref #7787

**Comment by WilliamHolden** [comment] 2019-05-09 19:59
Hey @dannon @jennaj, is this still an issue? I'm having trouble reproducing.

**Comment by dannon** [comment] 2019-05-09 20:14
@WilliamHolden The description was right, but the title was incorrect here.  It's not the dataset attribute pencil icon but the one in the share link.

![sharebug](https://user-images.githubusercontent.com/155398/57483780-8c2cd800-7275-11e9-9741-1e21f78ef069.gif)

**Comment by nsoranzo** [comment] 2019-05-09 21:19
Seems a duplicate of #7893 (or viceversa).

**Comment by jennaj** [comment] 2019-05-09 21:38
Yes, are duplicates. I closed the other already https://github.com/galaxyproject/galaxy/issues/7787 and it is linked here. 

@WilliamHolden Let's use the https://github.com/galaxyproject/galaxy/issues/7893 ticket and close others. They are all linked together now, so which to keep doesn't really matter, but better to have just one.

I am assuming that whatever fixes are needed would apply to all of these (seems so). If not, can reopen/clarify.

**Comment by dannon** [comment] 2019-05-09 21:39
The other one was actually the duplicate, but it doesn't matter :)  (thanks for getting it all linked up)

**Closed as completed by jennaj** 2019-05-09 21:38 UTC
Labels: kind/bug, area/UI-UX

**Comment by jennaj** [comment] 2019-05-09 21:41
Agree, was giving @martenson extra bug-hunting credit points :) haha
