### ISSUE TITLE
Minor UI bug: Show history panel button disappears after hiding history panel

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/galaxy#14394] opened 2022-08-03 09:12 UTC
**Describe the bug**
After hiding the history panel using the button shown at the bottom right corner, this button disappears and only way to bring back the history panel is to refresh the page.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: https://usegalaxy.org/
Commit: Galaxy version 22.05.rc1, commit [b0a526da8d4f02d0d4468ba49c4501af727138a0](https://github.com/galaxyproject/galaxy/commit/b0a526da8d4f02d0d4468ba49c4501af727138a0)

**To Reproduce**
Steps to reproduce the behavior (tested on Google Chrome but not on Mozilla):
1. Go to https://usegalaxy.org/
2. Click on hide history panel button
3. The button to bring history panel disappears
4. The page needs to be refreshed to bring back the history panel

**Expected behavior**
History show/hide panel button should always be visible. Similar feature for tool panel works correctly.

**Screenshots**
![usegalaxy_org_history](https://user-images.githubusercontent.com/3022518/182570881-749447cb-aaaf-416b-9f64-ce63abfb915c.png)

Thank you!

**Comment by guerler** [comment] 2022-08-04 18:14
Thanks for reporting this issue. This issue existed for awhile, but should now have been resolved in dev with the new client architecture. Can you verify that the problem is resolved in dev? Thanks again.

**Comment by guerler** [comment] 2022-08-05 20:33
Please re-open if this issue still exists in dev.

**Closed as completed by guerler** 2022-08-05 20:33 UTC
Labels: kind/bug, area/UI-UX

**Comment by anuprulez** [comment] 2022-08-19 13:23
It is fixed, thanks :)
