### ISSUE TITLE
Improve the user experience when using single datasets that are part of a collection (e.g. as inputs to tools or other collections)

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2178] opened 2016-04-15 18:38 UTC
If a tool is run on a collection and outputs a collection, the individual output items are not available to be selected when running a tool.

**Comment by lparsons** [comment] 2016-04-18 14:55
Turns out this is actually possible, but not necessarily intuitive. The datasets are "hidden" and the user must first click on "hidden" to display the datasets before they are able to select them and add them to a collection. By clicking "Unhide" for each dataset, users are able to select these as input for tools.

So perhaps this issue should be modified to reflect the desire for an improved interface when dealing with datasets in collections. Like a sort of "folder" interface when selecting datasets. For that matter, allowing collections to be "unfolded" (e.g. with a little arrow that turns from pointing sideways to down) in a history might be nice as well.

**Comment by jmchilton** [comment] 2017-09-27 14:55
Still an issue but I'm closing as a duplicate of https://github.com/galaxyproject/galaxy/issues/740. That issue covers this ground also I think and has more comments/links etc. Thanks for creating the issue though @lparsons.

**Closed as completed by jmchilton** 2017-09-27 14:55 UTC
