### ISSUE TITLE
View console output while job is running.

### ISSUE THREAD

**Issue by gecage952** [galaxyproject/galaxy#15504] opened 2023-02-03 21:10 UTC
One feature that that would be useful for users in my organization would be the ability to see Std Out and Std error live **while a job is running.** I know currently, you can access this after the job is finished, and you can see the job output update by clicking on the eye symbol, but this would expand that functionality. We've thought about maybe doing an implementation ourselves, but we wanted to get some feedback from here first.

Just a mock screenshot of the rough idea.
![Screenshot from 2023-01-31 16-56-45](https://user-images.githubusercontent.com/30890419/216710842-97f04847-833e-4fbe-83cd-73c93e5a9b1a.png)

**Comment by martenson** [comment] 2023-02-04 01:12
Given the nature of Galaxy's architecture especially focusing on leveraging distributed compute resources streaming back job's stdout and stderr is hard. This feature has potential to be awesome and has been wished for many times but the implementation is estimated to be costly and imperfect. @jmchilton and @mvdbeek may give you more detailed takes.

Please be wary that spending effort towards this goal without broad agreement on the direction is fairly risky.

**Comment by hexylena** [comment] 2023-02-04 14:25
Duplicate of https://github.com/galaxyproject/galaxy/issues/2332

**Closed as completed by hexylena** 2023-02-04 14:25 UTC
