### ISSUE TITLE
Integron_finder software error 

### ISSUE THREAD

**Issue by nwalas** [galaxyproject/galaxy#11120] opened 2021-01-13 16:59 UTC
Hello, 

I am using the online galaxy interface for integron_finder, but when I run my fasta file I get a failed return with the following error.

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/mount/gensoft2/exe/Integron_Finder/1.5.1/bin/integron_finder", line 1608, in <module>
    alphabet=Seq.IUPAC.unambiguous_dna)
  File "/local/gensoft2/adm/lib/python2.7/site-packages/

This seems to be an issue with the software. How can this be fixed?

Thank you, 
Niko

**Comment by fmareuil** [comment] 2021-01-14 16:32
Hello,
I can answer your question. This is not a bug on the galaxyproject, it is specific for a galaxy@pasteur's tool.
I answered you by email.
Best Regard,
Fabien (galaxy@pasteur admin)

**Comment by dannon** [comment] 2021-01-14 16:38
@fmareuil Thanks!  I'll close this out.

**Closed as completed by dannon** 2021-01-14 16:38 UTC

**Comment by nwalas** [comment] 2021-01-14 16:45
Hi Fabien, 

I haven’t received your answer by email. Just want to confirm you sent it?

Thanks, 
Niko
