### ISSUE TITLE
discrepancy for handling of untouched output files

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#9287] opened 2020-01-30 18:06 UTC
Currently there is a discrepancy in the output file handling if  the tool does not touch the output for the cases:

1. outputs go to the working dir or 
2. if they are written directly to `database/files`:

This may happen for filters that remove everything and simply don't write if everything is removed.

In case 

1. the jobrunner fails the job because it can not find the file (log message below)
2. an empty file sits in `database/files` and the tool runs successfully.

One of these cases is a bug. On first thought my impression was that case 1 is the bug and the job should not fail. But, consider for instance a case where the output format is determined by the input (`format_source="input"`) and input can be fastq / fastq.gz. Then in the fastq.gz file an empty file would lead to problems. 

So currently I would say the problem is case 2.

Log message:
```
fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/work/songalax/galaxy/database/jobs_directory/056/56052/galaxy_dataset_213175.dat'
```

Note, in the case where I observed this I reported upstream: https://github.com/benjjneb/dada2/issues/931

**Comment by mvdbeek** [comment] 2020-02-03 14:35
Duplicate of https://github.com/galaxyproject/galaxy/issues/8743 ?

**Comment by bernt-matthias** [comment] 2020-02-03 16:01
Seems so. Even if the reported error message is different.

**Comment by jmchilton** [comment] 2020-10-20 21:01
Closing as duplicate, thanks for the report.

**Closed as completed by jmchilton** 2020-10-20 21:01 UTC
Labels: kind/bug
