### ISSUE TITLE
Biomart tool fails

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#13824] opened 2022-04-28 10:23 UTC
**Describe the bug**
When I try to download info from biomartI get an error on the page:
![image](https://user-images.githubusercontent.com/30404086/165731464-61c60fd1-f5d9-427d-af82-8364511ced42.png)
and when I come back to my history I get a job which stays grey.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)
usegalaxy.eu
```
version_major | "21.09"
version_minor | "1.dev0"
```

**To Reproduce**
1. Click on the "Biomart Ensembl server" tool
2. Select Ensembl Genes 106 - Chicken genes
3. Click on results
4. Click on Go

**Expected behavior**
A dataset with chicken genes in galaxy

**Comment by nsoranzo** [comment] 2022-04-28 12:23
Duplicate of https://github.com/galaxyproject/galaxy/issues/13455

**Closed as completed by nsoranzo** 2022-04-28 12:23 UTC

**Comment by lldelisle** [comment] 2022-04-28 12:26
Thanks, sorry for that.

**Comment by lldelisle** [comment] 2022-04-28 14:20
Thanks
