### ISSUE TITLE
Configuration store bugs

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#16559] opened 2023-08-16 09:13 UTC
Related to #16514
- Toolshed menu item is not shown in the admin panel

https://github.com/galaxyproject/galaxy/assets/8046843/aaaf7aa5-9dfc-4dd7-8abc-18d5a7552308

- Extract workflow from history raises a pinia error

![image](https://github.com/galaxyproject/galaxy/assets/8046843/ab489fc6-be43-40c5-9671-d47ac35b55fd)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: latest dev branch
Commit: 983bbfb33e51992101945950f25d14d677e8269a

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davelopez** [comment] 2023-08-16 11:15
Thanks for the catch!
I think the first point is a duplicate of #16544
I'll try to fix both.

**Closed as completed** 2023-08-17 17:35 UTC
Labels: kind/bug, area/UI-UX
