### ISSUE TITLE
 Downloading multiple Datasets at once from History.

### ISSUE THREAD

**Issue by mhabsaoui** [galaxyproject/galaxy#4280] opened 2017-07-05 14:55 UTC
Hi,

Is it already possible to download multiple Datasets at once from History ?
If not, apart from being able to send results datasets to Data libraries or exporting/sharing Histories, can it be made through the "For all selected" by adding a 'Download Datasets/Datacollections' option in the menu as follow :

![image](https://user-images.githubusercontent.com/18755135/27858159-736407f8-6174-11e7-9c5c-0d5b338cea34.png)

Thanks.

**Comment by nsoranzo** [comment] 2017-07-05 15:16
Duplicate of #3195.

**Closed as completed by nsoranzo** 2017-07-05 15:16 UTC
