### ISSUE TITLE
unable to login to test toolshed TS2.0

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17035] opened 2023-11-15 17:58 UTC
3 browsers, 2 accounts

`{"err_msg":"Wrong session token found, denying request.","err_code":403005}`

**Comment by mvdbeek** [comment] 2023-11-16 14:15
Duplicate of https://github.com/galaxyproject/galaxy/issues/16842

**Closed as not planned by mvdbeek** 2023-11-16 14:15 UTC
Labels: kind/bug, area/toolshed
