### ISSUE TITLE
Two separate Trackster issues (with fixes)

### ISSUE THREAD

**Issue by kaukrise** [galaxyproject/galaxy#9205] opened 2020-01-13 08:42 UTC
Hi Galaxy developers,

first of all, I love what you have achieved with this project, your work is much appreciated.
In the process of testing a new Galaxy installation on our local cluster, I encountered several issues with the Trackster visualisation, two of which also seem to be present on usegalaxy.org:

1. **The genome navigation bar is not visible**. To reproduce, simply open any Trackster visualisation. I saw that the `unified-panel-body` `div` has an `overflow: visible` style attribute, which is supposed to make the navigation bar visible outside of its `div`. This is applied [here](https://github.com/galaxyproject/galaxy/blob/d6de316b5392d5d62a599b08a08c25fbd93d0dac/client/galaxy/scripts/viz/trackster/tracks.js#L1005). However, the default CSS stylesheet overrides this with an `!important` flag.

2. **Dataset history is not loading when adding a new track**. To reproduce, click the "add track" button in a Trackster visualisation - you will see the loading wheel spin but never fully load. The logs reveal that this is caused by an `sqlalchemy` bug which requires [this statement](https://github.com/galaxyproject/galaxy/blob/d6de316b5392d5d62a599b08a08c25fbd93d0dac/lib/galaxy/webapps/galaxy/controllers/visualization.py#L47) to be wrapped in `text()`.

The fixes are fairly straightforward in both cases, and I would be happy to submit pull requests for both. I read the contribution guidelines, so would it be acceptable if I created two separate pull requests, each based on the `20.01` branch? Or would you prefer them to be based on `dev`?

Thank you!

Kai

**Comment by nsoranzo** [comment] 2020-01-14 03:03
@kaukrise Thanks for the bug reports and the offer to contribute, much appreciated!
You surely can open pull requests against the (yet unreleased) release_20.01 branch, or even release_19.05 or release_19.09, which are the 2 presently supported releases (if the issue is present there too).

**Comment by dannon** [comment] 2020-01-14 20:15
Thanks for both of these fixes @kaukrise.  They've both been merged and merged forward through 20.01 to dev as well.

**Closed as completed** 2020-01-14 20:15 UTC

**Comment by kaukrise** [comment] 2020-01-15 07:07
Thank you guys, that was incredibly quick!
