### ISSUE TITLE
Selecting all datasets in the history only selects those shown on the current page

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#11242] opened 2021-01-28 10:29 UTC
If I upload a large number of datasets, e.g. 1000, they will be shown in the history on multiple pages. If I now want to perform 'operations on multiple datasets' (e.g. build a collection) and want to use all datasets I've just uploaded, I click on 'All'. Unfortunately, it seems this only selects the datasets on the current page, whereas I expect that 'All' should really include all datasets in the histories, whether they're on the current page or not.

**Comment by hexylena** [comment] 2021-01-28 10:51
Duplicate of https://github.com/galaxyproject/galaxy/issues/4350 which @nekrut identified as a "major issue"

**Closed as completed by hexylena** 2021-01-28 10:51 UTC
