### ISSUE TITLE
Configuration API returns unexpected values for by_host option

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#16454] opened 2023-07-25 00:33 UTC
**Describe the bug**
`/api/configuration` does not return the correct themes, if the themes are set per host.
This behavior leads to the themes not being selectable for users on subdomain configurations.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 - dev

**To Reproduce**
1. Set `themes_config_file_by_host` in the galaxy configuration to two different hosts. `localhost` and `127.0.0.1` can be used for local testing
2. Create two different theme files for these hosts
3. Run galaxy
4. Go to each of these URLs, and see that the default theme for each configuration is applied
5. call `/api/configuration` for each of these URLs, and observe that the themes do not match the set, or displayed themes

**Expected behavior**
`/api/configuration` reflects the correct configuration per host

**Additional Context**
The configuration inlined in the client html behaves as expected (see #16455), which is why the default theme is applied correctly.

**Comment by davelopez** [comment] 2023-08-17 10:17
Sorry I forgot I assigned myself to this one :man_facepalming: 

I'm just checking 23.0 branch and I couldn't find `themes_config_file_by_host` in the configuration schema. Is this an intended *undocumented* configuration option? or should we add it to the config schema?

**Comment by bgruening** [comment] 2023-08-17 10:21
It is themes_config_file the by host extension is a feature that is enabled if you want by host configurations.

https://github.com/galaxyproject/galaxy/pull/12328

**Comment by davelopez** [comment] 2023-08-17 10:26
Ouch, I didn't know that... I guess those dynamic config options will need to be taken into account in the future Pydantic model https://github.com/galaxyproject/galaxy/pull/16518

**Comment by mvdbeek** [comment] 2023-08-17 12:42
In the response model you shouldn't know about `per_` and just return the correct one, but yes, the parsing needs to account for these.

**Comment by ElectronicBlueberry** [comment] 2023-08-17 16:27
It is confirmed to be broken with proper subdomains as well.

**Comment by davelopez** [comment] 2023-08-18 07:56
Interesting... Hmmm, the logic itself looks fine, it would be useful to see what is in the `request.host` variable for those sub-domains. If the issue is still the same and it resolves them to the same IP in the ASGI request, then we probably need to use another way of discriminating the host.

**Comment by mvdbeek** [comment] 2023-08-18 08:40
The solution is probably somewhere in the ASGI to WSGI middleware, if it works on old-style request objects.

**Comment by mvdbeek** [comment] 2023-08-18 09:07
yep, it's in the host header, the logic in the webob.Request class is this (`_host__get` is a property):

```python
    def _host__get(self):
        """Host name provided in HTTP_HOST, with fall-back to SERVER_NAME"""
        if 'HTTP_HOST' in self.environ:
            return self.environ['HTTP_HOST']
        else:
            return '%(SERVER_NAME)s:%(SERVER_PORT)s' % self.environ
```
and the logic in the middleware is this:

```
    # Go through headers and make them into environ entries
    for name, value in scope.get("headers", []):
        name = name.decode("latin1")
        if name == "content-length":
            corrected_name = "CONTENT_LENGTH"
        elif name == "content-type":
            corrected_name = "CONTENT_TYPE"
        else:
            corrected_name = f"HTTP_{name}".upper().replace("-", "_")
```
we could do the same, or we could use `request.base_url.netloc`.

**Comment by davelopez** [comment] 2023-08-18 09:46
Definitely a big bug... :sweat: 
I think #16574 will return the correct host now. I tested it with the themes and it works like the old-style request.

**Comment by davelopez** [comment] 2023-08-21 08:23
Should be fixed by https://github.com/galaxyproject/galaxy/pull/16574

**Closed as completed by davelopez** 2023-08-21 08:23 UTC
Labels: kind/bug, area/backend
