### ISSUE TITLE
R installations possibly broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#919] opened 2015-10-14 22:44 UTC
details here: https://github.com/galaxyproject/galaxy/pull/893#commitcomment-13766844

ping @yhoogstrate @mvdbeek @bgruening @jmchilton

**Comment by bgruening** [comment] 2015-10-15 06:41
working on this ...
Potential fix here: https://github.com/galaxyproject/galaxy/compare/dev...bgruening:R_return?expand=1
Just want to search for more test computers with different R versions and OS ...
R is not really portable and error handling seems to be very tricky :(

**Comment by nsoranzo** [comment] 2015-10-15 11:42
@bgruening @yhoogstrate Your fix is wrong, it will return 0 also if `Rscript` fails for a random reason. The original problem is with the syntax of the `error` parameter of `tryCatch`. Can you test if this commit fixes the problem for you:

https://github.com/nsoranzo/galaxy/commit/73ca4c75ee03169d0430d6340808adc24d7084d2

It works correctly for me on the command line.

**Comment by bgruening** [comment] 2015-10-15 11:49
@nsoranzo for some reason the tryCatch is not working for all users.
Please see the latest discussion here:
https://github.com/bgruening/galaxy/pull/8

Including a new idea using Python to catch the error.

**Comment by nsoranzo** [comment] 2015-10-15 12:02
I guess `tryCatch` was not working because of the problem fixed in nsoranzo@73ca4c7 . I think my solution is less hacky and does not rely on grepping the Rscript stdout. I'm doing more testing now.

**Comment by bgruening** [comment] 2015-10-15 12:05
@nsoranzo even the old version was working for me in one R version :)
If you think this works for every R version including R2 than I'm happy to take this one.

**Comment by bgruening** [comment] 2015-10-15 12:13
This is what I get:

```
root@4e0ee2d18014:/galaxy-central# R --version
R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

root@4e0ee2d18014:/galaxy-central# Rscript -e "tryCatch({ install.packages(c('BiocGenerics_0.14.0.tar.gz-'), lib = '/galaxy-central/tool_deps/deseq2/1.8.2/iuc/package_deseq2_1_8_2/00b14423d00f', repos=NULL, dependencies=FALSE) }, error = function(e) { print(e); quit(status = 1) } )"
Warning: invalid package ‘BiocGenerics_0.14.0.tar.gz-’
Error: ERROR: no packages specified
Warning message:
In install.packages(c("BiocGenerics_0.14.0.tar.gz-"), lib = "/galaxy-central/tool_deps/deseq2/1.8.2/iuc/package_deseq2_1_8_2/00b14423d00f",  :
  installation of package ‘BiocGenerics_0.14.0.tar.gz-’ had non-zero exit status
root@4e0ee2d18014:/galaxy-central# echo $?
0
```

**Comment by yhoogstrate** [comment] 2015-10-15 13:24
```
$ R --version
R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.
```

Test 1: correct package, incorrect destination:

```
$ Rscript -e "tryCatch({ install.packages(c('BiocGenerics_0.14.0.tar.gz'), lib = '/dev/null', repos=NULL, dependencies=FALSE) }, error = function(e) { print(e); quit(status = 1) } )"
Warning in install.packages(c("BiocGenerics_0.14.0.tar.gz"), lib = "/dev/null",  :
  'lib = "/dev/null"' is not writable
<simpleError in install.packages(c("BiocGenerics_0.14.0.tar.gz"), lib = "/dev/null",     repos = NULL, dependencies = FALSE): unable to install packages>
$ echo $?
1
```

Test 2: incorrect package, correct destination:

```
$ Rscript -e "tryCatch({ install.packages(c('/dev/null'), lib = '/tmp/deseq2/inst', repos=NULL, dependencies=FALSE) }, error = function(e) { print(e); quit(status = 1) } )"
ERROR: cannot extract package from ‘/dev/null’
Warning message:
In install.packages(c("/dev/null"), lib = "/tmp/deseq2/inst", repos = NULL,  :
  installation of package ‘/dev/null’ had non-zero exit status
$ echo $?
0
```

Edit
Test 3: corrupt .tar.gz file, correct destination:

```
$ Rscript -e "tryCatch({ install.packages(c('Bio2.tar.gz'), lib = '/tmp/deseq2/inst2', repos=NULL, dependencies=FALSE) }, error = function(e) { print(e); quit(status = 1) } )"
Error in untar2(tarfile, files, list, exdir, restore_times) : 
  incomplete block on file
Warning message:
In install.packages(c("Bio2.tar.gz"), lib = "/tmp/deseq2/inst2",  :
  installation of package ‘Bio2.tar.gz’ had non-zero exit status
$ echo $?
0
```

**Comment by nsoranzo** [comment] 2015-10-15 13:27
Yep, it looks like an invalid package name raise a warning instead of an error. Should we exit with `status = 1` also for warnings?

**Comment by bgruening** [comment] 2015-10-15 13:53
@nsoranzo I haven't done this because I fear that during compilations there are a lot of warnings.

**Comment by nsoranzo** [comment] 2015-10-15 14:11
Should be fixed by https://github.com/nsoranzo/galaxy/commit/f666b05fdae5aec59c3c1ddc209a8eb0cec9450f

**Comment by yhoogstrate** [comment] 2015-10-15 14:19
@nsoranzo `if ( grep('had non-zero exit status', as.character(w))` Pure ownage. Shame on us @bgruening :laughing: 

The three tests cases I wrote in the comment above work currectly using https://github.com/nsoranzo/galaxy/commit/f666b05fdae5aec59c3c1ddc209a8eb0cec9450f

**Comment by bgruening** [comment] 2015-10-15 15:51
@nsoranzo your last one works for all of my examples. You probably want to include a few more strings to grep for, as shown by @yhoogstrate. Not sure if all are errors or a few of them are warnings.
Also we should consider that we need to add more filters later if R changes the error messages.

Please decide yourself if you want to have this one-liner or if we want to create a Python template without tryCatch(). The grep functions seems to be stable since 2.11 so this could be a valid solution.

**Comment by nsoranzo** [comment] 2015-10-15 16:02
@yhoogstrate How can I reproduce `unable to install packages` and `Execution halted` errors/warnings?

**Comment by yhoogstrate** [comment] 2015-10-16 06:41
@nsoranzo 

```
$ Rscript -e "install.packages(c('BiocGenerics_0.14.0.tar.gz'),lib='/dev/null', repos=NULL, dependencies=FALSE)" 
Warning in install.packages(c("BiocGenerics_0.14.0.tar.gz"), lib = "/dev/null",  :
  'lib = "/dev/null"' is not writable
Error in install.packages(c("BiocGenerics_0.14.0.tar.gz"), lib = "/dev/null",  : 
  unable to install packages
Execution halted
```

This makes me realize that your grep should not be able to capture this warning, but it still returns an error. I think we should look a bit closer into it, unless I made a mistake in copy pasting:

```
$ Rscript -e "tryCatch( { install.packages(c('BiocGenerics_0.14.0.tar.gz'), lib = '/dev/null', repos = NULL, dependencies = FALSE) }, error = function(e) { print('--Error--'); quit(status = 1) }, warning = function(w) { if ( grep('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZz', as.character(w)) ) { print('--Warning--'); quit(status = 1) } } )"
Error in if (grep("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZz", as.character(w))) { : 
  argument is of length zero
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by nsoranzo** [comment] 2015-10-16 10:54
@yhoogstrate The problem is that I should have used `grepl` instead of `grep` (which returns an empty vector if there is no match). It should be finally fixed with https://github.com/nsoranzo/galaxy/commit/c9294a6ec9270490d78b79fb3a615ed30b477650 , where I also added all warnings found in the `install.packages()` source code.

**Comment by yhoogstrate** [comment] 2015-10-16 11:32
@nsoranzo Thanks, it works here. I think you should make a PR and in the meantime we should test the packages within:

package_dexseq_1_14
package_deseq_2_8_2
package_r_ggplot2_0_9_3
package_r_edger_3_11_0

**Comment by yhoogstrate** [comment] 2015-10-16 12:59
I got this one in dexseq:
```
* installing *source* package ‘Cairo’ ...
** package ‘Cairo’ successfully unpacked and MD5 sums checked
configure: error: Cannot use cairo-ft backend, although cairo claims it is working. Please check your caito installation and/or update cairo if necessary or set CAIRO_CFLAGS/CAIRO_LIBS accordingly.
ERROR: configuration failed for package ‘Cairo’
```
I am not sure whether it's your PR though

**Closed as completed** 2015-10-19 13:34 UTC
Labels: kind/bug

**Comment by martenson** [comment] 2015-10-19 14:37
Awesome, thank you guys!
