### ISSUE TITLE
WF editor: "Add connection to module" not working for conditionals

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12588] opened 2021-09-29 07:48 UTC
**Describe the bug**

Not sure whether this is intentional or not, but In 21.09 the workflow editor offers "Add connection to module" (<->) also for outer conditional params.
Clicking on <-> for such a param, however, does not seem to have any effect except making the param unconfigurable.
No new workflow step input is appearing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
Example tools where this can be seen are:
- https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/compose_text_param/compose_text_param/0.1.1

  <-> Choose the type of parameter for this field

- https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.4.2+galaxy0

  <-> Is this single or paired library

**Additional context**
Discovered during 21.09 release testing

**Comment by mvdbeek** [comment] 2021-09-29 08:03
That looks like a bug to me. We should probably not allow workflow setting parameters for a conditional, since we don't have a way to define parameters for the different `<when>` cases a conditional might allow. I just cross-checked and 21.05 also shows this. I'll leave this at 21.09, this shouldn't be too hard to fix. @guerler can you also take a look at this ?

**Comment by wm75** [comment] 2021-09-29 08:04
> I just cross-checked and 21.05 also shows this.

Interesting. Not seeing it on .eu

**Comment by mvdbeek** [comment] 2021-09-29 08:07
I did check it on .eu as well 😆

**Comment by mvdbeek** [comment] 2021-09-29 08:08
Nevermind, wrong tab, was checking on .org ... yes, that is a regression in 21.09

**Comment by mvdbeek** [comment] 2021-09-30 11:52
Fixed in https://github.com/galaxyproject/galaxy/pull/12591

**Closed as completed by mvdbeek** 2021-09-30 11:52 UTC
Labels: kind/bug, area/UI-UX
