### ISSUE TITLE
API key page reveals key too easily

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#18587] opened 2024-07-23 09:55 UTC
**Describe the bug**

On /user/api_key the current API key gets revealed as soon as the mouse touches any part of the input group there, including e.g. the Copy button.

This makes it impossible to copy the API key during presentations or hover over the button for screenshots.

**Galaxy Version and/or server at which you observed the bug**
all usegalaxy.* instances

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**Expected behavior**
Ideally, there should be a dedicated eye icon to reveal the key or the key icon at the left could have that function.
At the very least, the buttons to the right of the key (copy and trash shouldn't trigger the function).

**Comment by davelopez** [comment] 2024-07-23 10:11
Duplicate of #17936

@itisAliRH can you have a look? you got #17936 assigned and you may have forgotten :)

**Comment by dannon** [comment] 2024-07-23 14:53
Closing this as duplicate, @itisAliRH is on it.

**Closed as completed by dannon** 2024-07-23 14:53 UTC
Labels: area/UI-UX
