### ISSUE TITLE
galaxy won't accept non-annotated .gff file [need assistance with annotating it (featurecounts)]

### ISSUE THREAD

**Issue by katuff24** [galaxyproject/galaxy#16779] opened 2023-10-03 17:48 UTC
hello everyone,

does anyone happen to know where I can find an annotated .gff file for saccharomyces cerevisiae, strand 1278b? I am trying to do feature counts on galaxy but the .gff file I am using is not annotated and I keep getting this error

 "ERROR: failed to find the gene identifier attribute in the 9th column of the provided GTF file.
The specified gene identifier attribute is 'gene_id' 
An example of attributes included in your GTF annotation is 'exon;'."

please let me know how I can fix this!

Thank you ;)

**Comment by mvdbeek** [comment] 2023-10-05 02:02
Duplicate of https://github.com/galaxyproject/tools-iuc/issues/5518

**Closed as completed by mvdbeek** 2023-10-05 02:02 UTC
