### ISSUE TITLE
file sniff does not work on a MacBook

### ISSUE THREAD

**Issue by SergeyYakubov** [galaxyproject/galaxy#14381] opened 2022-07-27 16:27 UTC
**Describe the bug**

File upload fails with an error `'NoneType' object has no attribute 'split'` on local Galaxy instance deployed on a Mac

(macOS Monterey Version 12.4, Chip Apple M1 Pro)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (22.05, version_minor:rc1)
Commit: (8b6030f67e62733afb6ae3bb2dd58cc7292e3104)

**To Reproduce**
1. Run Galaxy
2. Try uploading a file
3. See error

**Expected behavior**

file upload should work

**Additional context**

after some debugging, the problem seems to be in `import pylibmagic`[line](https://github.com/galaxyproject/galaxy/blob/e383e593e0d4e36c534a5ef9831bd7c44b023aa2/lib/galaxy/datatypes/sniff.py#L40
)

commenting this line out (and installing libmagic via e.g. brew if it is not there yet) removes the problem. So, apparently pylibmagic package for this configuration (M1?) is not correct. Had this problem on two machines now.

**Comment by dannon** [comment] 2022-07-27 16:30
Sorry you ran into this issue; you're correct it only affects the m1 architecture.  A fix for this will be tracked in this ticket here:  #14006

**Comment by mvdbeek** [comment] 2022-08-04 16:46
Duplicate of https://github.com/galaxyproject/galaxy/issues/14006

**Closed as completed by mvdbeek** 2022-08-04 16:46 UTC
