### ISSUE TITLE
Workflow : Jobs fail to be scheduled if the outputs are given duplicated tags

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#13213] opened 2022-01-20 14:48 UTC
**Describe the bug**
I was trying to run workflows where I give tags to the outputs, ones without `#`, I don't want them to propagate. In some tools, I was giving the same tags to several outputs. In these cases, running the workflow leads to these tools not being scheduled at all, with only the message "Invocation scheduling failed".
On the server, here is the error : 

```
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: Traceback (most recent call last):
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1751, in _execute_context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     cursor, statement, parameters, context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 968, in do_executemany
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     **kwargs
--
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     self._flush(objects)
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     transaction.rollback(_capture_exception=True)
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     with_traceback=exc_tb,
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     raise exception
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     flush_context.execute()
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     n.execute_aggregate(self, set_)
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 748, in execute_aggregate
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     mapper, [self.state] + [r.state for r in our_recs], uow
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 247, in save_obj
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     insert,
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1154, in _emit_insert_statements
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     statement, multiparams, execution_options=execution_options
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     return meth(self, args_10style, kwargs_10style, execution_options)
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     self, multiparams, params, execution_options
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     cache_hit=cache_hit,
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     e, statement, parameters, cursor, context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     raise exception
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1751, in _execute_context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     cursor, statement, parameters, context
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 968, in do_executemany
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     **kwargs
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/psycopg2/extras.py", line 1270, in execute_values
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]:     cur.execute(b''.join(parts))
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "tag_name_key"
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: DETAIL:  Key (name)=(quast_s1) already exists.
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: [SQL: INSERT INTO tag (type, parent_id, name) VALUES (%(type)s, %(parent_id)s, %(name)s) RETURNING tag.id]
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: [parameters: ({'type': 0, 'parent_id': None, 'name': 'quast_s1'}, {'type': 0, 'parent_id': None, 'name': 'quast_s1'}, {'type': 0, 'parent_id': None, 'name': 'quast_s1'}, {'type': 0, 'parent_id': None, 'name': 'quast_s1'})]
Jan 19 16:24:16 sn06.galaxyproject.eu python[4035035]: (Background on this error at: http://sqlalche.me/e/14/gkpj)

```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: current version on usegalaxy.eu

**To Reproduce**

1. Run [this workflow]() on [this history]()
2. Wait a few minutes, it tries to schedule the jobs
3. See error

**Expected behavior**

I don't think it is necessary for tags to be unique, but it is, there should be a warning in the workflow creation view, as there is for duplicated labels.

**Screenshots**

![image](https://user-images.githubusercontent.com/11195061/150217749-d048ca5f-7b66-45ed-be83-5db7cad026d7.png)

**Additional context**

**Comment by mvdbeek** [comment] 2022-01-20 15:04
@Delphine-L something went wrong with the links to the workflow and history.
From the user side there's no requirement for tags to be unique, but when we rapidly create new tags in different steps the if tag exists use it else create new fails.

**Comment by Delphine-L** [comment] 2022-01-20 15:08
history : https://usegalaxy.eu/u/delphine-l/h/debugging-name-tags
workflow: https://usegalaxy.eu/u/delphine-l/w/debuggin-name-tags

**Comment by mvdbeek** [comment] 2022-01-20 16:42
A quick workaround until we have a fix (which is probably tricky) is to create the tags you're going to use once in advance.

**Comment by mvdbeek** [comment] 2022-01-20 17:04
https://github.com/galaxyproject/galaxy/issues/13213 happens because steps and/or invocations are being scheduled within different threads. The solution would be to use a technique to ensure that we don't run into the unique key constrain violation.
That could be something like
```
def get_or_create(sa_session, tag_name):
    tag = Tag(name=tag_name)
    try:
        sa_session.add(tag)
        sa_session.flush()
    except IntegrityError:
        tag = sa_session.query(Tag).filter(Tag.name == tag_name).one()
		return tag
```

The problem is that we can't flush the original sqlalchemy session, since we might be in an inconsistent state (HDA/Job whatever just created) and since the expire_on_commit setting would mean that everything that has been touched so far would have to be fetched again from the database.

If we use a separate session we could get around this problem, but the TagAssiciation would probably fail since the Tag and its associated instance would come from different sessions. We could merge the related association into the separate session, or the `get_or_create` function could create the tag in the separate session and then return the create tag via the original session. I'll try that last one first.

**Comment by mvdbeek** [comment] 2022-01-22 18:04
Should be fixed in https://github.com/galaxyproject/galaxy/pull/13216

**Closed as completed by mvdbeek** 2022-01-22 18:04 UTC
Labels: kind/bug, area/database
