### ISSUE TITLE
Error when starting up/running a local galaxy 

### ISSUE THREAD

**Issue by Aymenchaalia** [galaxyproject/galaxy#7427] opened 2019-02-28 12:55 UTC
```
Traceback (most recent call last):
  File "./scripts/paster.py", line 26, in <module>
    serve.run()
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/serve.py", line 1062, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/serve.py", line 1068, in invoke
    exit_code = runner.run(args)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/serve.py", line 224, in run
    result = self.command()
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/serve.py", line 640, in command
    app = loadapp( app_spec, name=app_name, relative_to=base, global_conf=vars)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 294, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 320, in loadobj
    return context.create()
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 761, in create
    return self.object_type.invoke(self)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 276, in invoke
    filtered = context.next_context.create()
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 761, in create
    return self.object_type.invoke(self)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 188, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 91, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 42, in app_factory
    return paste_app_factory( global_conf, **kwargs )
  File "/usr/local/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 71, in paste_app_factory
    webapp.add_ui_controllers( 'galaxy.webapps.galaxy.controllers', app )
  File "/usr/local/galaxy/lib/galaxy/web/framework/webapp.py", line 123, in add_ui_controllers
    module = import_module( module_name )
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/galaxy/lib/galaxy/webapps/galaxy/controllers/data_admin.py", line 10, in <module>
    pkg_resources.require("simplejson")
  File "/usr/local/galaxy/.venv/local/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/galaxy/.venv/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: simplejson
```

**Comment by nsoranzo** [comment] 2019-02-28 12:57
Which version of Galaxy? You can find out by looking in `lib/galaxy/version.py`

**Comment by Aymenchaalia** [comment] 2019-02-28 12:59
VERSION_MAJOR = "17.09"

**Comment by Aymenchaalia** [comment] 2019-02-28 13:02
VERSION_MAJOR = "17.09"
VERSION_MINOR = "dev"
VERSION = VERSION_MAJOR + ('.' + VERSION_MINOR if VERSION_MINOR else '')

**Comment by martenson** [comment] 2019-02-28 15:21
duplicate of https://help.galaxyproject.org/t/error-when-starting-up-running-a-local-galaxy/699

**Closed as completed by martenson** 2019-02-28 15:21 UTC
