### ISSUE TITLE
Edit Attributes: missing confirmation bubble after successful change

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14584] opened 2022-09-07 23:41 UTC
**Describe the bug**
* Missing confirmation bubble when a dataset has a change on the first tab's fields.
* Seems to be only at ORG for the missing confirmation bubble, not at EU. Maybe introduced in `22.05.1`?
* Both have a highlighted SAVE button after the action -- this part is minor but would be nicer if not highlighted around the button after an action is completed (meaning, when form doesn't include any "not applied yet" changes).

**Galaxy Version and/or server at which you observed the bug**
**ORG:** Galaxy Version Galaxy version `22.05.1`
Commit: [e1561ad66582e31816320c90f1e8ec9d5bc698e5](https://github.com/galaxyproject/galaxy/commit/e1561ad66582e31816320c90f1e8ec9d5bc698e5)
**EU:** Galaxy Version Galaxy version `22.05`

**To Reproduce**
1. Go to a history that contains at least one dataset
2. Click on the pencil icon
3. Change the dataset name, then SAVE
4. See error: attributes updated but no confirmation bubble/message at the top of the view + SAVE button still highlighted
5. Start up a job using that dataset
6. Try to make another change while dataset is in use -- there is an expected warning at the top of the view + SAVE button still highlighted
7. Do the same at EU -- confirmation bubble is presented + + SAVE button still highlighted

**Expected behavior**
Green bubble with text message confirming the action at step 4 above (if successful) + SAVE button that is _not_ still highlighted

**Screenshots**

**ORG**

<img width="1035" alt="change-name" src="https://user-images.githubusercontent.com/8999735/189000518-3fd2a38d-1532-4caa-a8c5-fde2061bfb2f.png">

<img width="750" alt="change-name-again-while-dataset-is-an-input" src="https://user-images.githubusercontent.com/8999735/189000546-180a981b-dc0d-44f0-b548-5a92a25a7bd1.png">

<img width="744" alt="change-info-while-dataset-is-an-input" src="https://user-images.githubusercontent.com/8999735/189000569-fc1e7711-5634-43be-8057-1500014f93f8.png">

**EU**

<img width="703" alt="change-name-EU" src="https://user-images.githubusercontent.com/8999735/189001181-2c75ebeb-0a59-4751-9e06-67443b871224.png">

**Additional context**
Not sure which Milestone to use

**Comment by mvdbeek** [comment] 2022-09-08 08:35
> * See error: attributes updated but no confirmation bubble/message at the top of the view + SAVE button still highlighted

That doesn't happen for me. Do you have more details on how to reproduce this ? Do you maybe not have permissions to change the dataset ? We haven't changed anything there inbetween the few commits that differ on .eu and .org, and that might explain this.

**Comment by davelopez** [comment] 2022-09-14 15:22
I tried to reproduce this but also works for me.

@jennaj I will close this for now, but if you can reproduce it again consistently, please reopen :)

However, I tried a bit of a corner case importing a dataset from a library and then removing access permission, and the Edit UI seems a bit broken in that case, I'll create a different issue for that...

**Closed as completed by davelopez** 2022-09-14 15:22 UTC
Labels: area/UI-UX
