### ISSUE TITLE
Unable to undelete collection

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3957] opened 2017-04-23 11:18 UTC
@ayaanhossain wrote in https://github.com/galaxyproject/training-material/issues/279
```
I was following this tutorial, and I deleted a collection of HISAT mapped reads.
Later I wanted the collection back but didn't find an undelete option like those found
for normal datasets.
```

**Comment by nsoranzo** [comment] 2017-04-23 20:05
Duplicate of #2319, for a workaround see https://github.com/galaxyproject/galaxy/issues/2237#issuecomment-213535641 .

**Closed as completed by nsoranzo** 2017-04-23 20:05 UTC
